### PR TITLE
Task/improve ping ui

### PR DESCRIPTION
**Pull request by adamczykba**
**Changes in this PR:**
- when controller is not configured or functionality is not implemented, disabled button along with info label appears instead of "Check connection" button and error at the top of the page
- *Check connection* button has now different styling to appear more interactive

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/245)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/245)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @adamczykba and @Crystalzord)

___
*[oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java, line 570 at r3](https://reviewable.io/reviews/servicecatalog/oscm/245#-L_qNQA84TyLRxUP4EZT:-L_qNQA84TyLRxUP4EZU:by2ouml) ([raw file](https://github.com/servicecatalog/oscm/blob/1390e194b6428805b1ffa4114618617a058cdb30/oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java#L570)):*
> ```Java
>                         logger.error("Unable to connect to VMware service", e);
>                         exception = new ServiceNotReachableException(
>                                 "Unable to connect to VMWare service");
> ```

Please use i18n. The checked messages appearing in the APP UI need to be localized.
___
*[oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java, line 623 at r3](https://reviewable.io/reviews/servicecatalog/oscm/245#-L_qOLa95PVGrj6wLQ8d:-L_qOLaA-45hWkeKVx5i:boqtvlk) ([raw file](https://github.com/servicecatalog/oscm/blob/1390e194b6428805b1ffa4114618617a058cdb30/oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java#L623)):*
> ```Java
>                 } else if (controllerSettings.isEmpty()) {
>                         exception = new ConfigurationException(
>                                 "Unable to get controller settings. Controller settings map is empty");
> ```

- Add localization (as above).  
- Combine both cases with a clear user message. Generally, please avoid intern/java terminolgy - such as "settings are null", "map is empty" which have poor use and rather appear as bugs to the users. 
(Of course another and valid aspect of use is debug logging: Where really required add such info with logging using debug level. Nevertheless, also creating such debug info requires some caution considering GBDR compliance and risk of information leaks)
___
*[oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java, line 671 at r3](https://reviewable.io/reviews/servicecatalog/oscm/245#-L_qVMTp5eqeodq84Up0:-L_qVMTp5eqeodq84Up1:b2nreh6) ([raw file](https://github.com/servicecatalog/oscm/blob/1390e194b6428805b1ffa4114618617a058cdb30/oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java#L671)):*
> ```Java
>                                 "Unable to get controller settings. VCenter list is empty");
>                         throw exception;
>                 }
> ```

Same as above.

**Review by adamczykba — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/245)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @Crystalzord and @GoebelL)

___
*[oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java, line 570 at r3](https://reviewable.io/reviews/servicecatalog/oscm/245#-L_qNQA84TyLRxUP4EZT:-L_wP3Th1JOClto5OoPB:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/1390e194b6428805b1ffa4114618617a058cdb30/oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java#L570)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Please use i18n. The checked messages appearing in the APP UI need to be localized.
</blockquote></details>

Done.
___
*[oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java, line 623 at r3](https://reviewable.io/reviews/servicecatalog/oscm/245#-L_qOLa95PVGrj6wLQ8d:-L_wP5zI0ygsL_Ilraq2:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/1390e194b6428805b1ffa4114618617a058cdb30/oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java#L623)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

- Add localization (as above).  
- Combine both cases with a clear user message. Generally, please avoid intern/java terminolgy - such as "settings are null", "map is empty" which have poor use and rather appear as bugs to the users. 
(Of course another and valid aspect of use is debug logging: Where really required add such info with logging using debug level. Nevertheless, also creating such debug info requires some caution considering GBDR compliance and risk of information leaks)
</blockquote></details>

Done.
___
*[oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java, line 671 at r3](https://reviewable.io/reviews/servicecatalog/oscm/245#-L_qVMTp5eqeodq84Up0:-L_wPIKrCNz8JlfMnaDb:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/1390e194b6428805b1ffa4114618617a058cdb30/oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java#L671)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

**Review by Crystalzord — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 4 files at r2, 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/245)* status: all files reviewed, 11 unresolved discussions (waiting on @adamczykba and @GoebelL)

___
*[oscm-app-startup/javares/org/oscm/app/ui/i18n/messages_en.properties, line 124 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-2MXA7UaK0-zhHT0d:-La-2MXB42iZLX-O8BGK:b2c4cxl) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-startup/javares/org/oscm/app/ui/i18n/messages_en.properties#L124)):*
> ```INI
> app.message.error.unable.to.get.settings=Unable to get controller settings
> app.message.error.unable.to.get.settings.no.vcenters=Unable to get controller settings. No VCenter has been found
> app.message.error.controller.param.empty=One of contoller config parameters is not filled in
> ```

cont(r)oller. Fix typo.
___
*[oscm-app-startup/javares/org/oscm/app/ui/i18n/messages_ja.properties, line 22 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-2kIVASAuN-2r3tOk:-La-2kIVASAuN-2r3tOl:b-799go0) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-startup/javares/org/oscm/app/ui/i18n/messages_ja.properties#L22)):*
> ```INI
> ui.app.pleaseSelect=-- \u9078\u629e --
> ui.app.suspend=Catalog Manager\u306e\u901a\u4fe1\u30a8\u30e9\u30fc\u306e\u305f\u3081\u3001APP\u306f\u4e2d\u6b62\u306b\u306a\u308a\u307e\u3057\u305f\u3002
> ui.app.controller.not.configured=This controller is not configured
> ```

Missing app.message.error.* localized strings.
___
*[oscm-app-startup/WebContent/keyValueEditor.xhtml, line 19 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-3yno-HPVUxFc2sLj:-La-3ynpArlU2wHJf8Rr:bgc0obj) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-startup/WebContent/keyValueEditor.xhtml#L19)):*
> ```HTML
>         function setOnSubmit(flag) { onSubmitFlag = flag; }
> 
>         function doCheckConnection() {
> ```

This is unused.
___
*[oscm-app-startup/WebContent/keyValueEditor.xhtml, line 48 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-4aUFEEdrSg1iwyWQ:-La-4aUG2OyiH1duCL8H:bda7vw8) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-startup/WebContent/keyValueEditor.xhtml#L48)):*
> ```HTML
>     </div>
> 
>     <div id="progressDiv" class="progressOverlay">
> ```

check if progressDiv is necessary (it is in header.xhtml already)
___
*[oscm-app-vmware/javares/org/oscm/app/vmware/i18n/messages_en.properties, line 227 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-5_x46b1vuX6zGro8:-La-5_x46b1vuX6zGro9:b-9cckmj) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-vmware/javares/org/oscm/app/vmware/i18n/messages_en.properties#L227)):*
> ```INI
> ui.config.error.unable.to.connect.to.vmware=Unable to connect to VMware service
> ui.config.error.unable.to.get.settings     =Unable to get controller settings
> ui.config.error.unable.to.get.settings.no.vcenters=Unable to get controller settings. No VCenter has been found
> ```

fix formatting
___
*[oscm-app-vmware/javares/org/oscm/app/vmware/i18n/messages_ja.properties, line 135 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-5eMVDEf5MwzymUcw:-La-5eMW2RIpC9ZHSpHc:b-7ropln) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-vmware/javares/org/oscm/app/vmware/i18n/messages_ja.properties#L135)):*
> ```INI
> ui.config.error.unable.to.get.settings     =Unable to get controller settings
> ui.config.error.unable.to.get.settings.no.vcenters=Unable to get controller settings. No VCenter has been found
> ui.config.error.controller.param.empty     =One of contoller config parameters is not filled in
> ```

ditto
___
*[oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java, line 619 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-84ug4bLkxu4kg8oa:-La-84ug4bLkxu4kg8ob:b-o52y53) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java#L619)):*
> ```Java
>                 }
> 
>                 if (controllerSettings == null) {
> ```

check if this can be simplified
___
*[oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java, line 669 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-88MJDEvSgaBZ0SHI:-La-88MJDEvSgaBZ0SHJ:b-o52y53) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java#L669)):*
> ```Java
>                 List<VCenter> vCenters = getVCenterList(controllerSettings);
> 
>                 if (vCenters == null) {
> ```

check if this can be simplified

**Review by adamczykba — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/245)* status: 10 of 16 files reviewed, 11 unresolved discussions (waiting on @Crystalzord and @GoebelL)

___
*[oscm-app-startup/javares/org/oscm/app/ui/i18n/messages_en.properties, line 124 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-2MXA7UaK0-zhHT0d:-La-fXTW1hkYFaCyG0Mx:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-startup/javares/org/oscm/app/ui/i18n/messages_en.properties#L124)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

cont(r)oller. Fix typo.
</blockquote></details>

Done.
___
*[oscm-app-startup/javares/org/oscm/app/ui/i18n/messages_ja.properties, line 22 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-2kIVASAuN-2r3tOk:-La-esNL1ayBU4nJ3wsv:br1eqft) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-startup/javares/org/oscm/app/ui/i18n/messages_ja.properties#L22)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Missing app.message.error.* localized strings.
</blockquote></details>

These messages aren't missing. They are in property files of oscm-app-vmware module. On the other hand I've deleted unused keys from oscm-app-startup
___
*[oscm-app-startup/WebContent/keyValueEditor.xhtml, line 19 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-3yno-HPVUxFc2sLj:-La-fYQm-ftdw48kZa-q:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-startup/WebContent/keyValueEditor.xhtml#L19)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

This is unused.
</blockquote></details>

Done.
___
*[oscm-app-startup/WebContent/keyValueEditor.xhtml, line 48 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-4aUFEEdrSg1iwyWQ:-La01sY0EbZxJjTJUSbo:b-95x6bi) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-startup/WebContent/keyValueEditor.xhtml#L48)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

check if progressDiv is necessary (it is in header.xhtml already)
</blockquote></details>

It is necessary. I've checked and after removing it, spinner doesn't show
___
*[oscm-app-vmware/javares/org/oscm/app/vmware/i18n/messages_en.properties, line 227 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-5_x46b1vuX6zGro8:-La-xy2-1raFj5A2RRg7:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-vmware/javares/org/oscm/app/vmware/i18n/messages_en.properties#L227)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

fix formatting
</blockquote></details>

Done.
___
*[oscm-app-vmware/javares/org/oscm/app/vmware/i18n/messages_ja.properties, line 135 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-5eMVDEf5MwzymUcw:-La-xz7CDjRa2K8ly2ax:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-vmware/javares/org/oscm/app/vmware/i18n/messages_ja.properties#L135)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java, line 619 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-84ug4bLkxu4kg8oa:-La06zaH997HyH2cwLNx:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java#L619)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

check if this can be simplified
</blockquote></details>

Done.
___
*[oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java, line 669 at r4](https://reviewable.io/reviews/servicecatalog/oscm/245#-La-88MJDEvSgaBZ0SHI:-La03fxmC8_yB7RmPd8n:b-noh8kv) ([raw file](https://github.com/servicecatalog/oscm/blob/bed7abe69b5cfff879e6faa275e91c603bdc1e34/oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMController.java#L669)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

check if this can be simplified
</blockquote></details>

Done. Simplified

**Review by Crystalzord — APPROVED** [review]
> Reviewed 5 of 5 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/245)* status: all files reviewed, 3 unresolved discussions (waiting on @GoebelL)

**Pull request merged**
