### PR TITLE
SSO cleanup

### PR DESCRIPTION
**Pull request by kowalczyka**
**Changes in this Pull Request:**
- saml related code and configuration cleanup

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [ ] changes were tested manually
- [ ] unit tests were properly implemented - N/A
- [ ] communication about interdependent changes has been sent to the team (if applicable) - N/A
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM Build And Push job](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Docker_Build_and_push/459/)
- [OSCM Pull And Start job](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Docker_pull_and_start/740/)
- [OSCM WS Tests INTERNAL job](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_WS_Tests_INTERNAL/93/)
- [OSCM WS Tests OIDC job](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_WS_Tests_OIDC/135/)
- [BES MASTER IT job](http://10.140.16.80:8080/view/.MASTER/job/BES_MASTER_IT/1603/)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/658)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 256 of 256 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/658)* status: all files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

___
*[oscm-webservices-tests/javares/wstests-ci7.properties, line 19 at r1](https://reviewable.io/reviews/servicecatalog/oscm/658#-M0HqWxN8rRXjRsZ6zw4:-M0HqWxN8rRXjRsZ6zw5:b-44dnkg) ([raw file](https://github.com/servicecatalog/oscm/blob/626686676f048d466f9f60df08feb5485ca67200/oscm-webservices-tests/javares/wstests-ci7.properties#L19)):*
> ```INI
> user.supplier.password=secret
> 
> auth.mode=INTERNAL
> ```

Is this really needed to have a host specific file in GitHub? If such settings are needed by WS tests, I'd prefer to have them in a single file that is environment agnostic. E.g. put static part in one template file that is piped to envsubst to generate the settings at runtime from given environment variables.

**Review by GoebelL — COMMENTED** [review]
IMHO we need a new datamodel version with migration task to remove SAML SSO related configsettings from existing repositories. 
For implementing DB migration tasks just have a look to /oscm-devruntime/javares/sql/upd_postgresql_02_10_03.sql - this version SQL invokes database migration to ensure proper organization names for OIDC.

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/658)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-webservices-tests/javares/wstests-ci7.properties, line 19 at r1](https://reviewable.io/reviews/servicecatalog/oscm/658#-M0HqWxN8rRXjRsZ6zw4:-M0IAx3i0ED6XFpuNnlQ:b-52tqdk) ([raw file](https://github.com/servicecatalog/oscm/blob/626686676f048d466f9f60df08feb5485ca67200/oscm-webservices-tests/javares/wstests-ci7.properties#L19)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Is this really needed to have a host specific file in GitHub? If such settings are needed by WS tests, I'd prefer to have them in a single file that is environment agnostic. E.g. put static part in one template file that is piped to envsubst to generate the settings at runtime from given environment variables.
</blockquote></details>

This file was commited by mistake. WS tests no longer require host specific file. File ha been removed.

**Review by kowalczyka — COMMENTED** [review]
Added db script.

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/658#-:-M0IiFjv10Gk4bhytRp5:bvr5zdy)* status: 255 of 256 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Comment by GoebelL** [comment]
> 
> 
> Added db script.
> 
> > _[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/658#-:-M0IiFjv10Gk4bhytRp5:bvr5zdy)_ status: 255 of 256 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

Please add a schema test.

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/658)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
