### PR TITLE
Refactor PSP management MVC

### PR DESCRIPTION
**Pull request by GoebelL**
**Changes in this Pull Request:**
- Reduce complexity of OperatorOrgBean
- Extract PSP management in separate MVC
- Raise unit test coverage for PSP management

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [x] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [ ] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/755)

### CODE REVIEW

**Review by cworf91 — COMMENTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/755)* status: all files reviewed, 4 unresolved discussions (waiting on @GoebelL)

___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java, line 189 at r1](https://reviewable.io/reviews/servicecatalog/oscm/755#-M3z0mOMECnqWIm-2ui9:-M3z-ek29XmRPFcnVO6X:b1t3saw) ([raw file](https://github.com/servicecatalog/oscm/blob/9ca5a2bd1cb579446f2bfbb49f5a54993df8a72f/oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java#L189)):*
> ```Java
>     // when
>     ctrl.setToken("token");
>     ctrl.savePaymentType();
> ```

//Then 
assert mehtod () is missing. 
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java, line 200 at r1](https://reviewable.io/reviews/servicecatalog/oscm/755#-M3z0wiR73-wESu-ldQ0:-M3z-toS9XSmzcZGfosO:bb7eybp) ([raw file](https://github.com/servicecatalog/oscm/blob/9ca5a2bd1cb579446f2bfbb49f5a54993df8a72f/oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java#L200)):*
> ```Java
>     // when
>     ctrl.getModel().setSelectedPaymentTypeKey(Long.valueOf(current));
>     ctrl.prepareDataForEditPaymentType();
> ```

dito
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java, line 210 at r1](https://reviewable.io/reviews/servicecatalog/oscm/755#-M3z0xGqAGRz6AJBkMHX:-M3z-uw64DC2vsxVran5:bb7eybp) ([raw file](https://github.com/servicecatalog/oscm/blob/9ca5a2bd1cb579446f2bfbb49f5a54993df8a72f/oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java#L210)):*
> ```Java
>     // when
>     ctrl.getModel().setSelectedPaymentTypeKey(Long.valueOf(1));
>     ctrl.prepareDataForEditPaymentType();
> ```

dito
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java, line 220 at r1](https://reviewable.io/reviews/servicecatalog/oscm/755#-M3z0yds0uKEdJPBNEfl:-M3z-x7o9eFqWPQ6a2JZ:bb7eybp) ([raw file](https://github.com/servicecatalog/oscm/blob/9ca5a2bd1cb579446f2bfbb49f5a54993df8a72f/oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java#L220)):*
> ```Java
>     // when
>     ctrl.getModel().setSelectedPaymentTypeKey(null);
>     ctrl.prepareDataForEditPaymentType();
> ```

dito

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/755)* status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @cworf91)

___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java, line 189 at r1](https://reviewable.io/reviews/servicecatalog/oscm/755#-M3z0mOMECnqWIm-2ui9:-M3zoMvZBge_EStvnJhG:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/9ca5a2bd1cb579446f2bfbb49f5a54993df8a72f/oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java#L189)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

//Then 
assert mehtod () is missing. 
</blockquote></details>

Done.
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java, line 200 at r1](https://reviewable.io/reviews/servicecatalog/oscm/755#-M3z0wiR73-wESu-ldQ0:-M3zoO3f3LESbqcNhmFL:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/9ca5a2bd1cb579446f2bfbb49f5a54993df8a72f/oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java#L200)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

dito
</blockquote></details>

Done.
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java, line 210 at r1](https://reviewable.io/reviews/servicecatalog/oscm/755#-M3z0xGqAGRz6AJBkMHX:-M3zoXjm2K4aXG9l_pR6:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/9ca5a2bd1cb579446f2bfbb49f5a54993df8a72f/oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java#L210)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

dito
</blockquote></details>

Done.
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java, line 220 at r1](https://reviewable.io/reviews/servicecatalog/oscm/755#-M3z0yds0uKEdJPBNEfl:-M3zo_hn17EXWspCEZ2L:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/9ca5a2bd1cb579446f2bfbb49f5a54993df8a72f/oscm-portal-unittests/javasrc/org/oscm/ui/beans/operator/ManagePSPCtrlTest.java#L220)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

dito
</blockquote></details>

Done.

**Review by cworf91 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/755#-:-M3zpEZu0opcfQCW_8_F:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @cworf91)

**Review by cworf91 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/755#-:-M3zqzHD3ZY0Ce5NBSl9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request closed without merging**
