### PR TITLE
UI tests with chrome driver

### PR DESCRIPTION
**Pull request by kowalczyka**
**Changes in this Pull Request:**
Configuration for running UI tests with chrome driver

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Integration_Tests_OIDC/29/

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/635)

### CODE REVIEW

**Review by adamczykba — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/635)* status: all files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

___
*[oscm-webtest-base/src/main/java/org/oscm/webtest/PortalTester.java, line 124 at r1](https://reviewable.io/reviews/servicecatalog/oscm/635#-LzkWHm3C7oljQxUbRkW:-LzkWHm495Kk_1KdURIz:b-rktuey) ([raw file](https://github.com/servicecatalog/oscm/blob/aa23cfec481747705eba967b6554fc0a3f0d1855/oscm-webtest-base/src/main/java/org/oscm/webtest/PortalTester.java#L124)):*
> ```Java
>     executor.executeScript("arguments[0].click();", logoutLink);
> 
>     //driver.findElement(By.id(PortalHtmlElements.PORTAL_LINK_LOGOUT)).click();
> ```

Is it necessary to have commented code here?

**Review by kowalczyka — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/635#-:-LzkYH-qCi_VkV_P4w5I:bb6un1j)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @adamczykba and @kowalczyka)

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/635)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @adamczykba)

___
*[oscm-webtest-base/src/main/java/org/oscm/webtest/PortalTester.java, line 124 at r1](https://reviewable.io/reviews/servicecatalog/oscm/635#-LzkWHm3C7oljQxUbRkW:-LzkYKOoE0BgItfz9hO-:bb6un1j) ([raw file](https://github.com/servicecatalog/oscm/blob/aa23cfec481747705eba967b6554fc0a3f0d1855/oscm-webtest-base/src/main/java/org/oscm/webtest/PortalTester.java#L124)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Is it necessary to have commented code here?
</blockquote></details>

Done

**Review by adamczykba — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/635)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by adamczykba — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/635#-:-LzkZ1N3AUIu_iEbsROJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
