### PR TITLE
Task/652 2

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
- Added uniqueness validation of organization name while creating a new organization.  

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [x] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [ ] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
N/A

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/690)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/690)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @mchudy-fujitsu)

___
*[oscm-internal-interfaces/javasrc/org/oscm/internal/tenant/ManageTenantService.java, line 95 at r1](https://reviewable.io/reviews/servicecatalog/oscm/690#-M1VIHK99IrfJrfRrLPk:-M1VIHK99IrfJrfRrLPl:b-8ycmjr) ([raw file](https://github.com/servicecatalog/oscm/blob/9679658c6796f5e343bb1ef20009d6272e9d1917/oscm-internal-interfaces/javasrc/org/oscm/internal/tenant/ManageTenantService.java#L95)):*
> ```Java
>     */
>     void validateOrgNameUniquenessInTenant(String orgName, String tenantId) throws ValidationException;
>     
> ```

```
Javadoc completion....
/**
* Checks if given organization name already exist for the given tenant.
* @param orgName organization name
* @param tenantId tenant ID
* @throws ValidationException ...
```

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/690)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @mchudy-fujitsu)

___
*[oscm-build/ivy-build.xml, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm/690#-M1VK0Q2Ao46RSyx5X6P:-M1VK0Q350uZajIFTP2J:bt54h2s) ([raw file](https://github.com/servicecatalog/oscm/blob/9679658c6796f5e343bb1ef20009d6272e9d1917/oscm-build/ivy-build.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

This modification refers to some jitpack branch "task~652_2-SNAPSHOT".  But I don't find any related pull request in the interface repo. Is this change needed?

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/690)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @mchudy-fujitsu)

___
*[oscm-internal-interfaces/javasrc/org/oscm/internal/tenant/ManageTenantService.java, line 95 at r1](https://reviewable.io/reviews/servicecatalog/oscm/690#-M1VIHK99IrfJrfRrLPk:-M1VLO2x-uUFexZ40fx1:b-6c4tp1) ([raw file](https://github.com/servicecatalog/oscm/blob/9679658c6796f5e343bb1ef20009d6272e9d1917/oscm-internal-interfaces/javasrc/org/oscm/internal/tenant/ManageTenantService.java#L95)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

```
Javadoc completion....
/**
* Checks if given organization name already exist for the given tenant.
* @param orgName organization name
* @param tenantId tenant ID
* @throws ValidationException ...
```
</blockquote></details>

Typo: if given organization name already exist**s**...

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/690)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @GoebelL)

___
*[oscm-build/ivy-build.xml, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm/690#-M1VK0Q2Ao46RSyx5X6P:-M1VS6cL4nuHEauTHRX-:bhkfi3p) ([raw file](https://github.com/servicecatalog/oscm/blob/9679658c6796f5e343bb1ef20009d6272e9d1917/oscm-build/ivy-build.xml#L1)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

This modification refers to some jitpack branch "task~652_2-SNAPSHOT".  But I don't find any related pull request in the interface repo. Is this change needed? 
</blockquote></details>

Created PR in oscm-commons and oscm-interfaces.
oscm-commons - added exception messeges to resource bundle
oscm-interfaces - added new method to TenantService interface and new enum to ValidationException enum
___
*[oscm-internal-interfaces/javasrc/org/oscm/internal/tenant/ManageTenantService.java, line 95 at r1](https://reviewable.io/reviews/servicecatalog/oscm/690#-M1VIHK99IrfJrfRrLPk:-M1VSolX1cGD3W7wxQrP:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/9679658c6796f5e343bb1ef20009d6272e9d1917/oscm-internal-interfaces/javasrc/org/oscm/internal/tenant/ManageTenantService.java#L95)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Typo: if given organization name already exist**s**...
</blockquote></details>

Done.

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/690)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-build/ivy-build.xml, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm/690#-M1VK0Q2Ao46RSyx5X6P:-M1yVWFT1xJ5vK-4KJjL:b8unjs) ([raw file](https://github.com/servicecatalog/oscm/blob/9679658c6796f5e343bb1ef20009d6272e9d1917/oscm-build/ivy-build.xml#L1)):*
<details><summary><i>Previously, mchudy-fujitsu wrote…</i></summary><blockquote>

Created PR in oscm-commons and oscm-interfaces.
oscm-commons - added exception messeges to resource bundle
oscm-interfaces - added new method to TenantService interface and new enum to ValidationException enum

</blockquote></details>

OK. 
To ensure that Travis stays green, the suggested merge procedure is:
1. OSCM PR in Master referring to task snapshots 
2. Merge messages from oscm-commons in master
3. Merge interfaces from oscm-interfaces in master
4. Follow-up PR to update references back to master snapshots 
 Please watch Travis builds in all three repos.

**Review by GoebelL — APPROVED** [review]
> Reviewed 2 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/690)* status: 2 of 15 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Pull request merged**
