### PR TITLE
Bug#1167 my subscription page search issue

### LINKED ISSUE #1167: marketplace: on My Subscriptions page, search term is not still displayed
**Version Info**
19.0 2021/01/19

**Describe the bug**
Search term is no longer displayed after clicking enter

**How to Reproduce**
1. login Marketplace
2. goto My Subscription
3. tip "Sample" into search field
4. click enter

**Observed behavior**
the subscription you are looking for is shown but the search field is empty.
When you leave the page and go back, only the searched subscriptions are shown, although the search field is empty

**Expected behavior**
search term is still shown

**Screenshots**
escm3
after  tip Sample and click
escm4

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Clear searchPhraseProperty after page unload

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**
- add a screenshot illustrating your change

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1174)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1174)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @KabacinskiPiotr)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/subscriptionFinderBootstrap.xhtml, line 27 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1174#-MRuGUol3Aeqe_V6eRuB:-MRuGUol3Aeqe_V6eRuC:b-2ur7d) ([raw file](https://github.com/servicecatalog/oscm/blob/b9e8f898e58174b338098c5f6211a037d85d6a96/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/subscriptionFinderBootstrap.xhtml#L27)):*
> ```HTML
>   window.onunload = function() {
>    document.getElementById('subListForm:searchField').value = "";
>    document.getElementById('subListForm:submitLink').click();
> ```

What is the purpose of this inline javascript? Please avoid this if possible.

**Comment by Piotr-K8i** [comment]
> > _[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1174)_ status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @KabacinskiPiotr)
> 
> _[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/subscriptionFinderBootstrap.xhtml, line 27 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1174#-MRuGUol3Aeqe_V6eRuB:-MRuGUol3Aeqe_V6eRuC:b-2ur7d) ([raw file](https://github.com/servicecatalog/oscm/blob/b9e8f898e58174b338098c5f6211a037d85d6a96/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/subscriptionFinderBootstrap.xhtml#L27)):_
> 
> > ```
> >   window.onunload = function() {
> >    document.getElementById('subListForm:searchField').value = "";
> >    document.getElementById('subListForm:submitLink').click();
> > ```
> 
> What is the purpose of this inline javascript? Please avoid this if possible.

The goal is to solve the problem:
_When you leave the page and go back, only the searched subscriptions are shown, although the search field is empty_ .

I think that without a thorough reconstruction of the backend I cannot do anything better.

**Review by Piotr-K8i — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1174)* status: all files reviewed, 1 unresolved discussion (waiting on @farmakiG and @GoebelL)

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1174)* status: all files reviewed, 1 unresolved discussion (waiting on @farmakiG and @KabacinskiPiotr)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/subscriptionFinderBootstrap.xhtml, line 27 at r2](https://reviewable.io/reviews/servicecatalog/oscm/1174#-MS9Rb_Z2y7xGKpqqZKL:-MS9Rb_Z2y7xGKpqqZKM:b-a0ge0y) ([raw file](https://github.com/servicecatalog/oscm/blob/f0072f578572587fefe041e6ab85c8a4739a17f7/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/subscriptionFinderBootstrap.xhtml#L27)):*
> ```HTML
>   window.onunload = function() {
>    document.getElementById('#{formId}:searchField').value = "";
>    document.getElementById('#{formId}:submitLink').click();
> ```

Please move the java script function in AdmUtils

**Comment by KabacinskiPiotr** [comment]
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/subscriptionFinderBootstrap.xhtml, line 27 at r2](https://reviewable.io/reviews/servicecatalog/oscm/1174#-MS9Rb_Z2y7xGKpqqZKL:-MSRyAPx8B7damWZyff_:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/f0072f578572587fefe041e6ab85c8a4739a17f7/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/subscriptionFinderBootstrap.xhtml#L27)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Please move the java script function in AdmUtils
</blockquote></details>

Done.

**Review by farmakiG — DISMISSED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1174)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1174)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
