### PR TITLE
Task/unit tests

### PR DESCRIPTION
**Pull request by GoebelL**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/443)

### CODE REVIEW

**Review by GoebelL — COMMENTED** [review]
> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/443)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cworf91 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/443#-:-Lozss3BAEVSSCyJWeKh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cworf91)

**Review by cworf91 — APPROVED** [review]

**Review by cworf91 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/443#-:-LozxuGrDQCPDG-CS6iG:bnfp4nl)* status: 29 of 30 files reviewed, all discussions resolved

**Review by cworf91 — DISMISSED** [review]
:lgtm:

> Reviewed 29 of 29 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/443#-:-Lozxy5MAI3CL_G5PmN0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cworf91 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/443#-:-Lp-79Af-8GNhGxUWVR6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
