### PR TITLE
[Subscription UI] Subscription details maim page

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
- Subscription main details page.

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [x] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [x] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
N/A

**Screenshot (if applicable):**
FireShot Capture 046 - Marketplace - 10 140 18 99
FireShot Capture 047 - Marketplace - 10 140 18 99

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/870)

### CODE REVIEW

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/870)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/playground/account/subscriptionDetails.xhtml, line 78 at r1](https://reviewable.io/reviews/servicecatalog/oscm/870#-M7vU3FR5K2XPUvBVXgg:-M7vU3FR5K2XPUvBVXgh:b-m6kow1) ([raw file](https://github.com/servicecatalog/oscm/blob/4c94d1560bf443b53cd90beacc234212eba977d4/oscm-portal/WebContent/marketplace/playground/account/subscriptionDetails.xhtml#L78)):*
> ```HTML
>         
> 
>         <div class="list-group list-group-horizontal-sm text-center" id="list-tab" role="tablist">
> ```

I suggest to add a common tab styling class to all such tab bars, e.g. 'tabControl', in the marketplace UI (search for list-group-item,  in order to have unique customization with mp.css.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 5 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/870)* status: 5 of 14 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @mchudy-fujitsu)

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/playground/account/subscriptionUdaDetails.xhtml, line 2 at r1](https://reviewable.io/reviews/servicecatalog/oscm/870#-M7vXjYU-cBUYWebu5gh:-M7vXjYU-cBUYWebu5gi:b-5zepbz) ([raw file](https://github.com/servicecatalog/oscm/blob/4c94d1560bf443b53cd90beacc234212eba977d4/oscm-portal/WebContent/marketplace/playground/account/subscriptionUdaDetails.xhtml#L2)):*
> ```HTML
> 
> 
> ```

What is this TODO about?

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/playground/account/subscriptionUdaDetails.xhtml, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm/870#-M7vXu223x-OQGDXiPk3:-M7vXu235uMOXHTZzMEM:b9qz15l) ([raw file](https://github.com/servicecatalog/oscm/blob/4c94d1560bf443b53cd90beacc234212eba977d4/oscm-portal/WebContent/marketplace/playground/account/subscriptionUdaDetails.xhtml#L1)):*
> ```HTML
> 
> ```

Update Copyright.

**Review by farmakiG — COMMENTED** [review]
> Reviewed 2 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/870)* status: 6 of 14 files reviewed, 3 unresolved discussions (waiting on @farmakiG and @mchudy-fujitsu)

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/playground/subscriptions/paymentInclude.xhtml, line 2 at r1](https://reviewable.io/reviews/servicecatalog/oscm/870#-M7vY8zy7KSK0I9d6YL-:-M7vY8zy7KSK0I9d6YL0:b-sz807m) ([raw file](https://github.com/servicecatalog/oscm/blob/4c94d1560bf443b53cd90beacc234212eba977d4/oscm-portal/WebContent/marketplace/playground/subscriptions/paymentInclude.xhtml#L2)):*
> ```
> -->
> ```
TODO?

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/playground/subscriptions/priceModelDetails.xhtml, line 17 at r1](https://reviewable.io/reviews/servicecatalog/oscm/870#-M7vYFIXAzftSZTFPFXa:-M7vYFIXAzftSZTFPFXb:b-9vbc1b) ([raw file](https://github.com/servicecatalog/oscm/blob/4c94d1560bf443b53cd90beacc234212eba977d4/oscm-portal/WebContent/marketplace/playground/subscriptions/priceModelDetails.xhtml#L17)):*
> ```HTML
>     <h1>
>       <h:outputText style="float:left;" value="#{msg['marketplace.services.overview']}" />
>     </h1>
> ```

Please avoid inline styles where possible.

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/870)* status: 6 of 14 files reviewed, 5 unresolved discussions (waiting on @farmakiG and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/playground/account/subscriptionUdaDetails.xhtml, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm/870#-M7vXu223x-OQGDXiPk3:-M7vZEGN8-Zt2CG_vXJ9:b-avf0v4) ([raw file](https://github.com/servicecatalog/oscm/blob/4c94d1560bf443b53cd90beacc234212eba977d4/oscm-portal/WebContent/marketplace/playground/account/subscriptionUdaDetails.xhtml#L1)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Update Copyright.
</blockquote></details>

This pull request is about the main page of subscription details, these pages are just copy required by the main page to not throw operation failed. Subpages have their own tasks in the #851 epic. The pages with  are not part of current PR but part of the same epic.
___
*[oscm-portal/WebContent/marketplace/playground/account/subscriptionUdaDetails.xhtml, line 2 at r1](https://reviewable.io/reviews/servicecatalog/oscm/870#-M7vXjYU-cBUYWebu5gh:-M7v_-_Y2EQvb0ZD-gBW:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/4c94d1560bf443b53cd90beacc234212eba977d4/oscm-portal/WebContent/marketplace/playground/account/subscriptionUdaDetails.xhtml#L2)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

What is this TODO about?
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/playground/subscriptions/paymentInclude.xhtml, line 2 at r1](https://reviewable.io/reviews/servicecatalog/oscm/870#-M7vY8zy7KSK0I9d6YL-:-M7v_25q8m1eSN23Srdo:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/4c94d1560bf443b53cd90beacc234212eba977d4/oscm-portal/WebContent/marketplace/playground/subscriptions/paymentInclude.xhtml#L2)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

> ```
> -->
> ```
TODO?
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/playground/subscriptions/priceModelDetails.xhtml, line 17 at r1](https://reviewable.io/reviews/servicecatalog/oscm/870#-M7vYFIXAzftSZTFPFXa:-M7v_2vg48l3GIaDEcJU:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/4c94d1560bf443b53cd90beacc234212eba977d4/oscm-portal/WebContent/marketplace/playground/subscriptions/priceModelDetails.xhtml#L17)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Please avoid inline styles where possible.
</blockquote></details>

Done.

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/870)* status: 6 of 14 files reviewed, 5 unresolved discussions (waiting on @farmakiG and @GoebelL)

___
*[oscm-portal/WebContent/marketplace/playground/account/subscriptionDetails.xhtml, line 78 at r1](https://reviewable.io/reviews/servicecatalog/oscm/870#-M7vU3FR5K2XPUvBVXgg:-M7viNTQAGOl9THo5hvL:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/4c94d1560bf443b53cd90beacc234212eba977d4/oscm-portal/WebContent/marketplace/playground/account/subscriptionDetails.xhtml#L78)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

I suggest to add a common tab styling class to all such tab bars, e.g. 'tabControl', in the marketplace UI (search for list-group-item,  in order to have unique customization with mp.css. 
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 9 of 14 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/870)* status: all files reviewed, 4 unresolved discussions (waiting on @farmakiG)

**Review by farmakiG — APPROVED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/870)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
