### PR TITLE
APP credentials synchronization

### PR DESCRIPTION
**Pull request by kowalczyka**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/281)

### CODE REVIEW

**Review by GoebelL — APPROVED** [review]
> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/281)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @GoebelL and @kowalczyka)

___
*[oscm-build/ivy-build.xml, line 26 at r1](https://reviewable.io/reviews/servicecatalog/oscm/281#-Lc5SMgoARc3f90LRFLc:-Lc5SMgoARc3f90LRFLd:b-c6wwhu) ([raw file](https://github.com/servicecatalog/oscm/blob/ad664c55e609bb52a4baca6dbf1c13ca03f1f273/oscm-build/ivy-build.xml#L26)):*
> ```XML
>       <param name="from"
>         value="https://jitpack.io/com/github/servicecatalog/oscm-interfaces/oscm-app-extsvc/task~synchronize_credentials-SNAPSHOT/oscm-app-extsvc-task~synchronize_credentials-SNAPSHOT.jar" />
>       <param name="to" value="${root.dir}/libraries/servicecatalog/oscm-app-extsvc/javalib/oscm-app-extsvc.jar" />
> ```

Ok, for now. This needs to be adapted once interface is merged. But I suggest to merge the interface PR first (incl. compatibility change). 
___
*[oscm-identitymgmt/.classpath, line 41 at r1](https://reviewable.io/reviews/servicecatalog/oscm/281#-Lc5Wgxe9mBNv85wtR5m:-Lc5Wgxe9mBNv85wtR5n:b-2qh6k9) ([raw file](https://github.com/servicecatalog/oscm/blob/ad664c55e609bb52a4baca6dbf1c13ca03f1f273/oscm-identitymgmt/.classpath#L41)):*
> ```XML
> 	<classpathentry kind="lib" path="/libraries/apache-tomee/javalib/javaee-api-7.0-1.jar"/>
> 	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
> 	<classpathentry kind="src" path="/oscm-app"/>
> ```

The idententity service should not have dependency to app.

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/281)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @GoebelL)

___
*[oscm-build/ivy-build.xml, line 26 at r1](https://reviewable.io/reviews/servicecatalog/oscm/281#-Lc5SMgoARc3f90LRFLc:-Lc5YPDw-o9PQ-e75Vkv:bgu5cg) ([raw file](https://github.com/servicecatalog/oscm/blob/ad664c55e609bb52a4baca6dbf1c13ca03f1f273/oscm-build/ivy-build.xml#L26)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Ok, for now. This needs to be adapted once interface is merged. But I suggest to merge the interface PR first (incl. compatibility change). 
</blockquote></details>

Yes, it was just left for CI to be executed without compilation problem. It will be adapted when the interface is merged.
___
*[oscm-identitymgmt/.classpath, line 41 at r1](https://reviewable.io/reviews/servicecatalog/oscm/281#-Lc5Wgxe9mBNv85wtR5m:-Lc5ZpUn1rWOsBuAkj6f:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/ad664c55e609bb52a4baca6dbf1c13ca03f1f273/oscm-identitymgmt/.classpath#L41)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

The idententity service should not have dependency to app.
</blockquote></details>

Done.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/281)* status: all files reviewed, 2 unresolved discussions (waiting on @GoebelL)

**Review by GoebelL — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/281#-:-Lc86Sk855KleaHN-BJX:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @GoebelL)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/281)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
