### PR TITLE
remove bootstrap sources

### PR DESCRIPTION
**Pull request by cworf91**
**Changes in this Pull Request:**
- remove bootstrap sources from package

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1027)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 1 of 111 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1027)* status: 1 of 111 files reviewed, 1 unresolved discussion (waiting on @cworf91 and @GoebelL)

___
*[oscm-build/ivy-build.xml, line 414 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1027#-MCljHhGDP7Iu-gj-KUU:-MCljHhHD9ZZM-iQFa4c:b-k8ip0a) ([raw file](https://github.com/servicecatalog/oscm/blob/bab0a827554617280af917829ba4eb642486fae5/oscm-build/ivy-build.xml#L414)):*
> ```XML
>       <fileset dir="${root.dir}/libraries/bootstrap/javalib/work/META-INF/resources/webjars/bootstrap/4.3.1"/>
>     </copy>
>     <copy todir="${root.dir}/oscm-portal/WebContent/bootstrap">
> ```

The script should first create the target folder. Otherwise the copy will fail.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 110 of 111 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1027)* status: all files reviewed, 1 unresolved discussion (waiting on @cworf91)

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1027)* status: 110 of 111 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-build/ivy-build.xml, line 414 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1027#-MCljHhGDP7Iu-gj-KUU:-MCloWKK5UN5BZRejTXV:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/bab0a827554617280af917829ba4eb642486fae5/oscm-build/ivy-build.xml#L414)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

The script should first create the target folder. Otherwise the copy will fail. 
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1027)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
