### PR TITLE
Bug#912 mobile view forms not fully reponsive

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Implement similar columns width in formSecret like in formInput
- change c:when to c:if

**Mandatory checks:**
- [ ] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- c:11

**Screenshot (if applicable):**
Bug_2
Bug_1
Bug_3

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/925)

### CODE REVIEW

**Review by farmakiG — DISMISSED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/925)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL and @KabacinskiPiotr)

___
*[oscm-portal/WebContent/marketplace/playground/loginUserAndPasswordInclude.xhtml, line 40 at r1](https://reviewable.io/reviews/servicecatalog/oscm/925#-M9SIWO6AfzEjE8HLdZH:-M9SIWO6AfzEjE8HLdZI:bg0mysq) ([raw file](https://github.com/servicecatalog/oscm/blob/a5a685106aa80f3136ffc21ace46e7bd6c179421/oscm-portal/WebContent/marketplace/playground/loginUserAndPasswordInclude.xhtml#L40)):*
> ```HTML
>     </div>
>     <div>
>       <mp:buttonBootstrap styleClass="btn-sm btn-secondary" id="loginButton" value="#{msg['button.login']}"
> ```

Please do not use float-right class inside styleClass.

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/925)* status: all files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-portal/WebContent/marketplace/playground/loginUserAndPasswordInclude.xhtml, line 40 at r1](https://reviewable.io/reviews/servicecatalog/oscm/925#-M9SIWO6AfzEjE8HLdZH:-M9TDxLH7gsLWBVOvasb:b-zeg4e2) ([raw file](https://github.com/servicecatalog/oscm/blob/a5a685106aa80f3136ffc21ace46e7bd6c179421/oscm-portal/WebContent/marketplace/playground/loginUserAndPasswordInclude.xhtml#L40)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Please do not use float-right class inside styleClass.
</blockquote></details>

@farmakig How? Make mp.css class loginButton and style with float right? Please suggest alternative solutions when rejecting given ones .

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/playground/loginUserAndPasswordInclude.xhtml, line 40 at r1](https://reviewable.io/reviews/servicecatalog/oscm/925#-M9SIWO6AfzEjE8HLdZH:-M9TNs061h07BeIBZxSk:b-g8jpst) ([raw file](https://github.com/servicecatalog/oscm/blob/a5a685106aa80f3136ffc21ace46e7bd6c179421/oscm-portal/WebContent/marketplace/playground/loginUserAndPasswordInclude.xhtml#L40)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

@farmakig How? Make mp.css class loginButton and style with float right? Please suggest alternative solutions when rejecting given ones . 
</blockquote></details>

You can add the following style for the <div> where mp:buttonBootstrap is located : <div class="text-right">.

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/925)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[oscm-portal/WebContent/marketplace/playground/loginUserAndPasswordInclude.xhtml, line 40 at r1](https://reviewable.io/reviews/servicecatalog/oscm/925#-M9SIWO6AfzEjE8HLdZH:-M9d0faa9hyrw4XoVWuz:b3kre) ([raw file](https://github.com/servicecatalog/oscm/blob/a5a685106aa80f3136ffc21ace46e7bd6c179421/oscm-portal/WebContent/marketplace/playground/loginUserAndPasswordInclude.xhtml#L40)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

You can add the following style for the <div> where mp:buttonBootstrap is located : <div class="text-right">. 
</blockquote></details>

?

**Review by GoebelL — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/925)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
