### PR TITLE
Feature/connectivity tests

### LINKED ISSUE #223: Ping - Enhance APP UI to provide for connectivity tests

### PR DESCRIPTION
**Pull request by adamczykba**
Changes in this PR:
- Implemented canPing functionality flow
- Implenented ping functionality flow

Closes #223

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/230)

### CODE REVIEW

**Comment by Crystalzord** [comment]
After clicking "Check connection" button I am unable to refresh the page using f5 (due to re-submit request). If I try to do so, it ends up in error and to get back to https://10.140.18.99:8881/oscm-app/default.jsf page I have to re-enter this in the browser's address tab.

**Review by Crystalzord — CHANGES_REQUESTED** [review]
After clicking "Check connection" button I am unable to refresh the page using f5 (due to re-submit request). If I try to do so, it ends up in error and to get back to https://10.140.18.99:8881/oscm-app/default.jsf page I have to re-enter this in the browser's address tab.

EDIT:
Ok looks like this is a bug not caused by this issue.
Reported this here: https://github.com/servicecatalog/oscm/issues/233

**Review by Crystalzord — APPROVED** [review]

**Comment by Crystalzord** [comment]
Looks good to me, however I see that logging does not work properly. Please create an issue about fixing logging of events in the controllers.

**Comment by adamczykba** [comment]
@Crystalzord 
#235

**Pull request merged**
