### PR TITLE
Task#786 responsive mySubscription page

### LINKED ISSUE #786: [Subscription UI] Make marketplace/subscriptions/index.jsf page responsive
Summary
Make subscriptions main page responsive using bootstrap.

Details
Make subscriptions main page responsive using bootstrap, page should look as close as possible to current page.

Acceptance criteria

- [ ] Page is responsive
- [ ] Page is linked with other playground pages
- [ ] UI test

Additional context
N/A

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- create new playgroundIndex page
- add new method for get subscriptions

**UI test for this page will be write in this task [#807 ](https://app.zenhub.com/workspaces/oscm-59f31a4996b6c551bc556610/issues/servicecatalog/oscm/807)**

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [x] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [ ] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM Build And Push job](<enter URL to a job here>)
- [OSCM Pull And Start job](<enter URL to a job here>)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/820)

### CODE REVIEW

**Review by farmakiG — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/820)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @KabacinskiPiotr)

___
*[oscm-portal/WebContent/marketplace/subscriptions/playgroundIndex.xhtml, line 144 at r2](https://reviewable.io/reviews/servicecatalog/oscm/820#-M5znbYB-TECptqSaHDu:-M5znbYC4_okuC4LoQuY:btn8317) ([raw file](https://github.com/servicecatalog/oscm/blob/474d2aefd92559277e47eec6e34ac291fdad296e/oscm-portal/WebContent/marketplace/subscriptions/playgroundIndex.xhtml#L144)):*
<details><summary><i alt="summary">Quoted 144 lines of code…</i></summary>

> ```
> 
>       from
>       Task#786_Responive_subscription 
>       to
>       master       master     No branch found List is empty. Task#786 responsive mySubscription page
> Changes in this Pull Request:
> 
> create new playgroundIndex page
> add new method for get subscriptions
> 
> UI test for this page will be write in this task #807 
> Mandatory checks:
> 
>  latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
>  changes were tested manually
>  unit tests were properly implemented
>  communication about interdependent changes has been sent to the team (if applicable)
>  respective Jenkins jobs were referenced in additional context section of this PR
> 
> OSCM Build References:
> 
> OSCM Build And Push job
> OSCM Pull And Start job
> New commits in r1 (60878f9) at 2020-04-27 11:59:13Z:
> aca9439: Create bootstrap MySubscription page
> 
> 549d5ff: Fix css styles
> 
> 60878f9: fixup! Fix css styles
> 
> Codecov Report
> 
> Merging #820 into master will increase coverage by 0.00%. The diff coverage is 77.77%.
> 
> 
> @@            Coverage Diff            @@
> ##             master     #820   +/-   ##
> =========================================
>   Coverage     55.31%   55.31%           
> - Complexity    14349    14351    +2     
> =========================================
>   Files          1370     1370           
>   Lines         80324    80333    +9     
>   Branches       8582     8584    +2     
> =========================================
> + Hits          44430    44437    +7     
> - Misses        33225    33226    +1     
> - Partials       2669     2670    +1     
> | Impacted Files | Coverage Δ | Complexity Δ | | |---|---|---|---| | ...usesubscriptions/MySubscriptionsLazyDataModel.java | 75.57% <77.77%> (+0.16%) | 34.00 <2.00> (+2.00) | |New commits in r2 (474d2ae) at 2020-04-27 12:54:35Z:
> fffd772: Implement Lorenz review
> 
> e9928f9: fixup! Implement Lorenz review
> 
> 474d2ae: Align text to left
> 
> oscm-portal/javasrc/org/oscm/ui/dialog/mp/usesubscriptions/MySubscriptionsLazyDataModel.java!function(){"use strict";function e(){"init:reviewable";window.REVIEWABLE_PROD=true;"endinit"}var t=document.getElementById("libs-script");if(t?t.addEventListener("load",e):document.addEventListener("DOMContentLoaded",e),"/"!==location.pathname&&"/pricing"!==location.pathname){var n=document.getElementsByTagName("script");n[n.length-1].parentNode.style.display="none"}}();Serious about code reviews?Try a sample code review!You've found the right code review toolThor­oughTracks where par­tic­i­pants stand on each dis­cus­sion, en­sur­ing it won't dis­ap­pear un­til re­solved. Fully cus­tomiz­able logic de­ter­mines when a re­view is com­plete.Ef­fi­cientClearly shows net deltas since last time you looked, even if com­mits got re­based or amended. Batches com­ments and cor­rectly threads email re­sponses.Fo­cusedWorks only with GitHub and GitHub En­ter­prise, mak­ing for a seam­less in­te­gra­tion. Min­i­mal ad­min busy­work, no ex­tra fluff — just awe­some code re­views.What are others saying?“GitHub, the cur­rent de facto stan­dard for [code re­views], is let­ting us down.” —Justin Abrahms“It seems that the tools for code re­view in GitHub are not great, to put it lightly. Not great at all.” —Jaime BueltaBTW Reviewable is really awesome.After using it for a few reviews now, I hate going back to GitHub.Nicolas ArtmanFrontend Engineering Lead, UdacityI've gotta say—Reviewable is the best damn code-review tool out there.Super slick, silky-smooth integration into GitHub. Love it.Danny KoppingSenior PHP Developer, ZandoJust did my first code review on Reviewable. Very well done!Thanks for bringing this to the developers of this world!Holger RappSenior Software Engineer, GoogleReviewable is working really well for us so far. We’re migrating from a self-hosted Gerrit installation and Reviewable gives us most if not all of the benefits while integrating much better with the GitHub workflow developers are used to.Jay StotzCo-founder & CTO at Springboard RetailReviewable is freaking awesome, BTW. I'm a Xoogler myself, and I feel right at home.Austin McDonaldSoftware Engineer, SeedNot convinced yet? Here's some more featuresIn­stantly diff any two re­vi­sions of a file, in uni­fied or side-by-side style. Hide mi­nor changes: white­space, merge, and re­base deltas.Cus­tomize mar­gin, fonts, col­ors, key­board short­cuts, etc. Jump from a com­ment straight to the right spot in your fa­vorite ed­i­tor.Line com­ments map across file re­vi­sions and stay in place un­til re­solved, not just un­til changes are pushed.Mod­ern, clean UI with a touch of whimsy. Full con­tex­tual help and fast sup­port if you have ques­tions.Keep track of who re­viewed which re­vi­sion of each file to make sure no changes are missed. Com­bine com­mits or re­view each one.SSO with GitHub ac­count — no sep­a­rate ac­counts to man­age. All your code stays on GitHub, never touch­ing our servers.Shut up and take my money!Open SourceAll public reposAll personal reposUnlimited reviewsFREE foreverStart reviewingOrganizationAll private reposUnlimited reviewsFree 30 day trial$39 / month for10 contributors 10 contributors25 contributors50 contributorsStart reviewingEnterpriseFor GitHub EnterpriseOn-prem (mostly)Free trial$17 / seat / monthFind out moreNone of these fit you? We'll work something out. Questions? Check out the user guide.                                                       #HW_badge_cont {
>   visibility: hidden;
>   pointer-events: none;
>   display: block;
>   height: 32px;
>   width: 32px;
>   cursor: pointer;
>   position: relative;
> }
> 
> #HW_badge_cont.HW_visible {
>   visibility: visible;
>   pointer-events: auto;
> }
> 
> #HW_badge {
>   display: block;
>   border-radius: 20px;
>   background: #CD4B5B;
>   height: 16px;
>   width: 16px;
>   color: #fff;
>   text-align: center;
>   line-height: 16px;
>   font-size: 11px;
>   cursor: pointer;
>   position: absolute;
>   top: 8px;
>   left: 8px;
>   opacity: 0;
>   transform: scale(0);
>   transition: all 0.3s;
> }
> 
> #HW_badge.HW_softHidden {
>   background: #d4d4d4;
>   opacity: 1;
>   transform: scale(0.6);
> }
> 
> #HW_badge.HW_hidden {
>   opacity: 0;
>   transform: scale(0);
> }
> 
> #HW_badge.HW_visible {
>   opacity: 1;
>   transform: scale(1.0);
> }
> 
> #HW_frame_cont {
>   pointer-events: none;
>   border-radius: 4px;
>   box-shadow: 0 0 1px rgba(99, 114, 130, 0.32), 0 8px 16px rgba(27, 39, 51, 0.08);
>   background: #fff;
>   border: none;
>   position: absolute;
>   top: -900em;
>   z-index: 2147483647;
>   width: 340px;
>   height: 0;
>   opacity: 0;
>   will-change: height, margin-top, opacity;
>   margin-top: -10px;
>   transition: margin-top 0.15s ease-out, opacity 0.1s ease-out, height 0.3s ease-out;
> }
> 
> #HW_frame_cont.HW_visible {
>   opacity: 1;
>   pointer-events: auto;
>   margin-top: 0px;
> }
> 
> #HW_frame {
>   background: #fff;
>   border: none;
>   width: 100%;
>   height: 100%;
>   overflow: hidden;
>   border-radius: 4px;
>   position: relative;
>   z-index: 2147483647;
>   transition: height 0.3s ease-out;
> }
> 
> #HW_frame_cont.HW_embed {
>   position: static;
>   margin-top: 0;
> }
> ```
</details>

Please do not use inline styles, especially if  they are so many inside of an .xhtml file.

**Comment by Piotr-K8i** [comment]
___
*[oscm-portal/WebContent/marketplace/subscriptions/playgroundIndex.xhtml, line 144 at r2](https://reviewable.io/reviews/servicecatalog/oscm/820#-M5znbYB-TECptqSaHDu:-M6-N6Wk2269nqQfrSSF:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/474d2aefd92559277e47eec6e34ac291fdad296e/oscm-portal/WebContent/marketplace/subscriptions/playgroundIndex.xhtml#L144)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

> ```
> 
>       from
>       Task#786_Responive_subscription 
>       to
>       master       master     No branch found List is empty. Task#786 responsive mySubscription page
> Changes in this Pull Request:
> 
> create new playgroundIndex page
> add new method for get subscriptions
> 
> UI test for this page will be write in this task #807 
> Mandatory checks:
> 
>  latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
>  changes were tested manually
>  unit tests were properly implemented
>  communication about interdependent changes has been sent to the team (if applicable)
>  respective Jenkins jobs were referenced in additional context section of this PR
> 
> OSCM Build References:
> 
> OSCM Build And Push job
> OSCM Pull And Start job
> New commits in r1 (60878f9) at 2020-04-27 11:59:13Z:
> aca9439: Create bootstrap MySubscription page
> 
> 549d5ff: Fix css styles
> 
> 60878f9: fixup! Fix css styles
> 
> Codecov Report
> 
> Merging #820 into master will increase coverage by 0.00%. The diff coverage is 77.77%.
> 
> 
> @@            Coverage Diff            @@
> ##             master     #820   +/-   ##
> =========================================
>   Coverage     55.31%   55.31%           
> - Complexity    14349    14351    +2     
> =========================================
>   Files          1370     1370           
>   Lines         80324    80333    +9     
>   Branches       8582     8584    +2     
> =========================================
> + Hits          44430    44437    +7     
> - Misses        33225    33226    +1     
> - Partials       2669     2670    +1     
> | Impacted Files | Coverage Δ | Complexity Δ | | |---|---|---|---| | ...usesubscriptions/MySubscriptionsLazyDataModel.java | 75.57% <77.77%> (+0.16%) | 34.00 <2.00> (+2.00) | |New commits in r2 (474d2ae) at 2020-04-27 12:54:35Z:
> fffd772: Implement Lorenz review
> 
> e9928f9: fixup! Implement Lorenz review
> 
> 474d2ae: Align text to left
> 
> oscm-portal/javasrc/org/oscm/ui/dialog/mp/usesubscriptions/MySubscriptionsLazyDataModel.java!function(){"use strict";function e(){"init:reviewable";window.REVIEWABLE_PROD=true;"endinit"}var t=document.getElementById("libs-script");if(t?t.addEventListener("load",e):document.addEventListener("DOMContentLoaded",e),"/"!==location.pathname&&"/pricing"!==location.pathname){var n=document.getElementsByTagName("script");n[n.length-1].parentNode.style.display="none"}}();Serious about code reviews?Try a sample code review!You've found the right code review toolThor­oughTracks where par­tic­i­pants stand on each dis­cus­sion, en­sur­ing it won't dis­ap­pear un­til re­solved. Fully cus­tomiz­able logic de­ter­mines when a re­view is com­plete.Ef­fi­cientClearly shows net deltas since last time you looked, even if com­mits got re­based or amended. Batches com­ments and cor­rectly threads email re­sponses.Fo­cusedWorks only with GitHub and GitHub En­ter­prise, mak­ing for a seam­less in­te­gra­tion. Min­i­mal ad­min busy­work, no ex­tra fluff — just awe­some code re­views.What are others saying?“GitHub, the cur­rent de facto stan­dard for [code re­views], is let­ting us down.” —Justin Abrahms“It seems that the tools for code re­view in GitHub are not great, to put it lightly. Not great at all.” —Jaime BueltaBTW Reviewable is really awesome.After using it for a few reviews now, I hate going back to GitHub.Nicolas ArtmanFrontend Engineering Lead, UdacityI've gotta say—Reviewable is the best damn code-review tool out there.Super slick, silky-smooth integration into GitHub. Love it.Danny KoppingSenior PHP Developer, ZandoJust did my first code review on Reviewable. Very well done!Thanks for bringing this to the developers of this world!Holger RappSenior Software Engineer, GoogleReviewable is working really well for us so far. We’re migrating from a self-hosted Gerrit installation and Reviewable gives us most if not all of the benefits while integrating much better with the GitHub workflow developers are used to.Jay StotzCo-founder & CTO at Springboard RetailReviewable is freaking awesome, BTW. I'm a Xoogler myself, and I feel right at home.Austin McDonaldSoftware Engineer, SeedNot convinced yet? Here's some more featuresIn­stantly diff any two re­vi­sions of a file, in uni­fied or side-by-side style. Hide mi­nor changes: white­space, merge, and re­base deltas.Cus­tomize mar­gin, fonts, col­ors, key­board short­cuts, etc. Jump from a com­ment straight to the right spot in your fa­vorite ed­i­tor.Line com­ments map across file re­vi­sions and stay in place un­til re­solved, not just un­til changes are pushed.Mod­ern, clean UI with a touch of whimsy. Full con­tex­tual help and fast sup­port if you have ques­tions.Keep track of who re­viewed which re­vi­sion of each file to make sure no changes are missed. Com­bine com­mits or re­view each one.SSO with GitHub ac­count — no sep­a­rate ac­counts to man­age. All your code stays on GitHub, never touch­ing our servers.Shut up and take my money!Open SourceAll public reposAll personal reposUnlimited reviewsFREE foreverStart reviewingOrganizationAll private reposUnlimited reviewsFree 30 day trial$39 / month for10 contributors 10 contributors25 contributors50 contributorsStart reviewingEnterpriseFor GitHub EnterpriseOn-prem (mostly)Free trial$17 / seat / monthFind out moreNone of these fit you? We'll work something out. Questions? Check out the user guide.                                                       #HW_badge_cont {
>   visibility: hidden;
>   pointer-events: none;
>   display: block;
>   height: 32px;
>   width: 32px;
>   cursor: pointer;
>   position: relative;
> }
> 
> #HW_badge_cont.HW_visible {
>   visibility: visible;
>   pointer-events: auto;
> }
> 
> #HW_badge {
>   display: block;
>   border-radius: 20px;
>   background: #CD4B5B;
>   height: 16px;
>   width: 16px;
>   color: #fff;
>   text-align: center;
>   line-height: 16px;
>   font-size: 11px;
>   cursor: pointer;
>   position: absolute;
>   top: 8px;
>   left: 8px;
>   opacity: 0;
>   transform: scale(0);
>   transition: all 0.3s;
> }
> 
> #HW_badge.HW_softHidden {
>   background: #d4d4d4;
>   opacity: 1;
>   transform: scale(0.6);
> }
> 
> #HW_badge.HW_hidden {
>   opacity: 0;
>   transform: scale(0);
> }
> 
> #HW_badge.HW_visible {
>   opacity: 1;
>   transform: scale(1.0);
> }
> 
> #HW_frame_cont {
>   pointer-events: none;
>   border-radius: 4px;
>   box-shadow: 0 0 1px rgba(99, 114, 130, 0.32), 0 8px 16px rgba(27, 39, 51, 0.08);
>   background: #fff;
>   border: none;
>   position: absolute;
>   top: -900em;
>   z-index: 2147483647;
>   width: 340px;
>   height: 0;
>   opacity: 0;
>   will-change: height, margin-top, opacity;
>   margin-top: -10px;
>   transition: margin-top 0.15s ease-out, opacity 0.1s ease-out, height 0.3s ease-out;
> }
> 
> #HW_frame_cont.HW_visible {
>   opacity: 1;
>   pointer-events: auto;
>   margin-top: 0px;
> }
> 
> #HW_frame {
>   background: #fff;
>   border: none;
>   width: 100%;
>   height: 100%;
>   overflow: hidden;
>   border-radius: 4px;
>   position: relative;
>   z-index: 2147483647;
>   transition: height 0.3s ease-out;
> }
> 
> #HW_frame_cont.HW_embed {
>   position: static;
>   margin-top: 0;
> }
> ```
Please do not use inline styles, especially if  they are so many inside of an .xhtml file.
</blockquote></details>

Done.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/css/dataTableDarkStyle.css, line 5 at r3](https://reviewable.io/reviews/servicecatalog/oscm/820#-M6-cZkKCUUNZ8EcDPor:-M6-cZkKCUUNZ8EcDPos:b-knhme4) ([raw file](https://github.com/servicecatalog/oscm/blob/23dd0ee58f66f91aa95baaf9426a52fd371583ba/oscm-portal/WebContent/css/dataTableDarkStyle.css#L5)):*
> ```CSS
> }
> 
> table.dataTable thead tr {
> ```

We don 't use rgba values but hexadecimal values.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/css/dataTableDarkStyle.css, line 2 at r3](https://reviewable.io/reviews/servicecatalog/oscm/820#-M6-cgTM06-LP5rD815f:-M6-cgTN-NZJ02U5ybik:bxal6ow) ([raw file](https://github.com/servicecatalog/oscm/blob/23dd0ee58f66f91aa95baaf9426a52fd371583ba/oscm-portal/WebContent/css/dataTableDarkStyle.css#L2)):*
> ```CSS
> ul {
>   width: 100% !important;
> ```

Use more specific selector for ul.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/css/dataTableDarkStyle.css, line 26 at r3](https://reviewable.io/reviews/servicecatalog/oscm/820#-M6-clNV1Y7CRhIVDwyi:-M6-clNV1Y7CRhIVDwyj:b1vc6ww) ([raw file](https://github.com/servicecatalog/oscm/blob/23dd0ee58f66f91aa95baaf9426a52fd371583ba/oscm-portal/WebContent/css/dataTableDarkStyle.css#L26)):*
> ```CSS
> #location li a {
>   color: aliceblue;
> }
> ```

You can also use a specific selector for the table instead of table.datatable use #tableID

**Review by farmakiG — COMMENTED** [review]
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/820)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @farmakiG and @KabacinskiPiotr)

**Review by farmakiG — APPROVED** [review]
> Reviewed 3 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/820)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
