### PR TITLE
Bug#912_Mobile_view_forms_not_fully_reponsive

### LINKED ISSUE #912: Bugs in forms in mobile view
**Version Info**
18.1

**Describe the bug**
Not fully responsive mobile view, missing tooltips at mobile view

**How to Reproduce**
1. Go to playground/index.jsf
2. Click on 'Show Details'
3. Click on 'Get it now'
4. Switch to mobile view
5. See error

1. Go to playground/account/subscriptionDetails.jsf
2. Switch to mobile view
3. See error

**Observed behavior**
Missing tooltips, not fully responsive form 

**Expected behavior**
The mobile view should have all the features of the deskop page, for the form in the mobile view the label should be displayed first and the field to be filled below

**Screenshots**

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Change layout at subscriptions/creation/add.jsf and /account/subscriptionDetails.jsf

**Mandatory checks:**
- [ ] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- ci11

**Screenshot (if applicable):**
Bug_4
Bug_3
Bug_2
Bug_1

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/919)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/919)* status: all files reviewed, 1 unresolved discussion (waiting on @farmakiG and @KabacinskiPiotr)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/hintBootstrap.xhtml, line 10 at r1](https://reviewable.io/reviews/servicecatalog/oscm/919#-M93c0nw0CieVHfcmkhr:-M93c0nyEOEtQZfAsCLD:b-6zglz6) ([raw file](https://github.com/servicecatalog/oscm/blob/dadfa8d601d427b7d393b2b9c3949b15db7f2f69/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/hintBootstrap.xhtml#L10)):*
> ```HTML
>  <c:set var="hintMsg" value="#{(not empty hintText)?hintText:(msg[hintMsgId])}"/>
> 
>  <a4j:outputPanel class="input-group-append">
> ```

 the a4j:outputPlanel doesn't provide for the attribute class, but only styleClass. Anyway, use plain HTML div for static contents rather that a4j.

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/919)* status: all files reviewed, 2 unresolved discussions (waiting on @farmakiG and @KabacinskiPiotr)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/formInput.xhtml, line 104 at r1](https://reviewable.io/reviews/servicecatalog/oscm/919#-M93dVjD3sw37WKn7iJo:-M93dVjD3sw37WKn7iJp:b-d9185i) ([raw file](https://github.com/servicecatalog/oscm/blob/dadfa8d601d427b7d393b2b9c3949b15db7f2f69/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/formInput.xhtml#L104)):*
> ```HTML
>     </c:when>
>     <c:otherwise>
>      <a4j:outputPanel class="row pl-3">
> ```

class is not defined for a4j:outputPanel. Remove namespace a4j and replace with div.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/formInput.xhtml, line 1 at r2](https://reviewable.io/reviews/servicecatalog/oscm/919#-M9IMGu6BVhVXiryXXkZ:-M9IMGu7ClLH2ZAE731m:b9qz15l) ([raw file](https://github.com/servicecatalog/oscm/blob/f0ace79a3be6cca7ef6473a50e003e05a7c9c43a/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/formInput.xhtml#L1)):*
> ```HTML
> 
> ```

Update Copyright.

**Review by farmakiG — COMMENTED** [review]
> Reviewed 12 of 15 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/919)* status: all files reviewed, 3 unresolved discussions (waiting on @KabacinskiPiotr)

**Review by GoebelL — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/919)* status: all files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)

**Review by farmakiG — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/919)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/919)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
