### PR TITLE
Remove nullPointerException in the canPing method

### PR DESCRIPTION
**Pull request by Crystalzord**
Removed nullpointer exception that was thrown during Openstack canPing method with no settings provided.

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/249)

### CODE REVIEW

**Review by adamczykba — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/249)* status: all files reviewed, 1 unresolved discussion (waiting on @Crystalzord)

___
*[oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/OpenStackController.java, line 644 at r1](https://reviewable.io/reviews/servicecatalog/oscm/249#-LaGEE0nA1twhrqTdmMi:-LaGEE0o9FeqgASCe6lS:b-e7pjs2) ([raw file](https://github.com/servicecatalog/oscm/blob/c8a6b9f1a9fcb90e2fadfb6ba447ccb0c1280ffb/oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/OpenStackController.java#L644)):*
> ```Java
>             throw exception;
>         }
>         if ((settings.get("KEYSTONE_API_URL") != null) ||
> ```

If settings object will for some reason resolve to null, nullpointer will appear once again.
Just add another check at the beggining. Ex: if(settings != null && ([remaining_conditions])) {}

**Review by Crystalzord — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/249)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @adamczykba)

___
*[oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/OpenStackController.java, line 644 at r1](https://reviewable.io/reviews/servicecatalog/oscm/249#-LaGEE0nA1twhrqTdmMi:-LaGNy_pBjkVqwHllxpi:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/c8a6b9f1a9fcb90e2fadfb6ba447ccb0c1280ffb/oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/OpenStackController.java#L644)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

If settings object will for some reason resolve to null, nullpointer will appear once again.
Just add another check at the beggining. Ex: if(settings != null && ([remaining_conditions])) {}
</blockquote></details>

Done.

**Review by adamczykba — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/249)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @adamczykba and @Crystalzord)

___
*[oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/OpenStackController.java, line 668 at r2](https://reviewable.io/reviews/servicecatalog/oscm/249#-LaGcL2LAnFaw0-irNcG:-LaGcL2M-WNGuY0zxFZq:btkgoxe) ([raw file](https://github.com/servicecatalog/oscm/blob/645594b42ebba2143e6c1991a835d1054715f13a/oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/OpenStackController.java#L668)):*
> ```Java
>                     new PasswordAuthentication(username, password));
>             if (settings == null) {
>                 throw new ConfigurationException(getLocalizedErrorMessage(
> ```

Just as we discussed earlier: Wouln't it be cleaner if exception is thrown inside gerOpenStackSettings() method?

**Review by adamczykba — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/249)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
