### PR TITLE
Marketplace login in SSO mode

### PR DESCRIPTION
**Pull request by kowalczyka**
**Changes in this Pull Request:**
Adapted filter to handle th public marketplace pages

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [x] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM Build And Push job](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Docker_Build_and_push/290/)
- [OSCM Pull And Start job](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Docker_pull_and_start/582/)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/533)

### CODE REVIEW

**Comment by kowalczyka** [comment]
Closes https://github.com/servicecatalog/oscm/issues/524

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/533)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

___
*[oscm-portal/WebContent/WEB-INF/web.xml, line 167 at r1](https://reviewable.io/reviews/servicecatalog/oscm/533#-Lt4HJG3BhYADwzb4L92:-Lt4HJG4EQjFTyV6qBPZ:btpou4c) ([raw file](https://github.com/servicecatalog/oscm/blob/b5caee5044141fff8384eed329d54dc5c6fd7159/oscm-portal/WebContent/WEB-INF/web.xml#L167)):*
> ```XML
>       <param-value>(^/marketplace/terms/.*|^/marketplace/[^/\?#]*([\?#].*)?)</param-value>
>     </init-param>
>   </filter>
> ```

some format flaw here.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/533)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/533)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

**Review by GoebelL — APPROVED** [review]

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/533)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
