### PR TITLE
Branch set primary color

### LINKED ISSUE #1219: Set Theme Colors at runtime
**Summary**
Set the basic theme colors at the Profile page. These are: 

1) the primary color, 
2) the theme-background-color 
3) the theme-background-color for input fields, 
4) the theme-foreground-color, 
5) the navigation background color and 
6) the navigation foreground color.

**Details**
List of :root variables that must be affected:

- --oscm-primary: primary color
- --oscm-main: background color
-  --oscm-main-input-color: background color for input fields.
- --oscm-main-font-color: foreground color for text
- --oscm-navbar-color: background color for navigation
- --oscm-navbar-links-color: foreground color for navigation

**Acceptance criteria**
- [ ] All above colors are updated in the UI upon click of "Save" in the Profile page
- [ ] UI Tests
- [ ] UI Screenshots
- [ ] UI Customizability is preserved

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- added hexToHsl javascript function
- set colors to sessionScope userdisplaySettings
- set colors as css variables at :root element from sessionScope
- extend profile page with extra colors.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell
-est6

**Screenshot (if applicable):**
image

Set light color scheme with custom colors:
Screenshot_2021-03-24 Marketplace(2)

Set dark color scheme with custom colors:
Screenshot_2021-03-24 Marketplace(3)

German text:
Screenshot_2021-03-24 Marktplatz(1)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1218)

### CODE REVIEW

**Review by Piotr-K8i — DISMISSED** [review]
> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1218)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @farmakiG)

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1218)* status: all files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml, line 176 at r3](https://reviewable.io/reviews/servicecatalog/oscm/1218#-MWYZPiS00wCopv5qVui:-MWYZPiS00wCopv5qVuj:b-tkwzar) ([raw file](https://github.com/servicecatalog/oscm/blob/d1c6a0e0b16eff3c1150c4c40a07dd16e78fdba1/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml#L176)):*
> ```HTML
>     }
>     
>     function hexToHSL(hex) {    
> ```

The logic here looks fine, but we need to avoid long inline code. We better maintain these functions in AdmUtils.js. Please move it there.

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1218)* status: all files reviewed, 2 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties, line 1704 at r3](https://reviewable.io/reviews/servicecatalog/oscm/1218#-MWYbWQE9D3Fsb-VlHE5:-MWYbWQE9D3Fsb-VlHE6:b-bvy00r) ([raw file](https://github.com/servicecatalog/oscm/blob/d1c6a0e0b16eff3c1150c4c40a07dd16e78fdba1/oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties#L1704)):*
> ```INI
> user.displaySettings.fontColor=Schriftfarbe
> user.displaySettings.navbarColor=Farbbandfarbe
> user.displaySettings.navbarLinkColor=Farbband Link Farbe
> ```

Please find better naming and translation, esp. for navbar colors.

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1218)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @farmakiG, @GoebelL, and @KabacinskiPiotr)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml, line 176 at r3](https://reviewable.io/reviews/servicecatalog/oscm/1218#-MWYZPiS00wCopv5qVui:-MWZ6hA5-nZ0ltJr5MQS:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/d1c6a0e0b16eff3c1150c4c40a07dd16e78fdba1/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml#L176)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

The logic here looks fine, but we need to avoid long inline code. We better maintain these functions in AdmUtils.js. Please move it there.  
</blockquote></details>

Done.

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1218)* status: 8 of 13 files reviewed, 2 unresolved discussions (waiting on @GoebelL and @KabacinskiPiotr)

___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties, line 1704 at r3](https://reviewable.io/reviews/servicecatalog/oscm/1218#-MWYbWQE9D3Fsb-VlHE5:-MWZFkJeDtdY8mgioMse:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/d1c6a0e0b16eff3c1150c4c40a07dd16e78fdba1/oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties#L1704)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Please find better naming and translation, esp. for navbar colors. 
</blockquote></details>

Done.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1218)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1218)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @farmakiG)

**Pull request merged**
