### PR TITLE
Task/sso retrive user data

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/410)

### CODE REVIEW

**Comment by GoebelL** [comment]
Guys, let's move ahead with this feature and get this merged when review is done.

**Review by Crystalzord — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/410)* status: all files reviewed, 15 unresolved discussions (waiting on @cworf91)

___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java, line 2952 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC4QyA-4soQbQ6ydrg:-LnC4QyA-4soQbQ6ydrh:b-jge3kh) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java#L2952)):*
> ```Java
>             logger.logWarn(Log4jLogger.SYSTEM_LOG, e,
>                     LogMessageIdentifier.ERROR_CREATE_ORGANIZATION);
>             throw new SaaSSystemException("can not connect to the oidc service");
> ```

Please change to Can not connec to the OIDC service (capital leters)
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java, line 2956 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC4nXgAUZUzEjYx4BN:-LnC4nXgAUZUzEjYx4BO:bzgdv7) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java#L2956)):*
> ```Java
>         return userDetails;
>     }
>     
> ```

Unnecessary white spaces
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/model/UserinfoModel.java, line 5 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC4qIE6ipzOoSm9yR0:-LnC4qIE6ipzOoSm9yR1:bzgdv7) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/model/UserinfoModel.java#L5)):*
> ```Java
> 
> public class UserinfoModel {
>     
> ```

Unnecessary white spaces
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/model/UserinfoModel.java, line 16 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC4qgI4bMIMfEoRvAr:-LnC4qgI4bMIMfEoRvAs:bzgdv7) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/model/UserinfoModel.java#L16)):*
> ```Java
>     private String gender;
>     private String postalCode;
>     
> ```

Unnecessary white spaces
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/model/UserinfoModel.java, line 81 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC4rmlCJBNGX-pbB9Q:-LnC4rmlCJBNGX-pbB9R:bojmxnn) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/model/UserinfoModel.java#L81)):*
> ```Java
> 
> ```

Too many blank lines
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java, line 35 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC5iCZ0Hac3rb3SrGB:-LnC5iCZ0Hac3rb3SrGC:bse0nnu) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java#L35)):*
> ```Java
>                 logger.logInfo(Log4jLogger.SYSTEM_LOG,
>                         LogMessageIdentifier.ERROR_ORGANIZATION_REGISTRATION_FAILED,
>                         "response code from identity service was "
> ```

Start log message with capital letter please
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java, line 38 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC5lcH69X564_Si65A:-LnC5lcH69X564_Si65B:bse0nnu) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java#L38)):*
> ```Java
>                                 + conn.getResponseCode());
>                 throw new RuntimeException(
>                         "response code from identity service was "
> ```

Start log message with capital letter please
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java, line 48 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC6KzQEUTT_fc9KD9h:-LnC6KzQEUTT_fc9KD9i:b-gx0i7p) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java#L48)):*
> ```Java
>             throw e;
>         }
>         VOUserDetails details = createUserDetails(response, userId);
> ```

Creating VOUserDetails object could be skipped here and the function createUserDetails could be passed to the return statement directly
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java, line 56 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC664d6GMjShXPiz0G:-LnC664d6GMjShXPiz0H:b-4qoxj7) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java#L56)):*
> ```Java
>         UserinfoModel userInfoModel = gson.fromJson(response,
>                 UserinfoModel.class);
>         VOUserDetails details = mapUserInfoToUserDetails(userInfoModel, userId);
> ```

Creating VOUserDetails object could be skipped here and the function mapUserInfoToUserDetails could be passed to the return statement directly
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java, line 100 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC6VckDQBmxW4geN5c:-LnC6VckDQBmxW4geN5d:b-ffdj3y) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java#L100)):*
> ```Java
> 
>     protected HttpURLConnection createConnection(URL url, String tokenId)
>             throws IOException, ProtocolException {
> ```

IOException is more general exception and ProtocolException could be removed here
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java, line 106 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC6mlSD1nvq3miKyuq:-LnC6mlSD1nvq3miKyur:b-dbfkmn) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java#L106)):*
> ```Java
>         conn.setRequestProperty("Content-Type", "application/json");
>         conn.connect();
>         logger.logDebug("Connection to identity service successfull");
> ```

Typo. should be "successful"
___
*[oscm-identitymgmt-unittests/javasrc/org/oscm/identityservice/rest/UserinfoTest.java, line 182 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC6xmo3KOyGmfv61vv:-LnC6xmpEiKN4aMp6v-T:bzgdv7) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt-unittests/javasrc/org/oscm/identityservice/rest/UserinfoTest.java#L182)):*
> ```Java
>          //when
>          VOUserDetails result = userinfo.createUserDetails(input, "");
>          
> ```

Unnecessary white spaces
___
*[oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java, line 172 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC705l6mBjNS7PuFLd:-LnC705l6mBjNS7PuFLe:bzgdv7) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java#L172)):*
> ```Java
>                     newAdministrator.getUserId(), getSelectedTenantId(), getIdToken());
>         }
>         
> ```

Unnecessary white spaces
___
*[oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java, line 200 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC71NRCJDLxNNGDiBJ:-LnC71NSCWuDL0a0BuJ8:bzgdv7) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java#L200)):*
> ```Java
>         return ""; 
>     }
>     
> ```

Unnecessary white spaces
___
*[oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java, line 205 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC7Ckc5Vl_47yCOrSL:-LnC7Ckc5Vl_47yCOrSM:bu4do7z) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java#L205)):*
> ```Java
>         HttpSession session = (HttpSession) facesContext.getExternalContext()
>                 .getSession(true);
>         String idToken = (String) session
> ```

Creating an idToken String  could be skipped here and the function could be passed to the return statement directly

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/410)* status: all files reviewed, 15 unresolved discussions (waiting on @Crystalzord and @cworf91)

___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java, line 2952 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC4QyA-4soQbQ6ydrg:-LnC8KYyEvKyS2AuhpmR:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java#L2952)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Please change to Can not connec to the OIDC service (capital leters)
</blockquote></details>

Done.
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java, line 2956 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC4nXgAUZUzEjYx4BN:-LnCB_gG4YVKA2Tj1BMg:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java#L2956)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Unnecessary white spaces
</blockquote></details>

Done.
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/model/UserinfoModel.java, line 5 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC4qIE6ipzOoSm9yR0:-LnCBiQD3w5h3VRjSCJ5:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/model/UserinfoModel.java#L5)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Unnecessary white spaces
</blockquote></details>

Done.
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/model/UserinfoModel.java, line 16 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC4qgI4bMIMfEoRvAr:-LnCBikkB4Qzc6greJo7:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/model/UserinfoModel.java#L16)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Unnecessary white spaces
</blockquote></details>

Done.
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java, line 35 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC5iCZ0Hac3rb3SrGB:-LnCCFDkBVTQvQN5tX-y:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java#L35)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Start log message with capital letter please
</blockquote></details>

Done.
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java, line 38 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC5lcH69X564_Si65A:-LnCCFVU0X_GebApF2Sr:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java#L38)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Start log message with capital letter please
</blockquote></details>

Done.
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java, line 48 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC6KzQEUTT_fc9KD9h:-LnCCOpE4G0R4_wkivpT:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java#L48)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Creating VOUserDetails object could be skipped here and the function createUserDetails could be passed to the return statement directly
</blockquote></details>

Done.
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java, line 56 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC664d6GMjShXPiz0G:-LnCCVP8E9j0Xf1XO0TN:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java#L56)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Creating VOUserDetails object could be skipped here and the function mapUserInfoToUserDetails could be passed to the return statement directly
</blockquote></details>

Done.
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java, line 100 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC6VckDQBmxW4geN5c:-LnCCcmuEY-Fwudq1f2q:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java#L100)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

IOException is more general exception and ProtocolException could be removed here
</blockquote></details>

Done.
___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java, line 106 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC6mlSD1nvq3miKyuq:-LnCCgWD3oe8NURanmsK:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/Userinfo.java#L106)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Typo. should be "successful"
</blockquote></details>

Done.
___
*[oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java, line 172 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC705l6mBjNS7PuFLd:-LnCD5h774at_1nW_Mdl:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java#L172)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Unnecessary white spaces
</blockquote></details>

Done.
___
*[oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java, line 200 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC71NRCJDLxNNGDiBJ:-LnCDEUb8u1hsjsg7Zv8:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java#L200)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Unnecessary white spaces
</blockquote></details>

Done.
___
*[oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java, line 205 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC7Ckc5Vl_47yCOrSL:-LnCDJ3i-waJU28oOuff:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java#L205)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Creating an idToken String  could be skipped here and the function could be passed to the return statement directly
</blockquote></details>

Done.

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/410)* status: 2 of 6 files reviewed, 15 unresolved discussions (waiting on @Crystalzord)

___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/model/UserinfoModel.java, line 81 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC4rmlCJBNGX-pbB9Q:-LnCE5qrAWeqNkbxs_An:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt/javasrc/org/oscm/identityservice/model/UserinfoModel.java#L81)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Too many blank lines
</blockquote></details>

Done.
___
*[oscm-identitymgmt-unittests/javasrc/org/oscm/identityservice/rest/UserinfoTest.java, line 182 at r4](https://reviewable.io/reviews/servicecatalog/oscm/410#-LnC6xmo3KOyGmfv61vv:-LnCEZ3C60SXPjhAeuwk:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/70d272c6f325ea510f5a216adeade1467a150a15/oscm-identitymgmt-unittests/javasrc/org/oscm/identityservice/rest/UserinfoTest.java#L182)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Unnecessary white spaces
</blockquote></details>

Done.

**Review by Crystalzord — APPROVED** [review]
> Reviewed 4 of 4 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/410)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
