### PR TITLE
Landingpage playground

### PR DESCRIPTION
**Pull request by farmakiG**
Closes Issue #423.

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/471)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 22 of 29 files at r1, 9 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/471)* status: 29 of 35 files reviewed, 2 unresolved discussions (waiting on @farmakiG and @GoebelL)

___
*[oscm-portal/WebContent/marketplace/bootstrapLandingpage.xhtml, line 16 at r4](https://reviewable.io/reviews/servicecatalog/oscm/471#-LqLlo6r0P3ikDja76F3:-LqLlo6r0P3ikDja76F4:bujhscs) ([raw file](https://github.com/servicecatalog/oscm/blob/f07581aaa754bd8ed980bab709163aa54c861eaf/oscm-portal/WebContent/marketplace/bootstrapLandingpage.xhtml#L16)):*
> ```HTML
>   <script src="#{facesContext.externalContext.requestContextPath}/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
> 
>   <a4j:outputPanel id="listServicesForPublicLandingpage">
> ```

use div?
___
*[oscm-portal/WebContent/marketplace/templates/mainBootstrap.xhtml, line 46 at r4](https://reviewable.io/reviews/servicecatalog/oscm/471#-LqLkntwALGb1ayU6dxi:-LqLkntx7NhT3_izEox3:b2kxtu3) ([raw file](https://github.com/servicecatalog/oscm/blob/f07581aaa754bd8ed980bab709163aa54c861eaf/oscm-portal/WebContent/marketplace/templates/mainBootstrap.xhtml#L46)):*
> ```HTML
>   </div>
>  
>   <a4j:outputPanel id="contentPanelDiv" layout="block"> 
> ```

To be removed.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/471)* status: 30 of 35 files reviewed, 2 unresolved discussions (waiting on @farmakiG and @GoebelL)

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/471)* status: 31 of 35 files reviewed, 2 unresolved discussions (waiting on @farmakiG and @GoebelL)

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/471)* status: 26 of 36 files reviewed, 2 unresolved discussions (waiting on @GoebelL)

___
*[oscm-portal/WebContent/marketplace/bootstrapLandingpage.xhtml, line 16 at r4](https://reviewable.io/reviews/servicecatalog/oscm/471#-LqLlo6r0P3ikDja76F3:-Lqa9_SMAjTCNRHAuFPV:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/f07581aaa754bd8ed980bab709163aa54c861eaf/oscm-portal/WebContent/marketplace/bootstrapLandingpage.xhtml#L16)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

use div?
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/templates/mainBootstrap.xhtml, line 46 at r4](https://reviewable.io/reviews/servicecatalog/oscm/471#-LqLkntwALGb1ayU6dxi:-Lqa9Pwt5roL9a0IsiEE:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/f07581aaa754bd8ed980bab709163aa54c861eaf/oscm-portal/WebContent/marketplace/templates/mainBootstrap.xhtml#L46)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

To be removed.
</blockquote></details>

Done.

**Comment by farmakiG** [comment]
Tested manually with:
Travis CI build:  # 2508

**Review by GoebelL — APPROVED** [review]
> Reviewed 4 of 15 files at r4, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/471)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
