### PR TITLE
Change to OIDC authentication mode (WIP)

### PR DESCRIPTION
**Pull request by GoebelL**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/390)

### CODE REVIEW

**Review by cworf91 — APPROVED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/390)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-portal/javasrc/org/oscm/ui/beans/operator/ConfigurationSettingsBean.java, line 268 at r1](https://reviewable.io/reviews/servicecatalog/oscm/390#-LlWNRhE8fZZtWvDcoSU:-LlWNRhE8fZZtWvDcoSV:bnfb40i) ([raw file](https://github.com/servicecatalog/oscm/blob/d6add176ff270f16b63602be4d3b358b7b428ac1/oscm-portal/javasrc/org/oscm/ui/beans/operator/ConfigurationSettingsBean.java#L268)):*
> ```Java
>                 return true;
>             }
>         }
> ```

Kann das null werden?
Ansonsten ("OIDC").equals(settings.getValue()) bzw (AUTH_MODE).equals(..)

**Review by cworf91 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/390#-:-LlWOZMe8_vcArgzvC_2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/390)* status: all files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[oscm-portal/javasrc/org/oscm/ui/beans/operator/ConfigurationSettingsBean.java, line 268 at r1](https://reviewable.io/reviews/servicecatalog/oscm/390#-LlWNRhE8fZZtWvDcoSU:-LlWTgBV2UgGKq0pYXXR:b9q9kej) ([raw file](https://github.com/servicecatalog/oscm/blob/d6add176ff270f16b63602be4d3b358b7b428ac1/oscm-portal/javasrc/org/oscm/ui/beans/operator/ConfigurationSettingsBean.java#L268)):*
<details><summary><i>Previously, cworf91 wrote…</i></summary><blockquote>

Kann das null werden?
Ansonsten ("OIDC").equals(settings.getValue()) bzw (AUTH_MODE).equals(..)
</blockquote></details>

No. Unchanged.

**Review by cworf91 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/390)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
