### PR TITLE
Create v sphere link

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/243)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/243)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @cworf91 and @GoebelL)

___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VM.java, line 89 at r1](https://reviewable.io/reviews/servicecatalog/oscm/243#-L_teWki4UAHRNxeoZoy:-L_teWki4UAHRNxeoZoz:bscjq9k) ([raw file](https://github.com/servicecatalog/oscm/blob/445cb57743816d847b085ab424cecf9f5fcdbb35/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VM.java#L89)):*
> ```Java
>        URL.append("https://");
>        URL.append(ph.getTargetVCenterServer());
>        URL.append(":9443");
> ```

This needs to be configured with technical service parmaters rather than hardcoded. 
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VM.java, line 119 at r1](https://reviewable.io/reviews/servicecatalog/oscm/243#-L_tgJik5RdcvkdBALmK:-L_tgJik5RdcvkdBALmL:b-j06l7z) ([raw file](https://github.com/servicecatalog/oscm/blob/445cb57743816d847b085ab424cecf9f5fcdbb35/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VM.java#L119)):*
> ```Java
>             ArrayList<String> snaps, String indent) {
>         
>         vmInstance.getValue().toString();
> ```

Remove non-use code.
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VMwareProcessor.java, line 73 at r1](https://reviewable.io/reviews/servicecatalog/oscm/243#-L_tfpjWB8vfDvrmoLeU:-L_tfpjWB8vfDvrmoLeV:b-4mmwcc) ([raw file](https://github.com/servicecatalog/oscm/blob/445cb57743816d847b085ab424cecf9f5fcdbb35/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VMwareProcessor.java#L73)):*
> ```Java
>     }
> 
>     public String getvmAccessURL(VMPropertyHandler ph) {
> ```

Minor coding convensions: Method names in camel case and ...
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VMwareProcessor.java, line 84 at r1](https://reviewable.io/reviews/servicecatalog/oscm/243#-L_tg763ATRTqo5DKvjS:-L_tg763ATRTqo5DKvjT:bk9wwwq) ([raw file](https://github.com/servicecatalog/oscm/blob/445cb57743816d847b085ab424cecf9f5fcdbb35/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VMwareProcessor.java#L84)):*
> ```Java
>             instanceName = ph.getInstanceName();
>             VM vm = new VM(vmClient, instanceName);
>             URL = vm.createVMURL(ph);
> ```

... variable names starting lower case, please. 
___
*[oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMwareInstanceAccess.java, line 77 at r1](https://reviewable.io/reviews/servicecatalog/oscm/243#-L_tf6Pv0Yd2XctbbV9o:-L_tf6Pw9WSgvHIr-8l_:bs6bhem) ([raw file](https://github.com/servicecatalog/oscm/blob/445cb57743816d847b085ab424cecf9f5fcdbb35/oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMwareInstanceAccess.java#L77)):*
> ```Java
>                 .getServiceInstanceDetails(Controller.ID, instanceId,
>                         subscriptionId, organizationId);
>         VMPropertyHandler ph = new VMPropertyHandler(settings);
> ```

Should be more generically handeled using access info pattern substitution. Customers may not want any URLs here.

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/243)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @GoebelL)

___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VM.java, line 89 at r1](https://reviewable.io/reviews/servicecatalog/oscm/243#-L_teWki4UAHRNxeoZoy:-LaKs43T5kWf0Wfn8vIp:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/445cb57743816d847b085ab424cecf9f5fcdbb35/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VM.java#L89)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

This needs to be configured with technical service parmaters rather than hardcoded. 
</blockquote></details>

Done.
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VM.java, line 119 at r1](https://reviewable.io/reviews/servicecatalog/oscm/243#-L_tgJik5RdcvkdBALmK:-LaKs6Ed8JIQ5gxR6qVf:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/445cb57743816d847b085ab424cecf9f5fcdbb35/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VM.java#L119)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Remove non-use code.
</blockquote></details>

Done.
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VMwareProcessor.java, line 84 at r1](https://reviewable.io/reviews/servicecatalog/oscm/243#-L_tg763ATRTqo5DKvjS:-LaKsFM_2w4VhsZRVC6p:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/445cb57743816d847b085ab424cecf9f5fcdbb35/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VMwareProcessor.java#L84)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

... variable names starting lower case, please. 
</blockquote></details>

Done.
___
*[oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMwareInstanceAccess.java, line 77 at r1](https://reviewable.io/reviews/servicecatalog/oscm/243#-L_tf6Pv0Yd2XctbbV9o:-LaKsK4S3AgHSVb6hIg_:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/445cb57743816d847b085ab424cecf9f5fcdbb35/oscm-app-vmware-service/javasrc/org/oscm/app/vmware/service/VMwareInstanceAccess.java#L77)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Should be more generically handeled using access info pattern substitution. Customers may not want any URLs here.
</blockquote></details>

Done.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/243)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @GoebelL)

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/243)* status: all files reviewed, 4 unresolved discussions (waiting on @GoebelL)

**Review by GoebelL — APPROVED** [review]

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/243)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
