### PR TITLE
Refactor azure deletion logic

### LINKED ISSUE #153: Azure: wrong mail are resceived after deleting a Instance
[Build]
docker 17.7 2018/10/05

[Steps to reproduce]
create a azure instance  -> instance is running 
goto subscription and terminate it

[Expected result]
the instance is terminated, all resoures are deleted and a meaningful mail will be received

[Observed result]
the instance is terminated, all resources are deleted, but the following mail is resceived:

Dear user,

The current operation on subscription 'AzureARM_Example1#1a9be903-ae00-433c-86fe-1274813d5198' for customer 'PLATFORM_OPERATOR' has been suspended (Instance: 'azure-192328a5-1c56-460f-abd9-beb5526d0f5b').

Reported problem: Azure returned the following error: Delete Resources failed: 

To continue automatic processing, please click the following URL:
https://estst1.intern.est.fujitsu.com:8881/oscm-app/notify?sid=azure-192328a5-1c56-460f-abd9-beb5526d0f5b&controllerid=ess.azureARM&_resume=yes

If the problem cannot be solved and the processing cannot be continued, please terminate the subscription and create a new one.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #153

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/161)

### CODE REVIEW

**Review by GoebelL — COMMENTED** [review]
Well done. Read- and maintain-able now. Just a unit test would be good here.

**Comment by ghost** [comment]
I have updated related test to work with the refactored code. As introduced methods are actually private then we can only test `deleteInstance` method directly.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/161)* status: 1 of 2 files reviewed, all discussions resolved

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/161)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
