### PR TITLE
Sso register organization

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/364)

### CODE REVIEW

**Review by kowalczyka — DISMISSED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/364)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @cworf91 and @kowalczyka)

___
*[oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java, line 1282 at r1](https://reviewable.io/reviews/servicecatalog/oscm/364#-Lk3c8y26sjcqNLbSjfa:-Lk3c8y3-x9LN-DgERuN:b-ywn0ua) ([raw file](https://github.com/servicecatalog/oscm/blob/fe8e4bc9b7b0609efa345ff97e55871bb6283b0d/oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java#L1282)):*
> ```Java
>         return menuBean.getApplicationBean().isSamlSpAuthMode();
>     }
>     
> ```

There is already method for getting IdentityService - check the BaseBean getIdService()
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/userName.xhtml, line 6 at r1](https://reviewable.io/reviews/servicecatalog/oscm/364#-Lk3cgFk3AiG5610oHQH:-Lk3cgFk3AiG5610oHQI:b-61bln8) ([raw file](https://github.com/servicecatalog/oscm/blob/fe8e4bc9b7b0609efa345ff97e55871bb6283b0d/oscm-portal/WebContent/WEB-INF/facelets/tags/userName.xhtml#L6)):*
> ```HTML
> <ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
>   xmlns:adm="http://www.fujitsu.com/global/services/software/interstage">
> ```

What is the purpose of this conditions?

**Review by kowalczyka — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/364)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @cworf91 and @kowalczyka)

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/364)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @cworf91 and @kowalczyka)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/userName.xhtml, line 6 at r1](https://reviewable.io/reviews/servicecatalog/oscm/364#-Lk3cgFk3AiG5610oHQH:-Lk3iWEh7qFVzp0sjMwt:bh90sgh) ([raw file](https://github.com/servicecatalog/oscm/blob/fe8e4bc9b7b0609efa345ff97e55871bb6283b0d/oscm-portal/WebContent/WEB-INF/facelets/tags/userName.xhtml#L6)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

What is the purpose of this conditions?
</blockquote></details>

It is necessary that this field is not displayed in SSO mode. Therefore, it should not render if first and last names are not rendered in the createOrganization.xhtml. So, if SSO authentication is active, the first and last name field is not rendered in createOrganization.xhtml. This causes the condition "rendered" to be false. Therefore this field isn´t shown at the GUI. The "empty rendered" condition is: if other .xhtml fiels who use this label, can continue to use this label without side effects. If no "rendered" attribute is specified in the other .xhtml file, this condition is true and the old logic alone is decisive.

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/364)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @kowalczyka)

___
*[oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java, line 1282 at r1](https://reviewable.io/reviews/servicecatalog/oscm/364#-Lk3c8y26sjcqNLbSjfa:-Lk3mZzz1p4iI93tj3B9:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/fe8e4bc9b7b0609efa345ff97e55871bb6283b0d/oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java#L1282)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

There is already method for getting IdentityService - check the BaseBean getIdService()
</blockquote></details>

Done.

**Review by kowalczyka — APPROVED** [review]
LGTM

> Reviewed 1 of 5 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/364#-:-LkNxc_DDmWOI57GZZ9B:bb6ywmx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @GoebelL)

**Pull request merged**
