### PR TITLE
Connect ippools with vds 

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/301)

### CODE REVIEW

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/issues/279

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 2 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/301)* status: 2 of 24 files reviewed, 3 unresolved discussions (waiting on @cworf91 and @GoebelL)

___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/PortgroupIpSettings.java, line 54 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCN3UcA-w_VADxym9C:-LeCN3UcA-w_VADxym9D:btf09u9) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/PortgroupIpSettings.java#L54)):*
> ```Java
>   private DistributedVirtualSwitch getDistributedVirtualSwitch(
>       String dvsName, List<DistributedVirtualSwitch> distributedVirtualSwitches) {
>     DistributedVirtualSwitch DistributedVirtualSwitch = null;
> ```

any attributes and methods in lower case please (Java naming convensions)
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/PortgroupIpSettings.java, line 97 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCKT1YDE9sXRmSkdKD:-LeCKT1Z1ygrqqRlzcNv:b8g15jw) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/PortgroupIpSettings.java#L97)):*
> ```Java
>         } catch (Exception e) {
>           throw new APPlatformException(
>               "No IP address found Check whether you have specified an IP pool for the port group in the Technical Service. If so, there may not be IPs left in this pool",
> ```


1. Add i18 for all user error messages

2. Add port group information in this error message. 

E.g.: No IP address was found for the port group ''{0}'' . Check in the technical service definition. In case an IP pool has been specified for the given port group, there may be no free IP addresses available from this pool.
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/PortgroupIpSettings.java, line 113 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCNtHS9lQJWwAd4uRo:-LeCNtHS9lQJWwAd4uRp:b6okhmk) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/PortgroupIpSettings.java#L113)):*
> ```Java
>           } catch (Exception e) {
>             throw new IllegalArgumentException(
>                 "The ip adress " + ip + " can not be returned. The Ip does not exist");
> ```

1. i18a (dito)
2. Simplly say "The IP address ''{0}'' does not exist."

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 18 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/301)* status: 20 of 24 files reviewed, 8 unresolved discussions (waiting on @cworf91 and @GoebelL)

___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/model/DistributedVirtualSwitch.java, line 20 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCQ0_L1eumlqjpH15a:-LeCQ0_L1eumlqjpH15b:b-tbhc7f) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/model/DistributedVirtualSwitch.java#L20)):*
> ```Java
>   public String uuid;
>   public int tkey;
>   public int cluster_tkey;
> ```

change to "clusterKey" according java naming convension
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/model/DistributedVirtualSwitch.java, line 58 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCQYykAM4wh81u3dq6:-LeCQYykAM4wh81u3dq7:b-3dnn7o) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/model/DistributedVirtualSwitch.java#L58)):*
> ```Java
>   }
> 
>   public void setCluster_tkey(int cluster_tkey) {
> ```

setClusterKey(...) 

lower camel case without underscores, according Java naming convensions
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/importer/DistributedVirtualSwitchImporter.java, line 56 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCSpbV2KxhwL-U4ZNh:-LeCSpbV2KxhwL-U4ZNi:b-vzrnz2) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/importer/DistributedVirtualSwitchImporter.java#L56)):*
> ```Java
>     }
>   }
> ```

Move to beginning
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/importer/PortgroupImporter.java, line 66 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCRj1p6i5IsHe3om-9:-LeCRj1p6i5IsHe3om-A:b-f3lmaw) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/importer/PortgroupImporter.java#L66)):*
> ```Java
>   }
> 
>   PortgroupImporter(DataAccessService das) {
> ```

Move constructor to beginning of the class
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/importer/PortgroupIPPoolImporter.java, line 68 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCRxQPC8T9A_ucX_9d:-LeCRxQPC8T9A_ucX_9e:bb7eybp) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/importer/PortgroupIPPoolImporter.java#L68)):*
> ```Java
>     }
>   }
> ```

dito

**Review by GoebelL — COMMENTED** [review]
> Reviewed 2 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/301)* status: 22 of 24 files reviewed, 8 unresolved discussions (waiting on @cworf91 and @GoebelL)

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/301)* status: 17 of 28 files reviewed, 8 unresolved discussions (waiting on @GoebelL)

___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/PortgroupIpSettings.java, line 54 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCN3UcA-w_VADxym9C:-LeGUoD70Dz28qOSX6sx:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/PortgroupIpSettings.java#L54)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

any attributes and methods in lower case please (Java naming convensions)
</blockquote></details>

Done.
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/PortgroupIpSettings.java, line 97 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCKT1YDE9sXRmSkdKD:-LeGUoyC7NxayqfvHo6S:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/PortgroupIpSettings.java#L97)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>


1. Add i18 for all user error messages

2. Add port group information in this error message. 

E.g.: No IP address was found for the port group ''{0}'' . Check in the technical service definition. In case an IP pool has been specified for the given port group, there may be no free IP addresses available from this pool.
</blockquote></details>

Done.
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/PortgroupIpSettings.java, line 113 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCNtHS9lQJWwAd4uRo:-LeGUpYd3h1LnOyvUxSB:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/PortgroupIpSettings.java#L113)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

1. i18a (dito)
2. Simplly say "The IP address ''{0}'' does not exist." 
</blockquote></details>

Done.
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/model/DistributedVirtualSwitch.java, line 20 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCQ0_L1eumlqjpH15a:-LeGUqRmAnVdDcGCJoS7:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/model/DistributedVirtualSwitch.java#L20)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

change to "clusterKey" according java naming convension
</blockquote></details>

Done.
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/model/DistributedVirtualSwitch.java, line 58 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCQYykAM4wh81u3dq6:-LeGUqn7294N8XCLZ7Gb:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/model/DistributedVirtualSwitch.java#L58)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

setClusterKey(...) 

lower camel case without underscores, according Java naming convensions
</blockquote></details>

Done.
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/importer/DistributedVirtualSwitchImporter.java, line 56 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCSpbV2KxhwL-U4ZNh:-LeGUrWy4QkfnaLKpmzf:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/importer/DistributedVirtualSwitchImporter.java#L56)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Move to beginning
</blockquote></details>

Done.
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/importer/PortgroupImporter.java, line 66 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCRj1p6i5IsHe3om-9:-LeGUrz9AWMD9E4RE_sN:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/importer/PortgroupImporter.java#L66)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Move constructor to beginning of the class
</blockquote></details>

Done.
___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/importer/PortgroupIPPoolImporter.java, line 68 at r1](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeCRxQPC8T9A_ucX_9d:-LeGUshVCIeOelkJIcC0:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/868931f406bbf9a5dd9c223acec90a7aab6fca20/oscm-app-vmware/javasrc/org/oscm/app/vmware/importer/PortgroupIPPoolImporter.java#L68)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

dito
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/301)* status: 17 of 28 files reviewed, 9 unresolved discussions (waiting on @cworf91 and @GoebelL)

___
*[oscm-app-vmware/javares/org/oscm/app/vmware/i18n/messages_de.properties, line 64 at r2](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeX0uQu7SfJ2Zwjt9-O:-LeX0uQu7SfJ2Zwjt9-P:b-deibe2) ([raw file](https://github.com/servicecatalog/oscm/blob/233284e99e72249a748c1edb13292ad78c61a688/oscm-app-vmware/javares/org/oscm/app/vmware/i18n/messages_de.properties#L64)):*
> ```INI
> error_missing_trigger_email_recipient=Der Serviceparameter TRIGGER_EMAIL_RECIPIENT mu\u00DF gesetzt sein wenn TRIGGER_AFTER_CREATION ausgew\u00E4hlt ist.
> error_modification_overall=Fehler bei der Konfiguration der VM-Instanz.
> error_no_ip_left = Keine IP Adresse gefunden. M�glicherweise sind keine IP Adressen mehr im IPPool verf�gbar. 
> ```

german Umlaut character encoding is not supported here. Unicode references have to be used here.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 24 files at r1, 9 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/301)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @cworf91)

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/301)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-app-vmware/javares/org/oscm/app/vmware/i18n/messages_de.properties, line 64 at r2](https://reviewable.io/reviews/servicecatalog/oscm/301#-LeX0uQu7SfJ2Zwjt9-O:-LelWJREEmXINmNPvKYA:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/233284e99e72249a748c1edb13292ad78c61a688/oscm-app-vmware/javares/org/oscm/app/vmware/i18n/messages_de.properties#L64)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

german Umlaut character encoding is not supported here. Unicode references have to be used here.
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/301)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
