### PR TITLE
Bug#1107 height calculation issue

### LINKED ISSUE #1117: Broken modal dialog layout
**Version Info**
19.0

**Describe the bug**
The width of the dialogues is adjusted neither to the content nor to the screen size

**How to Reproduce**
1. Check any modal dialog

**Observed behavior**
See screenshot

**Expected behavior**
A clear and concise description of what is expected to happen.

**Screenshots**

**Additional context**
Any other context about the problem here.

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Fix bug
- Remove not used styles

**Mandatory checks:**
- [ ] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [ ] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**
image

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1118)

### CODE REVIEW

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/customBootstrap/scss/basic/_image_urls.scss, line 4 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1118#-MLOKvLj1ESgJ2HCvD0-:-MLOKvLlAN5r52Sj20o8:b-xqitvk) ([raw file](https://github.com/servicecatalog/oscm/blob/6bb6167e477c1db4f8924c9c38dd1e1d797482d1/oscm-portal/WebContent/marketplace/customBootstrap/scss/basic/_image_urls.scss#L4)):*
> ```SCSS
> $box_shadow_bottom: url(../img/page/box_shadow_bottom.png);
> $tab_top_bg: url(../img/page/tab-top-bg-1col.png);
> $mp_icon_sprite: url(../img/mp_icon_sprite.png);
> ```

I believe the URL of the images was correct (as it is relative to the context path). Now I do not see the "close" icon $mp_icon_sprite in the modal dialogs. Can you please check?

**Review by farmakiG — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1118)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @KabacinskiPiotr)

**Review by farmakiG — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1118)* status: all files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)

**Comment by Piotr-K8i** [comment]
> _[oscm-portal/WebContent/marketplace/customBootstrap/scss/basic/_image_urls.scss, line 4 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1118#-MLOKvLj1ESgJ2HCvD0-:-MLOKvLlAN5r52Sj20o8:b-xqitvk) ([raw file](https://github.com/servicecatalog/oscm/blob/6bb6167e477c1db4f8924c9c38dd1e1d797482d1/oscm-portal/WebContent/marketplace/customBootstrap/scss/basic/_image_urls.scss#L4)):_
> 
> > ```css-scss
> > $box_shadow_bottom: url(../img/page/box_shadow_bottom.png);
> > $tab_top_bg: url(../img/page/tab-top-bg-1col.png);
> > $mp_icon_sprite: url(../img/mp_icon_sprite.png);
> > ```
> 
> I believe the URL of the images was correct (as it is relative to the context path). Now I do not see the "close" icon $mp_icon_sprite in the modal dialogs. Can you please check?

I checked, in one place it needs to be change. Please note that now $mp_icon_sprite is in two places. Everything works fine for login dialogs, password changes, etc., the problem occurs for dialogs that use the modalDialogBootstrap.xhtml template

**Review by farmakiG — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1118)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
