### PR TITLE
Polish navbar and aside menu styling

### PR DESCRIPTION
**Pull request by GoebelL**
**Changes in this Pull Request:**
- Added account menu root entry
- Sidebar color scheme
- Sorting of navbar header menu in mobile view (search field at the top)

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [X] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- ci10:v18

**Screenshot (if applicable):**
Navigation menu style
image

Header menu with changed order in mobile view: 
image

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/921)

### CODE REVIEW

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/bootstrapNavigationMenu.xhtml, line 22 at r6](https://reviewable.io/reviews/servicecatalog/oscm/921#-M9J0HIXE_TfcoyA6DUP:-M9J0HIY0sNF0IvKmXI7:bn1bpa5) ([raw file](https://github.com/servicecatalog/oscm/blob/5923bf8f44e6df53e76f14d3bdce6a24a8afb1a7/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/bootstrapNavigationMenu.xhtml#L22)):*
> ```HTML
>         
>         <h:outputLink id="link0" value="#"
>           styleClass="#{menuHeaderStyle} #{selected eq first? 'text-primary' : 'text-white'}"
> ```

use text-light instead (please look at the light theme: lightCustom.scss which uses _lightVariables.scss).

**Review by farmakiG — COMMENTED** [review]
> Reviewed 2 of 8 files at r5, 4 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/921)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @GoebelL)

**Review by farmakiG — COMMENTED** [review]
> Reviewed 2 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/921)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/921)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/bootstrapNavigationMenu.xhtml, line 22 at r6](https://reviewable.io/reviews/servicecatalog/oscm/921#-M9J0HIXE_TfcoyA6DUP:-M9J5uH4DCmHVPCpSghx:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/5923bf8f44e6df53e76f14d3bdce6a24a8afb1a7/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/bootstrapNavigationMenu.xhtml#L22)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

use text-light instead (please look at the light theme: lightCustom.scss which uses _lightVariables.scss).
</blockquote></details>

Done.

**Review by farmakiG — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/921)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
