### PR TITLE
Oidc ui tests

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
- Updated test suite for OIDC mode.

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [ ] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM_Integration_Tests_Upgrade](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Integration_Tests_Upgrade/240/)
- [OSCM_Integration_Tests_OIDC](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Integration_Tests_OIDC/129/)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/666)

### CODE REVIEW

**Review by kowalczyka — CHANGES_REQUESTED** [review]
> Reviewed 6 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/666)* status: 6 of 13 files reviewed, 3 unresolved discussions (waiting on @kowalczyka and @mchudy-fujitsu)

___
*[oscm-ui-tests/src/main/java/org/oscm/webtest/WebTester.java, line 56 at r1](https://reviewable.io/reviews/servicecatalog/oscm/666#-M1-gro41fyqZgXowCPA:-M1-gro41fyqZgXowCPB:b-ad137z) ([raw file](https://github.com/servicecatalog/oscm/blob/bbe8af127d78a69a09783fdd234ebfe1b6acc086/oscm-ui-tests/src/main/java/org/oscm/webtest/WebTester.java#L56)):*
> ```
>   public static final String APP_SECURE = "app.secure";
>   public static final String APP_HTTP_URL = "app.http.url";
> ```
These statics are not used anymore, right? Let's remove it then.
___
*[oscm-ui-tests/src/test/java/org/oscm/portal/MarketplaceSubscriptionWT.java, line 22 at r1](https://reviewable.io/reviews/servicecatalog/oscm/666#-M1-f0g79_XJEPmF4H3c:-M1-f0g79_XJEPmF4H3d:b-oxhiy2) ([raw file](https://github.com/servicecatalog/oscm/blob/bbe8af127d78a69a09783fdd234ebfe1b6acc086/oscm-ui-tests/src/test/java/org/oscm/portal/MarketplaceSubscriptionWT.java#L22)):*
> ```Java
> 
> @FixMethodOrder(MethodSorters.NAME_ASCENDING)
> @Ignore
> ```

Why it is ignored? This test should simply go to newly created marketplace page 
___
*[oscm-ui-tests/src/test/java/org/oscm/portal/MarketplaceSubscriptionWT.java, line 44 at r1](https://reviewable.io/reviews/servicecatalog/oscm/666#-M1-fRpS0Pjk3_qLs6zB:-M1-fRpS0Pjk3_qLs6zC:b-89v8or) ([raw file](https://github.com/servicecatalog/oscm/blob/bbe8af127d78a69a09783fdd234ebfe1b6acc086/oscm-ui-tests/src/test/java/org/oscm/portal/MarketplaceSubscriptionWT.java#L44)):*
> ```Java
> 
>   @Test
>   @Ignore
> ```

DITTO

**Comment by kowalczyka** [comment]
Additionally, why all the APP related tests are skipped in OIDC mode? The only difference in this mode is using other user credentials.

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/666)* status: 6 of 14 files reviewed, 4 unresolved discussions (waiting on @mchudy-fujitsu)

___
*[oscm-ui-tests/src/test/java/org/oscm/portal/PortalMarketServiceWT.java, line 146 at r2](https://reviewable.io/reviews/servicecatalog/oscm/666#-M14tyepEzYFodz0hy4M:-M14tyer1GjmxcCg6T-B:b-9sy4e3) ([raw file](https://github.com/servicecatalog/oscm/blob/06c8809c5d15fac3a5afce69d2d6464b642c4fae/oscm-ui-tests/src/test/java/org/oscm/portal/PortalMarketServiceWT.java#L146)):*
> ```Java
>     tester.waitForElement(By.id(PortalHtmlElements.DEACTIVATION_SERVICE_TABLE), 5);
> 
>     String serviceXpath = "//input[@id='serviceDeActivationForm:j_idt489:0:active']";
> ```

This xpath is looks very brittle. The path should be much stable as possible, with less and more constant information to locate this particular input field, in a way the this test case is stable also if once a service is inserted or a minor layout has changed in this table. 
It might be an idea to enhance this JSF view in the oscm-portal and add further dedicated ids on these input fields.

**Review by kowalczyka — DISMISSED** [review]
:lgtm:

> Reviewed 8 of 10 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/666#-:-M1UlrtC1fn26ULBWOXT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mchudy-fujitsu)

**Review by kowalczyka — APPROVED** [review]
> Reviewed 13 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/666)* status: all files reviewed, 1 unresolved discussion (waiting on @mchudy-fujitsu)

**Pull request merged**
