### PR TITLE
 [Subscription UI] Users tab

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
- Created users tab

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [x] .MASTER/job/BES_MASTER_IT/
- [x] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [x] .MASTER/job/OSCM_WS_Tests_OIDC/
- [x] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
N/A

**Screenshot (if applicable):**
FireShot Capture 093 - Marketplace - 10 140 18 99
FireShot Capture 094 - Marketplace - 10 140 18 99
modal1
modal2
modal4
modal5

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/905)

### CODE REVIEW

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/playground/subscriptions/assignUsersInclude.xhtml, line 47 at r1](https://reviewable.io/reviews/servicecatalog/oscm/905#-M8seHM434Hn034n3gCQ:-M8seHM531u8hHy8lhnB:b-750vs1) ([raw file](https://github.com/servicecatalog/oscm/blob/17c07845ca5e0fc10dab62a7204f300959205cc9/oscm-portal/WebContent/marketplace/playground/subscriptions/assignUsersInclude.xhtml#L47)):*
> ```HTML
>         oncomplete="AdmUtils.showProgress(false);
>                 if(!#{facesContext.maximumSeverity.ordinal > 0}){
>                   #{rich:component(dialogId)}.hide();                 
> ```

remove space.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/playground/account/userTableInclude.xhtml, line 2 at r1](https://reviewable.io/reviews/servicecatalog/oscm/905#-M8seWaV07Nf676j6_MV:-M8seWaV07Nf676j6_MW:b-7mo7f4) ([raw file](https://github.com/servicecatalog/oscm/blob/17c07845ca5e0fc10dab62a7204f300959205cc9/oscm-portal/WebContent/marketplace/playground/account/userTableInclude.xhtml#L2)):*
> ```HTML
> 
> <!DOCTYPE html>
> ```

Remove empty line.

**Review by farmakiG — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/905)* status: all files reviewed, 3 unresolved discussions (waiting on @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/playground/account/userTableInclude.xhtml, line 53 at r1](https://reviewable.io/reviews/servicecatalog/oscm/905#-M8sf1rF5v35fbbvpH45:-M8sf1rG0eDK63nxUcQH:bwp5vwu) ([raw file](https://github.com/servicecatalog/oscm/blob/17c07845ca5e0fc10dab62a7204f300959205cc9/oscm-portal/WebContent/marketplace/playground/account/userTableInclude.xhtml#L53)):*
> ```HTML
>         id="#{colUserId}"
>         width="#{userIdWidth}"
>         sortBy="#{user.userId}"
> ```

Please correct the layout of the button on the sortable column (see attached Screenshot).

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/905)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal/WebContent/marketplace/playground/account/userTableInclude.xhtml, line 2 at r1](https://reviewable.io/reviews/servicecatalog/oscm/905#-M8seWaV07Nf676j6_MV:-M8sszDK5DvvZiTjqj_r:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/17c07845ca5e0fc10dab62a7204f300959205cc9/oscm-portal/WebContent/marketplace/playground/account/userTableInclude.xhtml#L2)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Remove empty line.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/playground/account/userTableInclude.xhtml, line 53 at r1](https://reviewable.io/reviews/servicecatalog/oscm/905#-M8sf1rF5v35fbbvpH45:-M8sszpt7rsfA1z_XTWh:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/17c07845ca5e0fc10dab62a7204f300959205cc9/oscm-portal/WebContent/marketplace/playground/account/userTableInclude.xhtml#L53)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Please correct the layout of the button on the sortable column (see attached Screenshot).
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/playground/subscriptions/assignUsersInclude.xhtml, line 47 at r1](https://reviewable.io/reviews/servicecatalog/oscm/905#-M8seHM434Hn034n3gCQ:-M8stF4l0M8hRO-blXjD:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/17c07845ca5e0fc10dab62a7204f300959205cc9/oscm-portal/WebContent/marketplace/playground/subscriptions/assignUsersInclude.xhtml#L47)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

remove space.
</blockquote></details>

Done.

**Review by farmakiG — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/905)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
