### PR TITLE
Task/required organization

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/461)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/461)* status: all files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/AccessGroup.java, line 139 at r2](https://reviewable.io/reviews/servicecatalog/oscm/461#-LpXCZH1AtyN4BDcisJB:-LpXCZH1AtyN4BDcisJC:bqizznt) ([raw file](https://github.com/servicecatalog/oscm/blob/9ee947a126c561c26cefab1bb35bff01f903500d/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/AccessGroup.java#L139)):*
> ```Java
>             group.setName("OSCM_" + groupName);
>         }
>         group.setDescription("Used tenant is: " + description
> ```

Ok, some minor improvements
1. Keep it short. "Tenant: ..., Organization: ..."
2. Rename description -> tenantId

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/461)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/AccessGroup.java, line 139 at r2](https://reviewable.io/reviews/servicecatalog/oscm/461#-LpXCZH1AtyN4BDcisJB:-LpXVT2VDQZWlSSdmHlc:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/9ee947a126c561c26cefab1bb35bff01f903500d/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/AccessGroup.java#L139)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Ok, some minor improvements
1. Keep it short. "Tenant: ..., Organization: ..."
2. Rename description -> tenantId

</blockquote></details>

Done.

**Review by GoebelL — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/461)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/461)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
