### PR TITLE
Task Clean up root color schema

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Remove unnecessary colors

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [ ] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**
- add a screenshot illustrating your change

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1231)

### CODE REVIEW

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/scss/components/_tables.scss, line 7 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1231#-MX6Ojki9Y6pD6H35oN4:-MX6Ojki9Y6pD6H35oN5:b-wpbtk4) ([raw file](https://github.com/servicecatalog/oscm/blob/16250d59cc242a4c23da790bcfdd6233e7eb5a93/oscm-portal/WebContent/marketplace/scss/components/_tables.scss#L7)):*
> ```SCSS
>   margin: 0;
>   text-align: left;
>   background: var(--oscm-table-bg-color);
> ```

Here you have --oscm-table-bg-color and then you have --oscm-table-background-color.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/scss/components/_tables.scss, line 288 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1231#-MX6OsHR0StBCjmwAS9_:-MX6OsHR0StBCjmwAS9a:bdhftiw) ([raw file](https://github.com/servicecatalog/oscm/blob/16250d59cc242a4c23da790bcfdd6233e7eb5a93/oscm-portal/WebContent/marketplace/scss/components/_tables.scss#L288)):*
> ```SCSS
> .rf-dt {
>    border: none !important;
>    background-color: var(--oscm-table-background-color) !important;
> ```

Here you have --oscm-table-background-color.

**Review by farmakiG — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1231)* status: 1 of 14 files reviewed, 2 unresolved discussions (waiting on @KabacinskiPiotr)

**Comment by Piotr-K8i** [comment]
There are different values for background and background-color, were used to override Richfaces values:
--oscm-table-bg-color:              hsla(var(--oscm-main), 0.8);
--oscm-table-background-color:      hsla(var(--oscm-main), 0.1);

**Review by farmakiG — COMMENTED** [review]
> Reviewed 13 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1231)* status: all files reviewed, 2 unresolved discussions (waiting on @KabacinskiPiotr)

**Review by Piotr-K8i — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1231)* status: all files reviewed, 2 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal/WebContent/marketplace/scss/components/_tables.scss, line 7 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1231#-MX6Ojki9Y6pD6H35oN4:-MX6Tyh37IGrlD0o0O1k:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/16250d59cc242a4c23da790bcfdd6233e7eb5a93/oscm-portal/WebContent/marketplace/scss/components/_tables.scss#L7)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Here you have --oscm-table-bg-color and then you have --oscm-table-background-color.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/scss/components/_tables.scss, line 288 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1231#-MX6OsHR0StBCjmwAS9_:-MX6TyzZDp-VWoljRcs7:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/16250d59cc242a4c23da790bcfdd6233e7eb5a93/oscm-portal/WebContent/marketplace/scss/components/_tables.scss#L288)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Here you have --oscm-table-background-color.
</blockquote></details>

Done.

**Review by farmakiG — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1231#-:-MX6UKwe8SDfj5xHGy7W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KabacinskiPiotr)

**Review by farmakiG — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1231#-:-MX6UQ8QD7mR3QdBIizV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KabacinskiPiotr)

**Pull request merged**
