### PR TITLE
Operations page responsive

### LINKED ISSUE #853: [Account UI] Make Operations page responsive.
**Summary**
The operations page is responsive.

**Details**
The first step is to create some operations. The second step is to make the operations panel responsive, the button "Delete" with Bootstrap look-and-feel and the pending operations table responsive (See Processes page).

**Acceptance criteria**
- [ ] Duplicate Operations page -> in playground folder.
- [ ] Manual tests
- [ ] Resulting UI Screenshots
- [ ] UI Test.

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- New responsive operations page

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- c11

**Screenshot (if applicable):**
operation_d
Operation_m

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/888)

### CODE REVIEW

**Review by GoebelL — DISMISSED** [review]
Please reduce the widths of the checkbox and execution date column (see other tables to unify the look) 

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/888#-:-M8npPU526HZ-gRqrULW:bfheqp4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 1707 at r1](https://reviewable.io/reviews/servicecatalog/oscm/888#-M8oFTx31drDuAHVoCSf:-M8oFTx45OYcm1hy6SAX:b-rfgi5z) ([raw file](https://github.com/servicecatalog/oscm/blob/e8c42f51b2d7b2fb105854bca9ea47500b3035d1/oscm-portal/WebContent/marketplace/css/mp.css#L1707)):*
> ```CSS
>   margin-top: 10px;
>   min-height: 500px;
> }
> ```

Please correct this.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/playground/subscriptions/subscriptionUsagePanel.xhtml, line 140 at r1](https://reviewable.io/reviews/servicecatalog/oscm/888#-M8oFvbk5StZyyjWtkvn:-M8oFvbk5StZyyjWtkvo:b3ncd77) ([raw file](https://github.com/servicecatalog/oscm/blob/e8c42f51b2d7b2fb105854bca9ea47500b3035d1/oscm-portal/WebContent/marketplace/playground/subscriptions/subscriptionUsagePanel.xhtml#L140)):*
> ```HTML
>          var f = document.getElementById('subscriptionForm');
>          f.target = subscriptionKey;
>          f.action = accessUrl;
> ```

why did you change this id?

**Review by farmakiG — COMMENTED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/888)* status: all files reviewed, 2 unresolved discussions (waiting on @KabacinskiPiotr)

**Comment by Piotr-K8i** [comment]
> _[oscm-portal/WebContent/marketplace/playground/subscriptions/subscriptionUsagePanel.xhtml, line 140 at r1](https://reviewable.io/reviews/servicecatalog/oscm/888#-M8oFvbk5StZyyjWtkvn:-M8oFvbk5StZyyjWtkvo:b3ncd77) ([raw file](https://github.com/servicecatalog/oscm/blob/e8c42f51b2d7b2fb105854bca9ea47500b3035d1/oscm-portal/WebContent/marketplace/playground/subscriptions/subscriptionUsagePanel.xhtml#L140)):_
> 
> > ```
> >          var f = document.getElementById('subscriptionForm');
> >          f.target = subscriptionKey;
> >          f.action = accessUrl;
> > ```
> 
> why did you change this id?

Because this caused problems when creating more operations

**Review by farmakiG — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/888)* status: all files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)

**Review by farmakiG — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/888#-:-M8ob83_EsxYgbGpAkuW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)

**Review by farmakiG — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/888)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
