### PR TITLE
Task/issue 1157 dark light navbar toggler

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- Create toggle of dark and light theme via two additional variables: enableDarkTheme and enableDarkNavigation.
- Create classes navbar-themed and bg-themed for easy switching of theme via their class.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [X] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- est6

**Screenshot (if applicable):**
Dark Navigation and  theme:

Screenshot_2021-01-26 Marketplace

Screenshot_2021-01-26 Marketplace(1)

Screenshot_2021-01-26 Marketplace(4)

Screenshot_2021-01-26 Marketplace(3)

Screenshot_2021-01-26 Marketplace(6)

Dark navigation light theme:
Screenshot_2021-01-26 Marketplace(7)

Screenshot_2021-01-26 Marketplace(8)

Screenshot_2021-01-26 Marketplace(9)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1175)

### CODE REVIEW

**Review by GoebelL — COMMENTED** [review]
> Reviewed 24 of 46 files at r1, 12 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1175)* status: 35 of 55 files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-portal/WebContent/marketplace/scss/basic/_main.scss, line 45 at r4](https://reviewable.io/reviews/servicecatalog/oscm/1175#-MRyjg2GCE-oawFK8DaU:-MRyjg2H4j-Ezcy84GSz:ba3dfna) ([raw file](https://github.com/servicecatalog/oscm/blob/fa5bc3f55c5765780039a169586a674c5db822cb/oscm-portal/WebContent/marketplace/scss/basic/_main.scss#L45)):*
> ```SCSS
>     text-decoration: underline;
>   }
> /*  &:link {
> ```

Remove?

**Review by GoebelL — COMMENTED** [review]
> Reviewed 15 of 46 files at r1, 5 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1175)* status: all files reviewed, 1 unresolved discussion (waiting on @farmakiG)

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/scss/basic/_main.scss, line 45 at r4](https://reviewable.io/reviews/servicecatalog/oscm/1175#-MRyjg2GCE-oawFK8DaU:-MRymY5m3OVKsW4CSo6K:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/fa5bc3f55c5765780039a169586a674c5db822cb/oscm-portal/WebContent/marketplace/scss/basic/_main.scss#L45)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1175)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
