### PR TITLE
Decrypt VMware adapter password when running tasks

### PR DESCRIPTION
**Pull request by ghost**
@GoebelL https://github.com/servicecatalog/oscm/pull/110 was merged before we finished testing it and @fest-floreks found one more place that needs update.

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/111)

### CODE REVIEW

**Comment by ghost** [comment]
It's building on estessbesci8: http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Docker_build_and_start/26/

After startup I will do e2e test.

**Review by ghost — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/111)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ghost** [comment]
I can confirm, that it works right now:

obraz

obraz

**Comment by ghost** [comment]
You can check it on: https://10.140.18.123:8081/oscm-portal/marketplace

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/111)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
