### PR TITLE
Task/synchronize users

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/487)

### CODE REVIEW

**Review by GoebelL — COMMENTED** [review]
> Reviewed 5 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/487)* status: 5 of 13 files reviewed, all discussions resolved (waiting on @GoebelL)

**Comment by cworf91** [comment]
close https://github.com/servicecatalog/oscm/issues/405

**Comment by cworf91** [comment]
close https://github.com/servicecatalog/oscm/issues/485

**Review by GoebelL — APPROVED** [review]
> Reviewed 7 of 13 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/487)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
