### PR TITLE
Login/Change password modal

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
- Responsive login/change password modal
- Updated UI tests

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [x] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [x] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [x] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/869)

### CODE REVIEW

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/messageAndHintBootstrap.xhtml, line 5 at r1](https://reviewable.io/reviews/servicecatalog/oscm/869#-M7lGtiUCP6W_VhST9kv:-M7lGtiV181TXPQatwav:b-hgbvr4) ([raw file](https://github.com/servicecatalog/oscm/blob/5ad9f3f9f6de39449574eb2e792533864d8cfa13/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/messageAndHintBootstrap.xhtml#L5)):*
> ```HTML
>                       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
> <ui:composition
>   xmlns="http://www.w3.org/1999/xhtml" 
> ```

Update copyright and html 5 declaration.

**Review by farmakiG — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/869)* status: 8 of 13 files reviewed, 2 unresolved discussions (waiting on @farmakiG and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/playground/login.xhtml, line 3 at r1](https://reviewable.io/reviews/servicecatalog/oscm/869#-M7lQieB4fDqWR0hZukO:-M7lQieB4fDqWR0hZukP:b-jkyg6x) ([raw file](https://github.com/servicecatalog/oscm/blob/5ad9f3f9f6de39449574eb2e792533864d8cfa13/oscm-portal/WebContent/marketplace/playground/login.xhtml#L3)):*
> ```HTML
> 
> <!DOCTYPE html>
> <ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html"
> ```

Please use the agreed OSCM formatter.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/passwordBootstrap.xhtml, line 3 at r1](https://reviewable.io/reviews/servicecatalog/oscm/869#-M7lUikk11NqZpg3_ht9:-M7lUikk11NqZpg3_htA:b-6vrad8) ([raw file](https://github.com/servicecatalog/oscm/blob/5ad9f3f9f6de39449574eb2e792533864d8cfa13/oscm-portal/WebContent/WEB-INF/facelets/tags/passwordBootstrap.xhtml#L3)):*
> ```HTML
> 
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 
>   Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
> ```

update HTML5 doctype.

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/869)* status: 4 of 13 files reviewed, 3 unresolved discussions (waiting on @farmakiG and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/playground/login.xhtml, line 3 at r1](https://reviewable.io/reviews/servicecatalog/oscm/869#-M7lQieB4fDqWR0hZukO:-M7lbI8I8DFZ0957OoRQ:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/5ad9f3f9f6de39449574eb2e792533864d8cfa13/oscm-portal/WebContent/marketplace/playground/login.xhtml#L3)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Please use the agreed OSCM formatter.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/passwordBootstrap.xhtml, line 3 at r1](https://reviewable.io/reviews/servicecatalog/oscm/869#-M7lUikk11NqZpg3_ht9:-M7lYHo_5vEYa9U6SFaZ:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/5ad9f3f9f6de39449574eb2e792533864d8cfa13/oscm-portal/WebContent/WEB-INF/facelets/tags/passwordBootstrap.xhtml#L3)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

update HTML5 doctype.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/messageAndHintBootstrap.xhtml, line 5 at r1](https://reviewable.io/reviews/servicecatalog/oscm/869#-M7lGtiUCP6W_VhST9kv:-M7lY4ky0X0PfJKVu7bJ:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/5ad9f3f9f6de39449574eb2e792533864d8cfa13/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/messageAndHintBootstrap.xhtml#L5)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Update copyright and html 5 declaration.
</blockquote></details>

Done.

**Review by GoebelL — DISMISSED** [review]
> Reviewed 1 of 13 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/869)* status: all files reviewed, 3 unresolved discussions (waiting on @farmakiG)

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/messageAndHintBootstrap.xhtml, line 5 at r1](https://reviewable.io/reviews/servicecatalog/oscm/869#-M7lGtiUCP6W_VhST9kv:-M7lqz154qRZkqFwnY-V:bcxnxmv) ([raw file](https://github.com/servicecatalog/oscm/blob/5ad9f3f9f6de39449574eb2e792533864d8cfa13/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/messageAndHintBootstrap.xhtml#L5)):*
<details><summary><i>Previously, mchudy-fujitsu wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Update Copyright 2020.

**Review by farmakiG — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/869#-:-M7lqpAvDHsrKwHUf43i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
