### PR TITLE
Enclose iframe for branded stage inside a div for responsive container.

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- The iframe for the branded stage must be enclosed the <div class="responsive-container"> in order to work.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**
- add a screenshot illustrating your change

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1013)

### CODE REVIEW

**Review by cworf91 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1013)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal/javasrc/org/oscm/ui/beans/SkinBean.java, line 146 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1013#-MBsmZu1C8zk4X0TLZyx:-MBsmZu1C8zk4X0TLZyy:bbdao09) ([raw file](https://github.com/servicecatalog/oscm/blob/40eb3b07ddeacfc0368edd3fb41f79b3fd1c6244/oscm-portal/javasrc/org/oscm/ui/beans/SkinBean.java#L146)):*
> ```Java
>       marketplaceStage = MessageFormat.format(MARKETPLACE_STAGE_DEFAULT, getRequestContextPath());
>     } else {
>       marketplaceStage = appendResponsiveDiv(marketplaceStage);
> ```

Why do you create a new method and don´t do it in this way:
marketplaceStage = MessageFormat.format(MARKETPLACE_STAGE_RESPONSIVE, marketplaceStage);
It´s more uniform.
___
*[oscm-portal/javasrc/org/oscm/ui/beans/SkinBean.java, line 151 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1013#-MBsl4EM8Va8LIWrLH5f:-MBsl4EN17H4tBGFpaae:b-euxnh) ([raw file](https://github.com/servicecatalog/oscm/blob/40eb3b07ddeacfc0368edd3fb41f79b3fd1c6244/oscm-portal/javasrc/org/oscm/ui/beans/SkinBean.java#L151)):*
> ```Java
>   }
> 
>   private String appendResponsiveDiv(String mpStage) {
> ```

This method don´t append a resopnosiv div. 
___
*[oscm-portal/javasrc/org/oscm/ui/beans/SkinBean.java, line 152 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1013#-MBsnAaSDvps1zBCpXGy:-MBsnAaSDvps1zBCpXGz:bnrkxhx) ([raw file](https://github.com/servicecatalog/oscm/blob/40eb3b07ddeacfc0368edd3fb41f79b3fd1c6244/oscm-portal/javasrc/org/oscm/ui/beans/SkinBean.java#L152)):*
> ```Java
> 
>   private String appendResponsiveDiv(String mpStage) {
>     StringBuilder brandedStageBuilder = new StringBuilder();
> ```

Variable names should be fit to the scope of the method. Better name instead of brandedStageBuilder would be just "sb"

**Comment by farmakiG** [comment]
___
*[oscm-portal/javasrc/org/oscm/ui/beans/SkinBean.java, line 152 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1013#-MBsnAaSDvps1zBCpXGy:-MBsqb2S1jbnwz-Oujd_:bw73t89) ([raw file](https://github.com/servicecatalog/oscm/blob/40eb3b07ddeacfc0368edd3fb41f79b3fd1c6244/oscm-portal/javasrc/org/oscm/ui/beans/SkinBean.java#L152)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

Variable names should be fit to the scope of the method. Better name instead of brandedStageBuilder would be just "sb"
</blockquote></details>

Removed the method.

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1013)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @cworf91)

___
*[oscm-portal/javasrc/org/oscm/ui/beans/SkinBean.java, line 146 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1013#-MBsmZu1C8zk4X0TLZyx:-MBsqZ7z5LsASovVpPUw:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/40eb3b07ddeacfc0368edd3fb41f79b3fd1c6244/oscm-portal/javasrc/org/oscm/ui/beans/SkinBean.java#L146)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

Why do you create a new method and don´t do it in this way:
marketplaceStage = MessageFormat.format(MARKETPLACE_STAGE_RESPONSIVE, marketplaceStage);
It´s more uniform.
</blockquote></details>

Done.
___
*[oscm-portal/javasrc/org/oscm/ui/beans/SkinBean.java, line 151 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1013#-MBsl4EM8Va8LIWrLH5f:-MBsqZlfDel0Bq7rLRAl:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/40eb3b07ddeacfc0368edd3fb41f79b3fd1c6244/oscm-portal/javasrc/org/oscm/ui/beans/SkinBean.java#L151)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

This method don´t append a resopnosiv div. 
</blockquote></details>

Done.
___
*[oscm-portal/javasrc/org/oscm/ui/beans/SkinBean.java, line 152 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1013#-MBsnAaSDvps1zBCpXGy:-MBsqdQqBG573-d4ekAu:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/40eb3b07ddeacfc0368edd3fb41f79b3fd1c6244/oscm-portal/javasrc/org/oscm/ui/beans/SkinBean.java#L152)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Removed the method.
</blockquote></details>

Done.

**Review by cworf91 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1013#-:-MBsrRB-02fBLfFjIQta:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
