### PR TITLE
Bug load custom bootstrap

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- Fix bug with loading of custom bootstrap on first access.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [X] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**
- add a screenshot illustrating your change

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1044)

### CODE REVIEW

**Review by cworf91 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1044)* status: all files reviewed, 5 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java, line 71 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1044#-ME2sH8l56G6O7jrdXdC:-ME2sH8p6Xa1HsDMuN6D:beurqhk) ([raw file](https://github.com/servicecatalog/oscm/blob/be86ffda0f8f6c1f021473cc9db2fd2b29296aff/oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java#L71)):*
> ```Java
>   private String mpBrandUrl = null;
> 
>   /** @return the mpBrandUrl */
> ```

remove this javadoc. It´s not adding value
___
*[oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java, line 76 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1044#-ME2sJ7v-P10ZQEgW00g:-ME2sJ7v-P10ZQEgW00h:b-gg90hh) ([raw file](https://github.com/servicecatalog/oscm/blob/be86ffda0f8f6c1f021473cc9db2fd2b29296aff/oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java#L76)):*
> ```Java
>   }
> 
>   /** @param mpBrandUrl the mpBrandUrl to set */
> ```

remove this javadoc
___
*[oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java, line 389 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1044#-ME2t8gq5oLGbGo95Ywt:-ME2t8grEIRcdNWxWuvl:b-ccdksz) ([raw file](https://github.com/servicecatalog/oscm/blob/be86ffda0f8f6c1f021473cc9db2fd2b29296aff/oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java#L389)):*
> ```Java
>           mpBrandUrl = getWhiteLabelBrandingUrl();
>         }
>       } catch (ObjectNotFoundException e) {
> ```

????
Whey is the handling of the exception the same procedure as your code? Is it just a copy paste mistake?
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/SessionBeanTest.java, line 146 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1044#-ME2uVh68jTGObRfK5wd:-ME2uVh68jTGObRfK5we:bbet9ep) ([raw file](https://github.com/servicecatalog/oscm/blob/be86ffda0f8f6c1f021473cc9db2fd2b29296aff/oscm-portal-unittests/javasrc/org/oscm/ui/beans/SessionBeanTest.java#L146)):*
> ```Java
>   public void testGetMarketplaceBrandUrl_NullBrandingUrl() throws Exception {
>     doReturn(null).when(marketplaceServiceMock).getBrandingUrl(MARKETPLACE_ID);
>     sessionBean.getBrandBaseUrl();
> ```

is this call necessary?
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/SessionBeanTest.java, line 157 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1044#-ME2udEA-F0kzUpIgwTt:-ME2udEBC73RhSZ3JiBx:bbet9ep) ([raw file](https://github.com/servicecatalog/oscm/blob/be86ffda0f8f6c1f021473cc9db2fd2b29296aff/oscm-portal-unittests/javasrc/org/oscm/ui/beans/SessionBeanTest.java#L157)):*
> ```Java
>         .getBrandingUrl(MARKETPLACE_ID);
> 
>     sessionBean.getBrandBaseUrl();
> ```

is this call necessary?

**Comment by farmakiG** [comment]
___
*[oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java, line 389 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1044#-ME2t8gq5oLGbGo95Ywt:-ME6mW8vDbBaLtNtNtJG:b-ux4nta) ([raw file](https://github.com/servicecatalog/oscm/blob/be86ffda0f8f6c1f021473cc9db2fd2b29296aff/oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java#L389)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

????
Whey is the handling of the exception the same procedure as your code? Is it just a copy paste mistake?
</blockquote></details>

No, it is not copy paste. It is handling of two cases: 1.) in case of null (the marketplace has no branding, or: 2) of ObjectNotFoundException when feching from db).

**Comment by farmakiG** [comment]
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/SessionBeanTest.java, line 146 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1044#-ME2uVh68jTGObRfK5wd:-ME6mn3w5DgdmbEpWZvq:bl6gzle) ([raw file](https://github.com/servicecatalog/oscm/blob/be86ffda0f8f6c1f021473cc9db2fd2b29296aff/oscm-portal-unittests/javasrc/org/oscm/ui/beans/SessionBeanTest.java#L146)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

is this call necessary?
</blockquote></details>

Yes ,it is necessary to call this method as it sets all necessary values, as Sessionbean does not have a dedicated Controller class.

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1044)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @cworf91)

___
*[oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java, line 71 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1044#-ME2sH8l56G6O7jrdXdC:-ME6mTLVAFzoqai3Elnx:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/be86ffda0f8f6c1f021473cc9db2fd2b29296aff/oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java#L71)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

remove this javadoc. It´s not adding value
</blockquote></details>

Done.
___
*[oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java, line 76 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1044#-ME2sJ7v-P10ZQEgW00g:-ME6mTqv1XgatKRplvc6:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/be86ffda0f8f6c1f021473cc9db2fd2b29296aff/oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java#L76)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

remove this javadoc
</blockquote></details>

Done.
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/SessionBeanTest.java, line 157 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1044#-ME2udEA-F0kzUpIgwTt:-ME6myIz-q2yzh5HwDrj:bql8j0t) ([raw file](https://github.com/servicecatalog/oscm/blob/be86ffda0f8f6c1f021473cc9db2fd2b29296aff/oscm-portal-unittests/javasrc/org/oscm/ui/beans/SessionBeanTest.java#L157)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

is this call necessary?
</blockquote></details>

See as above.

**Review by Piotr-K8i — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1044)* status: all files reviewed, 5 unresolved discussions (waiting on @cworf91)

**Pull request merged**
