### PR TITLE
Bootstrap 5

### LINKED ISSUE #1190: Upgrade Bootstrap version
**Summary**
Bootstrap is upgraded to version 5.0.

**Details**
Bootstrap is upgraded to the newest version 5.0, since it offers more features, for example more useful color functions, support for CSS variables, etc. 
A useful feature is the runtime customization of the UI (for example the primary and the secondary colors) with CSS variables. See [this link](https://getbootstrap.com/docs/5.0/customize/css-variables/#root-variables) for more information on this topic.

Check also the components that have been renamed in version 5.0. See [here](https://getbootstrap.com/docs/5.0/migration/) for renamed components.

**Acceptance criteria**
- [x] Bootstrap is upgraded to version 5.0.
- [ ] Automatic tests are green
- [ ] UI functionality and customization works exactly as before
- [ ] UI Customizability is preserved

**Additional context**
Add any other context or screenshots about the task.

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
Migrated from Bootstrap 4.3.1 to version 5.0 Beta 3. In particular:

- Adapted ivy build scripts
- Replaced text-left (and *-left) to text-start and text-right to text-end.
- Replaced .ml-* and .mr-* to .ms-* and .me-*.
- Replaced .pl-* and .pr-* to .ps-* and .pe-*.
- Replaced .custom-select classes to .form-select classes.
- Replaced data-toggle to data-bs-toggle.
- Replaced javascript for popup.
- Replaced "custom-file" to "form-control" and "custom-file-label" to "form-label" and .scss styles.

Refer to [Migrating to v5](https://getbootstrap.com/docs/5.0/migration/#v500-beta3) link for more information about the changes in Bootstrap v5.0.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- est6

**Screenshot (if applicable):**
- add a screenshot illustrating your change

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1200)

### CODE REVIEW

**Comment by Piotr-K8i** [comment]
After upgrading to Bootstrap 5, the problem is with the popover focusing. After a few appearances, the popover is no longer visible. Probably the bug is connected to tooltip bug

**Comment by Piotr-K8i** [comment]
> After upgrading to Bootstrap 5, the problem is with the popover focusing. After a few appearances, the popover is no longer visible. Probably the bug is connected to tooltip bug

The problem also occurs when you try to log out. It seems that form is not execute in dropdown.

**Comment by GoebelL** [comment]
@KabacinskiPiotr 
This should not go in master as long as bootstrap 5 stable isn't released yet. Please consolidate with @farmakiG and target your PRs to some common bootstrap 5 branch.

**Review by GoebelL — APPROVED** [review]
> Reviewed 66 of 100 files at r1, 1 of 3 files at r2, 3 of 3 files at r3, 94 of 94 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Piotr-K8i)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Piotr-K8i)

**Pull request merged**
