### PR TITLE
Task 898 refactor mp css

### LINKED ISSUE #898: Split Bootstrap-related css from mp.css
**Summary**
All bootstrap-related UI components should be in darkCustom.scss and not in mp.css. Furthermore, the styles in mp.scss should **NOT Override** Bootstrap-related styles, styles of MP and styles of Bootstrap UI components should be loosely coupled.

**Details**
The concept here is that the Bootstrap-related css styles are split from mp.css and located in "darkCustom.css". 
This makes the maintainance of the CSS files easier.
The same version of this file but importing different sass variables is the file "lightCustom.css".
We are using the sass pre-processor so we should add all styles in either darkCustom.scss or lightCustom.scss.
Please note that in order not to lose styles, we have to integrate the compilation of the sass files into css in our build process.

**Acceptance criteria**
Resulting css files: darkCustom.css and mp.css

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- Moved components of mp.css to customBootstrap.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell
-est6

**Screenshot (if applicable):**
- add a screenshot illustrating your change

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1106)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 22 of 25 files at r1, 4 of 4 files at r2, 7 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1106)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @GoebelL)

___
*[oscm-portal/WebContent/marketplace/scss/components/_tables.scss, line 5 at r3](https://reviewable.io/reviews/servicecatalog/oscm/1106#-ML9VcR42gRbdAfcbv6n:-ML9VcR42gRbdAfcbv6o:b4fgw1g) ([raw file](https://github.com/servicecatalog/oscm/blob/3caa7c251c13dc12e50ce5e757fbbf833c198ae2/oscm-portal/WebContent/marketplace/scss/components/_tables.scss#L5)):*
> ```SCSS
> -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
> 10.6 Tables
> -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
> ```

Why is the chapter number added here, while this has been removed in _grid.scss?
Please decide either in both or in none, but anyway consistently.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/scss/components/_tables.scss, line 5 at r3](https://reviewable.io/reviews/servicecatalog/oscm/1106#-ML9VcR42gRbdAfcbv6n:-MLDdHjm-qFh7c7AsQvu:b-olk1pe) ([raw file](https://github.com/servicecatalog/oscm/blob/3caa7c251c13dc12e50ce5e757fbbf833c198ae2/oscm-portal/WebContent/marketplace/scss/components/_tables.scss#L5)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Why is the chapter number added here, while this has been removed in _grid.scss?
Please decide either in both or in none, but anyway consistently.
</blockquote></details>

General Table styling are still in the tables section (while previous styles moved to customTheme). Furthermore, moved _modalDialogs to customTheme.

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1106)* status: 0 of 25 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-portal/WebContent/marketplace/scss/components/_tables.scss, line 5 at r3](https://reviewable.io/reviews/servicecatalog/oscm/1106#-ML9VcR42gRbdAfcbv6n:-MLEobJ01DPgT7p7zBXR:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/3caa7c251c13dc12e50ce5e757fbbf833c198ae2/oscm-portal/WebContent/marketplace/scss/components/_tables.scss#L5)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

General Table styling are still in the tables section (while previous styles moved to customTheme). Furthermore, moved _modalDialogs to customTheme.
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 2 of 20 files at r4, 5 of 5 files at r5, 18 of 18 files at r6.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1106)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
