### PR TITLE
Moved playground pages + UI routing

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
-  Moved playground pages to separate folder.
- Adjusted routing for UI pages.

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [x] Java code changes are unit tested
- [x] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- /view/Docker_OSCM/job/OSCM_Integration_Tests_INTERNAL/168/

**Screenshot (if applicable):**
- add a screenshot illustrating your change

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/849)

### CODE REVIEW

**Review by GoebelL — COMMENTED** [review]
> Reviewed 40 of 49 files at r1, 7 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/849)* status: 44 of 47 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @mchudy-fujitsu)

___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/ServiceListingBeanTest.java, line 76 at r2](https://reviewable.io/reviews/servicecatalog/oscm/849#-M7Hk9bh9lGdS_ugVKhq:-M7Hk9bh9lGdS_ugVKhr:b-lrq62y) ([raw file](https://github.com/servicecatalog/oscm/blob/95cf536db5b45e5b334d303bd17511e2b8e8489d/oscm-portal-unittests/javasrc/org/oscm/ui/beans/ServiceListingBeanTest.java#L76)):*
> ```Java
> //        HttpServletRequest request = mock(HttpServletRequest.class);
> //        doReturn(request).when(serviceListingBean).getRequest();
> ```

Please remove commented code.

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/849)* status: 44 of 47 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @mchudy-fujitsu)

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/849)* status: 44 of 47 files reviewed, 2 unresolved discussions (waiting on @GoebelL and @mchudy-fujitsu)

___
*[oscm-ui-tests/src/main/java/org/oscm/webtest/MarketplacePathSegments.java, line 19 at r3](https://reviewable.io/reviews/servicecatalog/oscm/849#-M7HqrTZAWJXBKXlLqkG:-M7HqrTZAWJXBKXlLqkH:b-hsn5d7) ([raw file](https://github.com/servicecatalog/oscm/blob/0e77ddf12f23e3aa222734b786ebe9d0a1a0595a/oscm-ui-tests/src/main/java/org/oscm/webtest/MarketplacePathSegments.java#L19)):*
> ```Java
>   public static final String MARKETPLACE_ACCOUNT_SUBSCRIPTIONS =
>       "account/playground/subscriptions.jsf";
> ```

? I think  this should be playground/account/...

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/849)* status: 45 of 47 files reviewed, 2 unresolved discussions (waiting on @GoebelL and @mchudy-fujitsu)

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/849)* status: 45 of 47 files reviewed, 2 unresolved discussions (waiting on @GoebelL)

___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/ServiceListingBeanTest.java, line 76 at r2](https://reviewable.io/reviews/servicecatalog/oscm/849#-M7Hk9bh9lGdS_ugVKhq:-M7I6qpI82YYR3k3TVyk:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/95cf536db5b45e5b334d303bd17511e2b8e8489d/oscm-portal-unittests/javasrc/org/oscm/ui/beans/ServiceListingBeanTest.java#L76)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Please remove commented code.
</blockquote></details>

Done.
___
*[oscm-ui-tests/src/main/java/org/oscm/webtest/MarketplacePathSegments.java, line 19 at r3](https://reviewable.io/reviews/servicecatalog/oscm/849#-M7HqrTZAWJXBKXlLqkG:-M7I7UHu2IiTQqpq7UeG:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/0e77ddf12f23e3aa222734b786ebe9d0a1a0595a/oscm-ui-tests/src/main/java/org/oscm/webtest/MarketplacePathSegments.java#L19)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

? I think  this should be playground/account/...
</blockquote></details>

Done.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 49 files at r1, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/849)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by GoebelL — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/849#-:-M7IZ65ECi50eok8tGNT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/849)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
