### PR TITLE
Handle OIDC login for API.

### PR DESCRIPTION
**Pull request by GoebelL**
**Changes in this Pull Request:**
- Change #1
  Verify ID token from user credentials for API login.

**Mandatory checks:**
- [X] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [ ] changes were tested manually
- [x] unit tests were properly implemented
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM Build And Push job](http://estessbesci1:8080/view/Docker_OSCM/job/OSCM_Docker_Build_and_push/244/) (UI login fix)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/505)

### CODE REVIEW

**Review by kowalczyka — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/505)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

___
*[oscm-security/javasrc/org/oscm/security/ADMRealmImpl.java, line 223 at r2](https://reviewable.io/reviews/servicecatalog/oscm/505#-LrJb-P5AEu_1Dq4rHJq:-LrJb-P5AEu_1Dq4rHJr:b-7e7nyt) ([raw file](https://github.com/servicecatalog/oscm/blob/a4b1908579499ed171c68d57e10d133ea765d3fd/oscm-security/javasrc/org/oscm/security/ADMRealmImpl.java#L223)):*
> ```Java
>         }
>     }
>    
> ```

Is this method used anywhere? if not let's remove it.

**Review by kowalczyka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/505)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @GoebelL)

___
*[oscm-security/javasrc/org/oscm/security/ADMRealmImpl.java, line 153 at r2](https://reviewable.io/reviews/servicecatalog/oscm/505#-LrJfiJoB7t080-uUNgI:-LrJfVFaEkW4xw82KyBq:b-b7qcfp) ([raw file](https://github.com/servicecatalog/oscm/blob/a4b1908579499ed171c68d57e10d133ea765d3fd/oscm-security/javasrc/org/oscm/security/ADMRealmImpl.java#L153)):*
> ```Java
> 
>     void handleOIDCLogin(String userKey, String password, UserQuery user) throws LoginException, SQLException, NamingException {
>         String callerType = getCallerType(password);
> ```

When login process is going through UI,  getting caller type will fail as the password is null/empty in this case in OIDC mode - this leads to Authentication failure.

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/505)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @kowalczyka)

___
*[oscm-security/javasrc/org/oscm/security/ADMRealmImpl.java, line 153 at r2](https://reviewable.io/reviews/servicecatalog/oscm/505#-LrJfiJoB7t080-uUNgI:-LrNjH249pEDhK4KEiUK:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/a4b1908579499ed171c68d57e10d133ea765d3fd/oscm-security/javasrc/org/oscm/security/ADMRealmImpl.java#L153)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

When login process is going through UI,  getting caller type will fail as the password is null/empty in this case in OIDC mode - this leads to Authentication failure.
</blockquote></details>

Done.
___
*[oscm-security/javasrc/org/oscm/security/ADMRealmImpl.java, line 223 at r2](https://reviewable.io/reviews/servicecatalog/oscm/505#-LrJb-P5AEu_1Dq4rHJq:-LrNjElo1IDrhAxeuhjS:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/a4b1908579499ed171c68d57e10d133ea765d3fd/oscm-security/javasrc/org/oscm/security/ADMRealmImpl.java#L223)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

Is this method used anywhere? if not let's remove it.
</blockquote></details>

Done.

**Review by kowalczyka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/505)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

___
*[oscm-security/javasrc/org/oscm/security/ADMRealmImpl.java, line 174 at r3](https://reviewable.io/reviews/servicecatalog/oscm/505#-LrOPiAn8PNnseOhxBUH:-LrOPiAn8PNnseOhxBUI:b8e363q) ([raw file](https://github.com/servicecatalog/oscm/blob/f5771d750d7b4a7abd13b32f9de9d63d89fcebf1/oscm-security/javasrc/org/oscm/security/ADMRealmImpl.java#L174)):*
> ```Java
>             ApiIdentityClient idc = getIdentityClient(tenantId);
>             String token = idc.getIdToken(userId, wsPassword);
>             idc.validateToken(token, TokenType.ID_TOKEN);
> ```

validateToken method was refactored to return user id - maybe we could addtionally check here if user id retrieved from validated token is the same as the one used in incoming request

**Review by kowalczyka — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/505)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/505)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

___
*[oscm-security/javasrc/org/oscm/security/ADMRealmImpl.java, line 174 at r3](https://reviewable.io/reviews/servicecatalog/oscm/505#-LrOPiAn8PNnseOhxBUH:-LrP79L0DFT4IdhNh8S3:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/f5771d750d7b4a7abd13b32f9de9d63d89fcebf1/oscm-security/javasrc/org/oscm/security/ADMRealmImpl.java#L174)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

validateToken method was refactored to return user id - maybe we could addtionally check here if user id retrieved from validated token is the same as the one used in incoming request
</blockquote></details>

Done.

**Review by kowalczyka — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/505#-:-LrP7fKd98NSMi-BrA1C:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
