### PR TITLE
Bug/aws empty logfile

### PR DESCRIPTION
**Pull request by Crystalzord**
**Changes in this pull request:**
- Add debug logging for aws controller that was missing compared to other controllers.
- Change default logging level from WARN to INFO to controllers. I think this is necessary because many important INFO logs are not written to the log file and it might suggest that the logging is not working correctly.
aws-log-info2conf

Besides that, actually aws log was not empty at all - indeed it logged errors correctly in my case.
For example, this piece of code is being executed during validating parameters for AWS controller and in case of for example missing name, the error is logged in the app-aws.log file
aws-log-logger-code

After setting the default logging to INFO to FILE, all messages are visible and it looks like this:
aws-log-info

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/253)

### CODE REVIEW

**Review by adamczykba — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/253)* status: all files reviewed, 2 unresolved discussions (waiting on @Crystalzord and @kowalczyka)

___
*[oscm-app-aws/javasrc/org/oscm/app/aws/controller/AWSController.java, line 428 at r1](https://reviewable.io/reviews/servicecatalog/oscm/253#-LaQUR8zEskv6v802GxC:-LaQUR9-3geXRN3thq94:b-e1yfub) ([raw file](https://github.com/servicecatalog/oscm/blob/91a4dcbdb1d2423e0f2a28a0fc9cdc4806a191d8/oscm-app-aws/javasrc/org/oscm/app/aws/controller/AWSController.java#L428)):*
> ```Java
>             return status;
>         } catch (Throwable t) {
>             LOGGER.debug("Failed to execute service operation "
> ```

Is it needed for prod? If yes, maybe we can change log level to error or warn?
___
*[oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/OpenStackController.java, line 314 at r1](https://reviewable.io/reviews/servicecatalog/oscm/253#-LaQUa8w8no9FGob_aXO:-LaQUa8w8no9FGob_aXP:b-89a4l7) ([raw file](https://github.com/servicecatalog/oscm/blob/91a4dcbdb1d2423e0f2a28a0fc9cdc4806a191d8/oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/OpenStackController.java#L314)):*
> ```Java
>                                 + propertyHandler.getState()
>                                 + " => nothing changed");
>                 LOGGER.debug(pe.getMessage());
> ```

Ditto

**Review by Crystalzord — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/253)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @adamczykba and @kowalczyka)

___
*[oscm-app-aws/javasrc/org/oscm/app/aws/controller/AWSController.java, line 428 at r1](https://reviewable.io/reviews/servicecatalog/oscm/253#-LaQUR8zEskv6v802GxC:-LaUfZK0-CICufzkW1sh:b922nq) ([raw file](https://github.com/servicecatalog/oscm/blob/91a4dcbdb1d2423e0f2a28a0fc9cdc4806a191d8/oscm-app-aws/javasrc/org/oscm/app/aws/controller/AWSController.java#L428)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Is it needed for prod? If yes, maybe we can change log level to error or warn?
</blockquote></details>

Changed to warn.
___
*[oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/OpenStackController.java, line 314 at r1](https://reviewable.io/reviews/servicecatalog/oscm/253#-LaQUa8w8no9FGob_aXO:-LaUfaVl2SJBaaOonoGb:bgeq5ei) ([raw file](https://github.com/servicecatalog/oscm/blob/91a4dcbdb1d2423e0f2a28a0fc9cdc4806a191d8/oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/OpenStackController.java#L314)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Changed to warn

**Review by adamczykba — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/253)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kowalczyka)

**Review by kowalczyka — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/253)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
