### PR TITLE
Docu customize bootstrap

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- Created README with customization guide
-Link to README
-Filter the branding package.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**
- add a screenshot illustrating your change

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1020)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r5, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1020)* status: all files reviewed, 3 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal/WebContent/marketplace/customBootstrap/README.md, line 4 at r7](https://reviewable.io/reviews/servicecatalog/oscm/1020#-MClkkdqDa1SLBtfXwis:-MClkkdqDa1SLBtfXwit:b-no97q4) ([raw file](https://github.com/servicecatalog/oscm/blob/c2ac3e1bbe44988fa04fc103f302bc8bff331f0f/oscm-portal/WebContent/marketplace/customBootstrap/README.md#L4)):*
> ```Markdown
> 
> ## Introduction
> The new public marketplace UI has been re-designed based on the Bootstrap framework version 4.3.1.  
> ```

Ok, let's describe the usage here not how the UI was changed. Avoid version numbers that have to be maintained. 

I'd simply say: The new marketplace UI has been designed based on the Bootstrap framework. 

... and some reference link would be nice as well.
___
*[oscm-portal/WebContent/marketplace/customBootstrap/README.md, line 9 at r7](https://reviewable.io/reviews/servicecatalog/oscm/1020#-MClmZTrBWgDHjADU_tZ:-MClmZTrBWgDHjADU_t_:b1dldem) ([raw file](https://github.com/servicecatalog/oscm/blob/c2ac3e1bbe44988fa04fc103f302bc8bff331f0f/oscm-portal/WebContent/marketplace/customBootstrap/README.md#L9)):*
> ```Markdown
> ### Prerequisites:
> 
> -	You have downloaded the provided branding package. The branding package can be downloaded as a ZIP file in the administration portal as an Operator in the *“Customize layout”* page by clicking the button *“Download branding package”*. The branding package contains two folders containing Sass source files: the *“scss”* folder, containing source files of mp.css, and the *“customBootstrap/scss”* folder containing the theme source files for the custom Bootstrap, explained later on.
> ```

Line break after first sentence (first sentences is like a bullet header, flow text paragraph starts with second sentence)
___
*[oscm-portal/WebContent/marketplace/customBootstrap/README.md, line 10 at r7](https://reviewable.io/reviews/servicecatalog/oscm/1020#-MClnd8l5HN33HSzthBL:-MClnd8l5HN33HSzthBM:b-npvif4) ([raw file](https://github.com/servicecatalog/oscm/blob/c2ac3e1bbe44988fa04fc103f302bc8bff331f0f/oscm-portal/WebContent/marketplace/customBootstrap/README.md#L10)):*
> ```Markdown
> 
> -	You have downloaded the provided branding package. The branding package can be downloaded as a ZIP file in the administration portal as an Operator in the *“Customize layout”* page by clicking the button *“Download branding package”*. The branding package contains two folders containing Sass source files: the *“scss”* folder, containing source files of mp.css, and the *“customBootstrap/scss”* folder containing the theme source files for the custom Bootstrap, explained later on.
> -	You have configured a Sass Compiler (a CSS pre-procesor) in order to compile your Sass source files with the file extension “.scss” and generate CSS stylesheets.  For more information on Sass and how to configure it, see the following [README](https://github.com/servicecatalog/oscm/tree/master/oscm-portal/WebContent/marketplace/scss/README.md).  
> ```

Make short bullet headers of following list points, like the first above. Short bullet header list is easier to overlook than all flow text.

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1020)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @GoebelL)

___
*[oscm-portal/WebContent/marketplace/customBootstrap/README.md, line 4 at r7](https://reviewable.io/reviews/servicecatalog/oscm/1020#-MClkkdqDa1SLBtfXwis:-MCqOMeGDANE1I1QXdwo:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/c2ac3e1bbe44988fa04fc103f302bc8bff331f0f/oscm-portal/WebContent/marketplace/customBootstrap/README.md#L4)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Ok, let's describe the usage here not how the UI was changed. Avoid version numbers that have to be maintained. 

I'd simply say: The new marketplace UI has been designed based on the Bootstrap framework. 

... and some reference link would be nice as well.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/customBootstrap/README.md, line 9 at r7](https://reviewable.io/reviews/servicecatalog/oscm/1020#-MClmZTrBWgDHjADU_tZ:-MCqOO8y0PW7N1rbiKtW:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/c2ac3e1bbe44988fa04fc103f302bc8bff331f0f/oscm-portal/WebContent/marketplace/customBootstrap/README.md#L9)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Line break after first sentence (first sentences is like a bullet header, flow text paragraph starts with second sentence)
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/customBootstrap/README.md, line 10 at r7](https://reviewable.io/reviews/servicecatalog/oscm/1020#-MClnd8l5HN33HSzthBL:-MCqOPuM2noGO6SxI9Yl:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/c2ac3e1bbe44988fa04fc103f302bc8bff331f0f/oscm-portal/WebContent/marketplace/customBootstrap/README.md#L10)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Make short bullet headers of following list points, like the first above. Short bullet header list is easier to overlook than all flow text.
</blockquote></details>

Done.

**Review by GoebelL — DISMISSED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1020)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by farmakiG** [comment]
:lgtm:

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1020)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
