### PR TITLE
Task/issue 1172 dark theme color contrast

### LINKED ISSUE #1172: Dark theme - better color contrast.
**Summary**
Adjust better color contrast between dark background and text color for Dark theme.

**Details**
Now the color contrast uses the default dark and light color themes of Bootstrap, and additionally the darken and lighten Sass functions for the lighter shades of gray for the different UI blocks: breadcrumb, Aside menu, Service cards, body background,color and "Profile", "Users" etc sections. Adapt a better color contrast for those blocks and the text-color on them based on another Sass function (for example hsl values, or theme-color-level Bootstrap built-in function).

**Acceptance criteria**
- [ ] UI Customizeability is preserved.
- [ ] Manual testing for both light and dark themes.

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- Adjusted color contrast for Dark theme for: btn-primary and btn-secondary buttons.
- Adjusted color contrast for links.
- Adjusted text-color on list-group-item-secondary to either black or white depending on its background-color. Used built-in Bootstrap color-yiq function (in version 5.0 upgraded to color-contrast)
- Adjusted text-color of table rows (as above) depending on its background color.
- Adjusted text-color of tables (as above) on row hover.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [X] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- est6

**Screenshot (if applicable):**
-Button and link color adjusted to higher color contrast.
Screenshot_2021-02-10 Marketplace

Screenshot_2021-02-10 Marketplace(1)

table_hover

Screenshot_2021-02-10 Marketplace(2)
** Lighthouse Reports**
Report_landing_page

Lighthouse report

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1193)

### CODE REVIEW

**Review by GoebelL — COMMENTED** [review]
> Reviewed 7 of 10 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1193)* status: 10 of 11 files reviewed, all discussions resolved

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1193)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-portal/WebContent/marketplace/account/unitsTable.xhtml, line 51 at r2](https://reviewable.io/reviews/servicecatalog/oscm/1193#-MTAp7e49RLT9xce5hpp:-MTAp7e5999cmUJ36fXX:bnk2512) ([raw file](https://github.com/servicecatalog/oscm/blob/defb9c1a1516a4a90fc7752eb73a1dcf705289e6/oscm-portal/WebContent/marketplace/account/unitsTable.xhtml#L51)):*
> ```HTML
>           <h:outputText id="groupName" value="#{group.groupName}"/>
>         </a4j:outputPanel>
>         </f:facet>
> ```

I have some doubt about these changes. The header facet it spanning the whole column content now !? Did you tests this with several group entries? 
Please add a screenshot of your group table.

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1193)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-portal/WebContent/marketplace/account/unitsTable.xhtml, line 51 at r2](https://reviewable.io/reviews/servicecatalog/oscm/1193#-MTAp7e49RLT9xce5hpp:-MTB3A780WkoWnnbmFJe:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/defb9c1a1516a4a90fc7752eb73a1dcf705289e6/oscm-portal/WebContent/marketplace/account/unitsTable.xhtml#L51)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

I have some doubt about these changes. The header facet it spanning the whole column content now !? Did you tests this with several group entries? 
Please add a screenshot of your group table. 
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]

**Review by GoebelL — DISMISSED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1193)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 8 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1193)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
