### PR TITLE
Customize bootstrap

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- Added two templates darkCustom.css and darkFooter.cs for customizeable dark header & footer, and two templates for the light version.
-Load per default the dark header & footer.
 
**Mandatory checks:**
- [X] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [X] changes were tested manually
- [ ] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [X] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- Docker_OSCM/job/OSCM_Docker_Build_and_push/663/

**UI Screenshots** 
Screenshot_2020-05-04 Marketplace (2)
Screenshot_2020-05-04 Marketplace(1)
Screenshot_2020-05-04 Marketplace(2)
Screenshot_2020-05-04 Marketplace(3)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/834)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 8 of 114 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/834)* status: 8 of 114 files reviewed, 3 unresolved discussions (waiting on @farmakiG)

___
*[oscm-devruntime/javares/build-oscmaas.xml, line 31 at r1](https://reviewable.io/reviews/servicecatalog/oscm/834#-M6UmR8wB_y7WjVrHAyy:-M6UmR8wB_y7WjVrHAyz:b3kre) ([raw file](https://github.com/servicecatalog/oscm/blob/af2dedfa9d0f23339da51f4bf75efd1334aa9755/oscm-devruntime/javares/build-oscmaas.xml#L31)):*
> ```XML
>   
>  
>   
> ```

?
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml, line 12 at r1](https://reviewable.io/reviews/servicecatalog/oscm/834#-M6UnWTl1B26z1pSjcAK:-M6UnWTl1B26z1pSjcAL:bqsr8uw) ([raw file](https://github.com/servicecatalog/oscm/blob/af2dedfa9d0f23339da51f4bf75efd1334aa9755/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml#L12)):*
> ```HTML
>   <c:set var="logoimg" value="#{sessionBean.marketplaceBrandBaseUrl}/img/mp_logo3.png"/>
> 
>   <nav class="px-1 navbar navbar-expand-lg navbar-dark bg-dark">
> ```

Can't we leave fixed-top here?
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml, line 15 at r1](https://reviewable.io/reviews/servicecatalog/oscm/834#-M6Unind43cOC1X3d39i:-M6Unind43cOC1X3d39j:b-8h66d1) ([raw file](https://github.com/servicecatalog/oscm/blob/af2dedfa9d0f23339da51f4bf75efd1334aa9755/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml#L15)):*
> ```HTML
>     <div class="container-fluid h6 m-0 px-3">
>        <div class="no-gutters row align-items-center">
>         <a class= "navbar-brand" href="#{mpBaseUrl}/index.jsf"> <h:graphicImage value="${logoimg}"
> ```

by the way we are here, let's change this to href="..../playground.jsf"

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 114 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/834)* status: 9 of 114 files reviewed, 3 unresolved discussions (waiting on @farmakiG)

**Comment by farmakiG** [comment]
___
*[oscm-devruntime/javares/build-oscmaas.xml, line 31 at r1](https://reviewable.io/reviews/servicecatalog/oscm/834#-M6UmR8wB_y7WjVrHAyy:-M6VDFAK3Mf0OdHzhnui:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/af2dedfa9d0f23339da51f4bf75efd1334aa9755/oscm-devruntime/javares/build-oscmaas.xml#L31)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/834)* status: 8 of 113 files reviewed, 3 unresolved discussions (waiting on @GoebelL)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml, line 12 at r1](https://reviewable.io/reviews/servicecatalog/oscm/834#-M6UnWTl1B26z1pSjcAK:-M6VDLEA4BDqErYL2Lj5:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/af2dedfa9d0f23339da51f4bf75efd1334aa9755/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml#L12)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Can't we leave fixed-top here?
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml, line 15 at r1](https://reviewable.io/reviews/servicecatalog/oscm/834#-M6Unind43cOC1X3d39i:-M6VDNEQ-tpQdSq_9uZK:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/af2dedfa9d0f23339da51f4bf75efd1334aa9755/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml#L15)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

by the way we are here, let's change this to href="..../playground.jsf" 
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 104 of 114 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/834)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mchudy-fujitsu)

**Review by GoebelL — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/834#-:-M6Z7QveBaTn7UDMLHzu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mchudy-fujitsu)

**Pull request merged**
