### PR TITLE
Responsive service page

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
- Create responsive version of service page

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [ ] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [ ] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
N/A

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/733)

### CODE REVIEW

**Review by farmakiG — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/733)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/categorySelectionBootstrap.xhtml, line 19 at r1](https://reviewable.io/reviews/servicecatalog/oscm/733#-M37Ch5rC-Zjd_w6Uso6:-M37Ch5s6P5PNSreV4BB:b-vfv9q2) ([raw file](https://github.com/servicecatalog/oscm/blob/a05215bf133edfa3a236d381f9fe1a9c6a8a621e/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/categorySelectionBootstrap.xhtml#L19)):*
> ```HTML
>                 </h:commandButton>
> 
> 
> ```

Remove comment.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/pagingPanelBootstrap.xhtml, line 44 at r1](https://reviewable.io/reviews/servicecatalog/oscm/733#-M37DIG28O3BMesdGGpU:-M37DIG28O3BMesdGGpV:b-vfv9q2) ([raw file](https://github.com/servicecatalog/oscm/blob/a05215bf133edfa3a236d381f9fe1a9c6a8a621e/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/pagingPanelBootstrap.xhtml#L44)):*
> ```HTML
>                     class="fa fa-arrow-left"></i> #{msg['paging.previous']}
>                 </button>
>                 
> ```

Remove comment.

**Review by farmakiG — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/733)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @farmakiG and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/pagingPanelBootstrap.xhtml, line 80 at r1](https://reviewable.io/reviews/servicecatalog/oscm/733#-M37DPHN3nWqnA67su45:-M37DPHN3nWqnA67su46:b-vfv9q2) ([raw file](https://github.com/servicecatalog/oscm/blob/a05215bf133edfa3a236d381f9fe1a9c6a8a621e/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/pagingPanelBootstrap.xhtml#L80)):*
> ```HTML
>                 <button id="next#{prefix}" type="button" class="btn btn-outline-secondary" disabled="disabled">
>                   #{msg['paging.next']} <i class="fa fa-arrow-right"></i></button>
>                 
> ```

Remove comment.

**Review by farmakiG — COMMENTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/733)* status: all files reviewed, 3 unresolved discussions (waiting on @mchudy-fujitsu)

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/733)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/categorySelectionBootstrap.xhtml, line 19 at r1](https://reviewable.io/reviews/servicecatalog/oscm/733#-M37Ch5rC-Zjd_w6Uso6:-M3A3Eh93o3oTWMrFBJG:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/a05215bf133edfa3a236d381f9fe1a9c6a8a621e/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/categorySelectionBootstrap.xhtml#L19)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Remove comment.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/pagingPanelBootstrap.xhtml, line 44 at r1](https://reviewable.io/reviews/servicecatalog/oscm/733#-M37DIG28O3BMesdGGpU:-M3A3RXW9P8MUpKxryRd:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/a05215bf133edfa3a236d381f9fe1a9c6a8a621e/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/pagingPanelBootstrap.xhtml#L44)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Remove comment.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/pagingPanelBootstrap.xhtml, line 80 at r1](https://reviewable.io/reviews/servicecatalog/oscm/733#-M37DPHN3nWqnA67su45:-M3A3SGy40CIL7UPKJjj:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/a05215bf133edfa3a236d381f9fe1a9c6a8a621e/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/pagingPanelBootstrap.xhtml#L80)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Remove comment.
</blockquote></details>

Done.

**Review by farmakiG — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/733)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
