### PR TITLE
Fixed logout URL

### PR DESCRIPTION
**Pull request by GoebelL**
Fixed broken logout link.

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/397)

### CODE REVIEW

**Review by adamczykba — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/397)* status: all files reviewed, 4 unresolved discussions (waiting on @GoebelL)

___
*[oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java, line 91 at r1](https://reviewable.io/reviews/servicecatalog/oscm/397#-LllEuhD9VKJHaeTddmJ:-LllEuhD9VKJHaeTddmK:bmtg76q) ([raw file](https://github.com/servicecatalog/oscm/blob/9fdeb1c81a4e026e8c0a0fb55c7da6da4ea4aed1/oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java#L91)):*
> ```Java
>  
>   protected String buildLogoutUrl(String requestedUrl) throws URISyntaxException {
>     String logoutUrl;
> ```

Is there a reason for splitting definition and decalration there?
___
*[oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java, line 94 at r1](https://reviewable.io/reviews/servicecatalog/oscm/397#-LllFDGTDg8IU3L50jNn:-LllFDGTDg8IU3L50jNo:b-918v28) ([raw file](https://github.com/servicecatalog/oscm/blob/9fdeb1c81a4e026e8c0a0fb55c7da6da4ea4aed1/oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java#L94)):*
> ```Java
>     URI uri = new URI(requestedUrl);
>     logoutUrl = buildLogoutUrlFromRequestUri(uri);
>     return logoutUrl;
> ```

Couldn't we just return buildLogoutUrlFromRequestUri(uri); ? 
___
*[oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java, line 98 at r1](https://reviewable.io/reviews/servicecatalog/oscm/397#-LllF3Nq4K7YgJXilhLB:-LllF3Nq4K7YgJXilhLC:bmtg76q) ([raw file](https://github.com/servicecatalog/oscm/blob/9fdeb1c81a4e026e8c0a0fb55c7da6da4ea4aed1/oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java#L98)):*
> ```Java
> 
>   protected String buildLogoutUrlFromRequestUri(URI uri) {
>     String logoutUrl;
> ```

Is there a reason for splitting definition and decalration there?
___
*[oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java, line 102 at r1](https://reviewable.io/reviews/servicecatalog/oscm/397#-LllF7HJ5u26bTpz-YV6:-LllF7HJ5u26bTpz-YV7:b-ddd1n2) ([raw file](https://github.com/servicecatalog/oscm/blob/9fdeb1c81a4e026e8c0a0fb55c7da6da4ea4aed1/oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java#L102)):*
> ```Java
> 
>     String hostname = uri.getHost();
>     logoutUrl =
> ```

Couldn't we just return "https://" + hostname + ":9091/oscm-identity/logout?state=" + redirectionUrl; ?

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/397)* status: all files reviewed, 4 unresolved discussions (waiting on @adamczykba and @GoebelL)

___
*[oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java, line 91 at r1](https://reviewable.io/reviews/servicecatalog/oscm/397#-LllEuhD9VKJHaeTddmJ:-LllGa0aDKwYBij0xByR:bvsonc5) ([raw file](https://github.com/servicecatalog/oscm/blob/9fdeb1c81a4e026e8c0a0fb55c7da6da4ea4aed1/oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java#L91)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Is there a reason for splitting definition and decalration there?
</blockquote></details>

It's done for having better testable code and not causing any issue. The filter method is delegating the URL construction as it's not it's main task. Leave it.
___
*[oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java, line 102 at r1](https://reviewable.io/reviews/servicecatalog/oscm/397#-LllF7HJ5u26bTpz-YV6:-LllHhN-8hd7pNilnfES:bm99vov) ([raw file](https://github.com/servicecatalog/oscm/blob/9fdeb1c81a4e026e8c0a0fb55c7da6da4ea4aed1/oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java#L102)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Couldn't we just return "https://" + hostname + ":9091/oscm-identity/logout?state=" + redirectionUrl; ?
</blockquote></details>

Also done for testing . Anyway, the real issue is hard coding the URLs - this is a subsequent tasks to fix. 
This fix will also require reworking this logic. So, we don't put any effort here now.

**Review by adamczykba — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/397#-:-LllJ1p7-ILRlTQhJ4CM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by adamczykba — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/397#-:-LllM5bF6dY0KngwFR-t:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
