### PR TITLE
Redesign of subcription process payment page

### LINKED ISSUE #801: [Subscription UI] Redesign payment subscription page
**Summary**
Redesign second step Page of Subscription Creation.

**Details**
The second page which appears when creating a new Subscription (where the user clicks on Confirm dialog) should become responsive.

**Acceptance criteria**
- [ ] Functionality remains as before
- [ ] UI test (previous UI test for the first step of Subscription creation can be extended by one further step).

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
- Subcription process payment page
- UI tests

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [x] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Integration_Tests_INTERNAL/145/

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/835)

### CODE REVIEW

**Review by GoebelL — COMMENTED** [review]
> Reviewed 7 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/835)* status: 7 of 16 files reviewed, 1 unresolved discussion (waiting on @mchudy-fujitsu)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/subscriptionProcessPaymentBootstrap.xhtml, line 104 at r1](https://reviewable.io/reviews/servicecatalog/oscm/835#-M6Z-NYv9pJDt9iSj6GR:-M6Z-NYv9pJDt9iSj6GS:brviroi) ([raw file](https://github.com/servicecatalog/oscm/blob/bd90842b6668387d70445471caa86c4bca430504/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/subscriptionProcessPaymentBootstrap.xhtml#L104)):*
> ```HTML
> 
>     <div class="col-md-4 col-sm-12">
>         <a4j:outputPanel id="piInformation" layout="block">
> ```

Minor formatting: Please use code indent of 2 spaces and remove the blank lines

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/835)* status: 7 of 15 files reviewed, all discussions resolved (waiting on @farmakiG)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/subscriptionProcessPaymentBootstrap.xhtml, line 104 at r1](https://reviewable.io/reviews/servicecatalog/oscm/835#-M6Z-NYv9pJDt9iSj6GR:-M6Z1WjT1R8_nL-Dm-N_:bb6un1j) ([raw file](https://github.com/servicecatalog/oscm/blob/bd90842b6668387d70445471caa86c4bca430504/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/subscriptionProcessPaymentBootstrap.xhtml#L104)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Minor formatting: Please use code indent of 2 spaces and remove the blank lines
</blockquote></details>

Done

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/835)* status: 8 of 15 files reviewed, all discussions resolved (waiting on @farmakiG)

**Review by farmakiG — CHANGES_REQUESTED** [review]
> Reviewed 4 of 16 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/835)* status: 13 of 15 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/subscriptions/creation/playgroundPaymentAdd.xhtml, line 18 at r2](https://reviewable.io/reviews/servicecatalog/oscm/835#-M6_-sjcCouTYxxUI-Ct:-M6_-sje0NL7BRmoOVIA:b-sat415) ([raw file](https://github.com/servicecatalog/oscm/blob/51507011f7476720ba8f8a9f954ddeb5b16ee0d4/oscm-portal/WebContent/marketplace/subscriptions/creation/playgroundPaymentAdd.xhtml#L18)):*
> ```HTML
>   <ui:define name="breadcrumbs">
>     <mp:bootstrapBreadcrumbs>
>       <mp:crumb labelPageId="marketplace.services" link="/marketplace/services.jsf"/>
> ```

Add link to playgroundServices in breadcrumbs so that we unify the playground UI.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/subscriptions/creation/playgroundPaymentAdd.xhtml, line 59 at r2](https://reviewable.io/reviews/servicecatalog/oscm/835#-M6_0tp503y85MHrfdFK:-M6_0tp503y85MHrfdFL:bnd3szn) ([raw file](https://github.com/servicecatalog/oscm/blob/51507011f7476720ba8f8a9f954ddeb5b16ee0d4/oscm-portal/WebContent/marketplace/subscriptions/creation/playgroundPaymentAdd.xhtml#L59)):*
> ```HTML
>         <div>
>           <mp:subscriptionProcessProgressBootstrap active="payment"/>
>         </div>
> ```

why don t you include this big section with <ui:include playgroundPayment.xhtml>?

**Review by farmakiG — COMMENTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/835)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @farmakiG and @mchudy-fujitsu)

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/835)* status: 13 of 18 files reviewed, 2 unresolved discussions (waiting on @farmakiG and @GoebelL)

___
*[oscm-portal/WebContent/marketplace/subscriptions/creation/playgroundPaymentAdd.xhtml, line 18 at r2](https://reviewable.io/reviews/servicecatalog/oscm/835#-M6_-sjcCouTYxxUI-Ct:-M6cwHEpEHC-cROmtVZZ:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/51507011f7476720ba8f8a9f954ddeb5b16ee0d4/oscm-portal/WebContent/marketplace/subscriptions/creation/playgroundPaymentAdd.xhtml#L18)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Add link to playgroundServices in breadcrumbs so that we unify the playground UI.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/subscriptions/creation/playgroundPaymentAdd.xhtml, line 59 at r2](https://reviewable.io/reviews/servicecatalog/oscm/835#-M6_0tp503y85MHrfdFK:-M6cwGID79hDgLAX7tYQ:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/51507011f7476720ba8f8a9f954ddeb5b16ee0d4/oscm-portal/WebContent/marketplace/subscriptions/creation/playgroundPaymentAdd.xhtml#L59)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

why don t you include this big section with <ui:include playgroundPayment.xhtml>?
</blockquote></details>

Done.

**Review by farmakiG — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/835)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
