### PR TITLE
Task/651

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
- Created new css class
- Changed dropdown width on pages: shop/manageBrokerRevenueShare, shop/manageResellerRevenueShare, operator/manageOperatorRevenueShare

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [ ] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM Build And Push job](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Docker_Build_and_push/467/)
- [OSCM Pull And Start job](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Docker_pull_and_start/756/)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/664)

### CODE REVIEW

**Review by farmakiG — CHANGES_REQUESTED** [review]
When you resize the Browser Window the Dropdown exceeds the panel size.

**Review by farmakiG — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/664)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/css/portal.css, line 1028 at r2](https://reviewable.io/reviews/servicecatalog/oscm/664#-M0MjzTxAnehiNjVM8Gt:-M0MjzTxAnehiNjVM8Gu:b-32obfi) ([raw file](https://github.com/servicecatalog/oscm/blob/a7ad6ec5ce17feb2d7cd0202585c710c23cb520c/oscm-portal/WebContent/css/portal.css#L1028)):*
> ```CSS
>     padding: 0, 10px
>     max-width: 450px;
> }
> ```

Hi you forgot ";" separator.

**Review by farmakiG — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/664)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @farmakiG and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/operator/manageOperatorRevenueShare.xhtml, line 89 at r10](https://reviewable.io/reviews/servicecatalog/oscm/664#-M0NULUQBhlRrgRc4UjR:-M0NULURD1u6MHXV7FzA:bbplry2) ([raw file](https://github.com/servicecatalog/oscm/blob/f7c7177dfda07c76a73d7a6d8ef0cfd869e48224/oscm-portal/WebContent/operator/manageOperatorRevenueShare.xhtml#L89)):*
> ```HTML
>     <script type="text/javascript">
>       $('document').ready(function(){
>       document.getElementsByClassName('select2')[0].style="width: 100%"
> ```

Hi. I think a nicer way to solve this is to set an inline style for b:selectOneMenu, such as style="width: 100%;". And in order for select2 plugin to take it into account, you can specify it such as: $(".select2).select2(){width:resolve}

**Review by farmakiG — COMMENTED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/664)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @farmakiG and @mchudy-fujitsu)

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/css/portal.css, line 1037 at r13](https://reviewable.io/reviews/servicecatalog/oscm/664#-M0RgLJ63BB7tJ6nml4n:-M0RgLJ63BB7tJ6nml4o:b-7x5nvz) ([raw file](https://github.com/servicecatalog/oscm/blob/f98bead50ddbc9b92029eac7ef2ab41d291c810d/oscm-portal/WebContent/css/portal.css#L1037)):*
> ```CSS
> 
> .selectWide {
>     width: 100%
> ```

Hi. You still forgot ";".

**Review by farmakiG — COMMENTED** [review]
> Reviewed 4 of 4 files at r11, 2 of 2 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 2 of 2 files at r15, 2 of 2 files at r16, 2 of 2 files at r17, 2 of 2 files at r18, 1 of 1 files at r19, 4 of 4 files at r20, 1 of 1 files at r21, 3 of 3 files at r22, 3 of 3 files at r23.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/664)* status: all files reviewed, 1 unresolved discussion (waiting on @mchudy-fujitsu)

**Review by farmakiG — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/664)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/664)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[oscm-portal/WebContent/css/portal.css, line 1028 at r2](https://reviewable.io/reviews/servicecatalog/oscm/664#-M0MjzTxAnehiNjVM8Gt:-M0RicTq-IdQ-n_MgykQ:bs7wumb) ([raw file](https://github.com/servicecatalog/oscm/blob/a7ad6ec5ce17feb2d7cd0202585c710c23cb520c/oscm-portal/WebContent/css/portal.css#L1028)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Hi you forgot ";" separator.
</blockquote></details>

Done.

**Pull request merged**
