### PR TITLE
Task#768 Replace header and footer #765 #768

### LINKED ISSUE #765: Replace Bootstrap Navigation bar in Marketplace UI.
**Summary**
Replace the already implemented Bootstrap header menu bar in the rest of the MP UI pages.

**Details**
A headerBootstrap tag has been already implemented. Replace the reference of this header to the rest of the Marketplace UI pages. 
Basically, the point to solve in this issue is the following: The Bootstrap Navigation bar is responsive, while the other pages are not yet responsive. Ensure this does not worsen the user experience and  confuse the user.
Since we show a "Toggle" button in the navigation bar for medium screens, this overcomes the above issue with the user experience.

**Acceptance criteria**
- [ ] The functionality of affected pages is not broken.
- [ ] The styling of affected pages remains professional.
- [ ] One small UI Test for opening one page with the Bootstrap nav bar & checking if it has the defined Bootstrap classes.

**Additional context**
N/A.

### LINKED ISSUE #768: Replace Bootstrap footer in MP pages.
**Summary**
Replace the footer in MP UI pages with the already implemented Bootstrap footer.

**Details**
A footer for Bootstrap has already been implemented in the mainBootstrap template. Split it to a new tag "bootstrapFooter" and reference it in both "main" and "mainBootstrap" template. 
(As a next step, to be defined in a next task, replace step by step the main template with the mainBootstrap template in UI pages.)

**Acceptance criteria**
- [ ] The footer is replaced in MP UI pages and is responsive.
- [ ] Small UI Test for opening one page and checking if footer of style bootstrap_footer is present.

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Implement bootstrap header and footer
- Add new tests 
- Fixed tests

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [ ] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM_Integration_Tests_INTERNAL](<enter URL to a job here>)
- [OSCM_Integration_Tests_OIDC](<enter URL to a job here>)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/778)

### CODE REVIEW

**Review by farmakiG — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/778)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @farmakiG, @KabacinskiPiotr, and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 212 at r3](https://reviewable.io/reviews/servicecatalog/oscm/778#-M4TV32B19Vgclt-4O8t:-M4TV32C9iLc5WmMVcKX:bl9xlie) ([raw file](https://github.com/servicecatalog/oscm/blob/eba86b672810b4910b73d00bbe126cd315bdcae7/oscm-portal/WebContent/marketplace/css/mp.css#L212)):*
> ```CSS
>  
> p { margin-top: 0; margin-bottom: 1.75em; padding: 0; line-height: 1.5; }
> ul { margin-top: 0; margin-bottom: 1.75em; margin-left: 0; padding: 0 0 0 2.8em; }
> ```

Basically it is not a good approach to overwrite styles with !important. Since we would like to use the Bootstrap look-and-feel and be able to customize it, these !important flags will always overwrite the custom styles we have defined. I suggest a new Issue is created for following a better design principle.

**Review by farmakiG — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/778)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @farmakiG, @KabacinskiPiotr, and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/templates/main.xhtml, line 165 at r3](https://reviewable.io/reviews/servicecatalog/oscm/778#-M4TVzuVCOYluAaZyBgM:-M4TVzuVCOYluAaZyBgN:b-v7nvi) ([raw file](https://github.com/servicecatalog/oscm/blob/455296ea7386386028a29ac329bb85e6542180f5/oscm-portal/WebContent/marketplace/templates/main.xhtml#L165)):*
> ```HTML
>     value="#{empty translationBean.imprintSessionLocale ? defaultImprintUrl : translationBean.imprintSessionLocale}" />
> 
>   <div class="footer">
> ```

I think the first two lines a4j:outputPanel and div id=permanentmenu are no longer necessary.

**Review by farmakiG — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/778)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @farmakiG, @KabacinskiPiotr, and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml, line 95 at r3](https://reviewable.io/reviews/servicecatalog/oscm/778#-M4TZIr67nBVGMF2TguR:-M4TZIr67nBVGMF2TguS:b-czj8e6) ([raw file](https://github.com/servicecatalog/oscm/blob/eba86b672810b4910b73d00bbe126cd315bdcae7/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml#L95)):*
> ```HTML
>               <li class="nav-item dropdown"><a class="nav-link dropdown-toggle waves-effect waves-light" href="#" id="logoutDrop"
>                 data-toggle="dropdown"><i class="fa fa-user"/>
>                 <h:outputText id="welcome"/> User </a>
> ```

The messages "User" and "Logged-in-as" should be localized.

**Comment by Piotr-K8i** [comment]
___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 212 at r3](https://reviewable.io/reviews/servicecatalog/oscm/778#-M4TV32B19Vgclt-4O8t:-M4TjPXI5tw97DXLMI9S:bju6mex) ([raw file](https://github.com/servicecatalog/oscm/blob/eba86b672810b4910b73d00bbe126cd315bdcae7/oscm-portal/WebContent/marketplace/css/mp.css#L212)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Basically it is not a good approach to overwrite styles with !important. Since we would like to use the Bootstrap look-and-feel and be able to customize it, these !important flags will always overwrite the custom styles we have defined. I suggest a new Issue is created for following a better design principle.
</blockquote></details>

https://app.zenhub.com/workspaces/oscm-59f31a4996b6c551bc556610/issues/servicecatalog/oscm/782

**Comment by Piotr-K8i** [comment]
___
*[oscm-portal/WebContent/marketplace/templates/main.xhtml, line 165 at r3](https://reviewable.io/reviews/servicecatalog/oscm/778#-M4TVzuVCOYluAaZyBgM:-M4TjgKZ74kPIfYEA62Z:b-re8byn) ([raw file](https://github.com/servicecatalog/oscm/blob/455296ea7386386028a29ac329bb85e6542180f5/oscm-portal/WebContent/marketplace/templates/main.xhtml#L165)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

I think the first two lines a4j:outputPanel and div id=permanentmenu are no longer necessary.
</blockquote></details>

Yes, this is deleted

**Comment by Piotr-K8i** [comment]
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml, line 95 at r3](https://reviewable.io/reviews/servicecatalog/oscm/778#-M4TZIr67nBVGMF2TguR:-M4Tjnt2CA5D34jtIoB1:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/eba86b672810b4910b73d00bbe126cd315bdcae7/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml#L95)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

The messages "User" and "Logged-in-as" should be localized. 
</blockquote></details>

Done.

**Review by mchudy-fujitsu — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, 2 of 3 files at r2, 3 of 3 files at r3, 1 of 4 files at r4, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/778)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @farmakiG and @mchudy-fujitsu)

**Review by mchudy-fujitsu — APPROVED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/778)* status: all files reviewed, 3 unresolved discussions (waiting on @farmakiG)

**Pull request merged**
