### PR TITLE
Task#698 disable tracking code field

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Add as a default value for selectOneMenu empty string
- Clean code at trackingCode.xhtml

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [ ] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM Build And Push job](<enter URL to a job here>)
- [OSCM Pull And Start job](<enter URL to a job here>)

[Link for node with this branch](http://10.140.16.80:8080/job/OSCM_Update_oscm_core/681/)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/715)

### CODE REVIEW

**Review by mchudy-fujitsu — DISMISSED** [review]

**Review by GoebelL — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/715)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KabacinskiPiotr)

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/715)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @KabacinskiPiotr)

*[a discussion](https://reviewable.io/reviews/servicecatalog/oscm/715#-M28yyrHEsBsFlZLjsW_:-M28yyrHEsBsFlZLjsWa:b4783wl) (no related file):*
 TrackingCodeCtrlTest failure https://travis-ci.org/github/servicecatalog/oscm/builds/661090742#L30765

---

**Review by Piotr-K8i — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/715)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

*[a discussion](https://reviewable.io/reviews/servicecatalog/oscm/715#-M28yyrHEsBsFlZLjsW_:-M29Fc1BEcVflJV_WtNe:b-896fix) (no related file):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

 TrackingCodeCtrlTest failure https://travis-ci.org/github/servicecatalog/oscm/builds/661090742#L30765
</blockquote></details>

Done.

---

**Review by mchudy-fujitsu — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/715)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @GoebelL and @KabacinskiPiotr)

___
*[oscm-portal-unittests/javasrc/org/oscm/ui/dialog/classic/trackingCode/TrackingCodeCtrlTest.java, line 131 at r4](https://reviewable.io/reviews/servicecatalog/oscm/715#-M2CgX6c8juNWaNrtvuy:-M2CgX6c8juNWaNrtvuz:b34abka) ([raw file](https://github.com/servicecatalog/oscm/blob/18edf601bf359614b255d21197f8aedf1149252b/oscm-portal-unittests/javasrc/org/oscm/ui/dialog/classic/trackingCode/TrackingCodeCtrlTest.java#L131)):*
> ```Java
>     public void marketplaceChangedIntoDefaultValue() throws Exception {
>         model.setSelectedMarketplace("");
>         doReturn(new Response()).when(tcMgmServ)
> ```

This shouldn't be required in a given test case loadTrackingCodeForMarketplace should never be called. It would be a good idea to verify that.
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/dialog/classic/trackingCode/TrackingCodeCtrlTest.java, line 236 at r4](https://reviewable.io/reviews/servicecatalog/oscm/715#-M2ChLq9ALG1kzqMOC8C:-M2ChLq9ALG1kzqMOC8D:bb752ax) ([raw file](https://github.com/servicecatalog/oscm/blob/18edf601bf359614b255d21197f8aedf1149252b/oscm-portal-unittests/javasrc/org/oscm/ui/dialog/classic/trackingCode/TrackingCodeCtrlTest.java#L236)):*
> ```Java
>         doReturn(null).when(model).getSelectedMarketplace();
>         // when
>         boolean isDisables = controller.isFieldsDisabled();
> ```

Typo
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/dialog/classic/trackingCode/TrackingCodeCtrlTest.java, line 245 at r4](https://reviewable.io/reviews/servicecatalog/oscm/715#-M2ChjPI1e4BxlbxoA5x:-M2ChjPI1e4BxlbxoA5y:b3ks9) ([raw file](https://github.com/servicecatalog/oscm/blob/18edf601bf359614b255d21197f8aedf1149252b/oscm-portal-unittests/javasrc/org/oscm/ui/dialog/classic/trackingCode/TrackingCodeCtrlTest.java#L245)):*
> ```Java
>         when(model.getSelectedMarketplace()).thenReturn("marketplace");
>         // when
>         boolean isDisables = controller.isFieldsDisabled();
> ```

^

**Review by mchudy-fujitsu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/715)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Pull request merged**
