### PR TITLE
Task/sync credentials client

### PR DESCRIPTION
**Pull request by kowalczyka**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/291)

### CODE REVIEW

**Review by GoebelL — APPROVED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/291)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

___
*[oscm-portal/.classpath, line 52 at r1](https://reviewable.io/reviews/servicecatalog/oscm/291#-Ld8V6Nm2zCeadmli0PS:-Ld8V6Nn8J5vj_qoYAPz:ba68suv) ([raw file](https://github.com/servicecatalog/oscm/blob/2c79f6eac3b4ffab00d91fbaf479cfe7688db459/oscm-portal/.classpath#L52)):*
> ```XML
> 	<classpathentry kind="lib" path="/libraries/apache-tomee/javalib/geronimo-javamail_1.4_mail-1.9.0-alpha-2.jar"/>
> 	<classpathentry kind="lib" path="/libraries/apache-tomee/javalib/openejb-loader-7.0.3.jar"/>
> 	<classpathentry combineaccessrules="false" kind="src" path="/oscm-app-extsvc-2-0"/>
> ```

Check if needed.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/291)* status: all files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/291)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-portal/.classpath, line 52 at r1](https://reviewable.io/reviews/servicecatalog/oscm/291#-Ld8V6Nm2zCeadmli0PS:-LdDNadU2VyH59h0idho:bjqyfww) ([raw file](https://github.com/servicecatalog/oscm/blob/2c79f6eac3b4ffab00d91fbaf479cfe7688db459/oscm-portal/.classpath#L52)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Check if needed.
</blockquote></details>

Yes, this is needed as  APP interface must be available for oscm-portal.

**Review by GoebelL — APPROVED** [review]
> Reviewed 21 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/291)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/291)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
