### PR TITLE
Fix ip not ready in a virtualdistributedswitch environment bug

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/278)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/278)* status: all files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VM.java, line 455 at r1](https://reviewable.io/reviews/servicecatalog/oscm/278#-Lc1I1VDEOJabgeCgmFe:-Lc1I1VDEOJabgeCgmFf:b-xrneck) ([raw file](https://github.com/servicecatalog/oscm/blob/340fae6a6772eafdfacea66320059a65cdbf3253/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VM.java#L455)):*
> ```Java
>         if ((validHostname && networkCardsConnected && validIp
>                 && isGuestSystemRunning() && areGuestToolsRunning())
>                 || (validHostname && networkCardsConnected && !getPortGroup(properties).isEmpty()
> ```

Functionally ok, but the code reading should be simplified. 
E.g. refactor added condition and extract "!getPortGroup(properties).isEmpty()" in boolean method arePortGroupsSet()

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/278)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VM.java, line 455 at r1](https://reviewable.io/reviews/servicecatalog/oscm/278#-Lc1I1VDEOJabgeCgmFe:-Lc65Ll5BohkK3dCL3YQ:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/340fae6a6772eafdfacea66320059a65cdbf3253/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/VM.java#L455)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Functionally ok, but the code reading should be simplified. 
E.g. refactor added condition and extract "!getPortGroup(properties).isEmpty()" in boolean method arePortGroupsSet()
</blockquote></details>

Done.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/278)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/278)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
