### PR TITLE
[Subscription UI] Price model tab

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
- Added price model tab to subscription details page.

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [x] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
N/A

**Screenshot (if applicable):**
FireShot Capture 048 - Marketplace - 10 140 18 99
FireShot Capture 049 - Marketplace - 10 140 18 99

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/872)

### CODE REVIEW

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/playground/subscriptions/priceModelDetails.xhtml, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm/872#-M8AZLhk5xAa-GOUHU_e:-M8AZLhk5xAa-GOUHU_f:b-7mo7f4) ([raw file](https://github.com/servicecatalog/oscm/blob/9d070750fe82638f74c3d5587eb743c0887dad5e/oscm-portal/WebContent/marketplace/playground/subscriptions/priceModelDetails.xhtml#L1)):*
> ```HTML
> 
> ```

Remove empty line.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/css/mpOverrides.css, line 74 at r1](https://reviewable.io/reviews/servicecatalog/oscm/872#-M8A_2N3BswgoUrXDzlv:-M8A_2N3BswgoUrXDzlw:bwo1ml2) ([raw file](https://github.com/servicecatalog/oscm/blob/9d070750fe82638f74c3d5587eb743c0887dad5e/oscm-portal/WebContent/css/mpOverrides.css#L74)):*
> ```CSS
>     background-position: -8px -205px;
> }
> ```

Add comment about "Bootstrap suspended message" so that we do not forget about Bootstrap-related stuff for later refactoring.

**Review by farmakiG — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/872)* status: all files reviewed, 2 unresolved discussions (waiting on @mchudy-fujitsu)

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/872)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal/WebContent/css/mpOverrides.css, line 74 at r1](https://reviewable.io/reviews/servicecatalog/oscm/872#-M8A_2N3BswgoUrXDzlv:-M8AdYvq4TBRp4oKNZAe:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/9d070750fe82638f74c3d5587eb743c0887dad5e/oscm-portal/WebContent/css/mpOverrides.css#L74)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Add comment about "Bootstrap suspended message" so that we do not forget about Bootstrap-related stuff for later refactoring.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/playground/subscriptions/priceModelDetails.xhtml, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm/872#-M8AZLhk5xAa-GOUHU_e:-M8AboB_2ljd6VP16dDk:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/9d070750fe82638f74c3d5587eb743c0887dad5e/oscm-portal/WebContent/marketplace/playground/subscriptions/priceModelDetails.xhtml#L1)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Remove empty line.
</blockquote></details>

Done.

**Review by farmakiG — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/872)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
