### PR TITLE
Task#1209 font awesome instead of png icon

### LINKED ISSUE #1209: Font Awesome instead of png icon
**Summary**
Due to the difficult customization of png graphics, we should replace the icons with the Font Awesome font 

**Details**
In png graphics, it's hard to change their color, they also behave better on responsive pages 

**Acceptance criteria**
Wherever it is easy to convert, convert png graphics to Font Awesome 

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Change png graphic (edit, sort) to Font Awesome

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**
image

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1213)

### CODE REVIEW

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/account/paymentTypes.xhtml, line 72 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1213#-MVzYAN-8FLDUfIS_kTP:-MVzYAN00sJ4If2tejgF:b9z83h1) ([raw file](https://github.com/servicecatalog/oscm/blob/51e239f06c90bd424fdcd556720e3c4b85a6f4b5/oscm-portal/WebContent/marketplace/account/paymentTypes.xhtml#L72)):*
> ```HTML
>                              layout="block"
>                              rendered="#{paymentInfoBean.collectionTypePSP eq paymentInfo.paymentType.collectionType}">
>               id="editPaymentImage#{index}"
> ```

I guess here you have a typing error?

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/customBootstrap/scss/_customVariables.scss, line 195 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1213#-MVzZo373bg2bOndlHtY:-MVzZo384rGc09WpMDw1:b-3iithp) ([raw file](https://github.com/servicecatalog/oscm/blob/51e239f06c90bd424fdcd556720e3c4b85a6f4b5/oscm-portal/WebContent/marketplace/customBootstrap/scss/_customVariables.scss#L195)):*
> ```SCSS
>   color:                               var(--oscm-rv-color) !important;
>   opacity: 1;
> }
> ```

Please explain why the bg-color and color for disabled/readonly form controls is the --oscm-input-color?

**Review by farmakiG — COMMENTED** [review]
> Reviewed 17 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1213)* status: 17 of 18 files reviewed, 2 unresolved discussions (waiting on @KabacinskiPiotr)

**Comment by Piotr-K8i** [comment]
___
*[oscm-portal/WebContent/marketplace/customBootstrap/scss/_customVariables.scss, line 195 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1213#-MVzZo373bg2bOndlHtY:-MVzae72DbFeTOd-XCfH:bfl7d76) ([raw file](https://github.com/servicecatalog/oscm/blob/51e239f06c90bd424fdcd556720e3c4b85a6f4b5/oscm-portal/WebContent/marketplace/customBootstrap/scss/_customVariables.scss#L195)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Please explain why the bg-color and color for disabled/readonly form controls is the --oscm-input-color?
</blockquote></details>

Because when the input is disabled I would to keep it as similar way but with opacity. SO for example in dark theme I would have input background in dark color and color font white. Without this changes in dark theme I got white background in input when it is disabled

**Review by Piotr-K8i — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1213)* status: 16 of 18 files reviewed, 2 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal/WebContent/marketplace/account/paymentTypes.xhtml, line 72 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1213#-MVzYAN-8FLDUfIS_kTP:-MVzsVnC8pqGcFaHpJ6g:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/51e239f06c90bd424fdcd556720e3c4b85a6f4b5/oscm-portal/WebContent/marketplace/account/paymentTypes.xhtml#L72)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

I guess here you have a typing error?
</blockquote></details>

Done.

**Comment by farmakiG** [comment]
Close this PR as it is not necessary to use font awesome instead of png icon.

**Pull request closed without merging**
