### PR TITLE
Fix #833 - add scss folder.

### LINKED ISSUE #833: [Customization]Load Custom bootstrap css.
**Summary**
Add a new method in brandingBean to load a customBootstrap.css instead of bootstrap(or just the theme.css without the bootstrap compiled version).

**Details**
Provide the choice to the customer to load a custom bootsrap css. Give input for documentation with a final comment in this issue.

**Acceptance criteria**
- [ ] Manual Tests for the loaded version.
- [ ] Small UI test.
- [ ] Documentation input is given 

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- included scss folder in branding package. 

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**
- add a screenshot illustrating your change

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/995)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/995)* status: all files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-portal/package.properties, line 6 at r1](https://reviewable.io/reviews/servicecatalog/oscm/995#-MB4EGv62S9UiYdaf_3O:-MB4EGv62S9UiYdaf_3P:bsug8e) ([raw file](https://github.com/servicecatalog/oscm/blob/8ed4b06724500944b2a9f0833e733ca1429bc2ac/oscm-portal/package.properties#L6)):*
> ```INI
> branding-package.zip@css = ${project.dir}/WebContent/marketplace/css[**/*]
> branding-package.zip@scss = ${project.dir}/WebContent/marketplace/scss[*.scss]
> branding-package.zip@fonts = ${project.dir}/WebContent/marketplace/fonts[**/*]
> ```

I think we should include also the /WebContent/marketplace/scss/README.md here

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/995)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-portal/package.properties, line 6 at r1](https://reviewable.io/reviews/servicecatalog/oscm/995#-MB4EGv62S9UiYdaf_3O:-MB4NDTLBEM4ZN4_sGn0:b-srh2u9) ([raw file](https://github.com/servicecatalog/oscm/blob/8ed4b06724500944b2a9f0833e733ca1429bc2ac/oscm-portal/package.properties#L6)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

I think we should include also the /WebContent/marketplace/scss/README.md here
</blockquote></details>

Ok. So should I include this README exactly as it is?

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/995)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/995)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
