### PR TITLE
Bootstrap nav sidebar

### LINKED ISSUE #769: Replace Navigation Menu for Account MP page.
**Summary**
The tag "navigationMenu" should be replaced with a responsive one.

**Details**
The layout of the responsive navigation menu will be the same as before, appearing to the left of the account page. The only difference is that it will be a responsive one.

**Acceptance criteria**
- [ ] The navigation menu of the Account menu is replaced by a Bootstrap navigation menu. Layout and functionality should remain as before.

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- Added new Bootstrap "Account" Navigation menu.

**Mandatory checks:**
- [X] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [X] changes were tested manually
- [ ] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [X] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [Docker_OSCM/job/OSCM_Docker_Build_and_push/653/]
- [Docker_OSCM/job/OSCM_Docker_pull_and_start/1033/]

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/811)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/811)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @farmakiG and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/playground.xhtml, line 29 at r2](https://reviewable.io/reviews/servicecatalog/oscm/811#-M5b6yKT3rWvc_rqABmn:-M5b6yKUC4YARExbj2Vr:bcmwg22) ([raw file](https://github.com/servicecatalog/oscm/blob/7e1dc0fd79779ad0e7c8ba3414b5a636659ab8f6/oscm-portal/WebContent/marketplace/playground.xhtml#L29)):*
> ```HTML
>     </a4j:outputPanel>
>   </ui:define> -->
> ```

Why is this commented?
___
*[oscm-portal/WebContent/marketplace/playgroundServices.xhtml, line 28 at r2](https://reviewable.io/reviews/servicecatalog/oscm/811#-M5b7EjzCWONBreLeQ58:-M5b7Ek-3rA6Orc2MszK:b-89a4rb) ([raw file](https://github.com/servicecatalog/oscm/blob/7e1dc0fd79779ad0e7c8ba3414b5a636659ab8f6/oscm-portal/WebContent/marketplace/playgroundServices.xhtml#L28)):*
> ```HTML
>       <mp:tagCloud bean="#{tagCloudBean}" />
>     </a4j:outputPanel>
>   </ui:define>  --> 
> ```

Dito.
___
*[oscm-portal/WebContent/marketplace/templates/headBootstrap.xhtml, line 37 at r2](https://reviewable.io/reviews/servicecatalog/oscm/811#-M5b83CL2SCk0IA0jZ10:-M5b7pRMCnY6pimHDCoq:b-8vwoz3) ([raw file](https://github.com/servicecatalog/oscm/blob/7e1dc0fd79779ad0e7c8ba3414b5a636659ab8f6/oscm-portal/WebContent/marketplace/templates/headBootstrap.xhtml#L37)):*
> ```HTML
>     type="text/css" />
>     
>   <link href="#{sessionBean.marketplaceBrandUrl}" rel="stylesheet" type="text/css" media="screen,projection,print" />
> ```

Why did you add this a second time? This is duplicate with line below.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/playground.xhtml, line 29 at r2](https://reviewable.io/reviews/servicecatalog/oscm/811#-M5b6yKT3rWvc_rqABmn:-M5bOOZaCb6rNrZcgqBy:b-b1895j) ([raw file](https://github.com/servicecatalog/oscm/blob/7e1dc0fd79779ad0e7c8ba3414b5a636659ab8f6/oscm-portal/WebContent/marketplace/playground.xhtml#L29)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Why is this commented?
</blockquote></details>

Tags and categories have been implemented already directly inside the container, not inside the aside menu (probably for responsiveness). I commented it, because I do not know if it is still necessary to replace them inside the aside div? If clarified, I will remove the comments.

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/811)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @farmakiG, @GoebelL, and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/templates/headBootstrap.xhtml, line 37 at r2](https://reviewable.io/reviews/servicecatalog/oscm/811#-M5b83CL2SCk0IA0jZ10:-M5bNoMFDqciUGGFFSlO:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/7e1dc0fd79779ad0e7c8ba3414b5a636659ab8f6/oscm-portal/WebContent/marketplace/templates/headBootstrap.xhtml#L37)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Why did you add this a second time? This is duplicate with line below. 
</blockquote></details>

Done.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/playgroundServices.xhtml, line 28 at r2](https://reviewable.io/reviews/servicecatalog/oscm/811#-M5b7EjzCWONBreLeQ58:-M5fYQvc46sLTcbvMcsP:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/7e1dc0fd79779ad0e7c8ba3414b5a636659ab8f6/oscm-portal/WebContent/marketplace/playgroundServices.xhtml#L28)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Dito.
</blockquote></details>

Done.

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/811)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @GoebelL and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/playground.xhtml, line 29 at r2](https://reviewable.io/reviews/servicecatalog/oscm/811#-M5b6yKT3rWvc_rqABmn:-M5fYURx0DGIuh63xccY:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/7e1dc0fd79779ad0e7c8ba3414b5a636659ab8f6/oscm-portal/WebContent/marketplace/playground.xhtml#L29)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Tags and categories have been implemented already directly inside the container, not inside the aside menu (probably for responsiveness). I commented it, because I do not know if it is still necessary to replace them inside the aside div? If clarified, I will remove the comments.
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/811)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mchudy-fujitsu)

**Pull request merged**
