### PR TITLE
Issue/task 1220 UI tests

### LINKED ISSUE #1219: Set Theme Colors at runtime
**Summary**
Set the basic theme colors at the Profile page. These are: 

1) the primary color, 
2) the theme-background-color 
3) the theme-background-color for input fields, 
4) the theme-foreground-color, 
5) the navigation background color and 
6) the navigation foreground color.

**Details**
List of :root variables that must be affected:

- --oscm-primary: primary color
- --oscm-main: background color
-  --oscm-main-input-color: background color for input fields.
- --oscm-main-font-color: foreground color for text
- --oscm-navbar-color: background color for navigation
- --oscm-navbar-links-color: foreground color for navigation

**Acceptance criteria**
- [ ] All above colors are updated in the UI upon click of "Save" in the Profile page
- [ ] UI Tests
- [ ] UI Screenshots
- [ ] UI Customizability is preserved

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- UI Tests for saving all colors of "Profile" page: primary color, font color, navbar bg, navbar link color, input bg color.
- Check successful message and verification of saved values of the colors.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [X] Webtests are successful

**To be checked by the reviewer:**
- [X] Clean Java code and unit tested changes 
- [X] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**
- add a screenshot illustrating your change

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1230)

### CODE REVIEW

**Review by Piotr-K8i — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1230)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-ui-tests/src/main/java/org/oscm/webtest/WebTester.java, line 310 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1230#-MX1oqxBE8cS-HS7L3wU:-MX1oqxC1iFpi2V4bAsw:b-qhlorm) ([raw file](https://github.com/servicecatalog/oscm/blob/aff639697708cc104b5531808c90a40cce3f523b/oscm-ui-tests/src/main/java/org/oscm/webtest/WebTester.java#L310)):*
> ```Java
>       WebElement colorElement = driver.findElement(By.id(id));
>       setAttribute(colorElement, value);
>     } catch (StaleElementReferenceException e) {
> ```

Add an error log with a description of what happened here

**Comment by farmakiG** [comment]
___
*[oscm-ui-tests/src/main/java/org/oscm/webtest/WebTester.java, line 310 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1230#-MX1oqxBE8cS-HS7L3wU:-MX1t7yrC_0GqU4VVOxR:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/aff639697708cc104b5531808c90a40cce3f523b/oscm-ui-tests/src/main/java/org/oscm/webtest/WebTester.java#L310)):*
<details><summary><i>Previously, KabacinskiPiotr wrote…</i></summary><blockquote>

Add an error log with a description of what happened here 
</blockquote></details>

Done.

**Review by farmakiG — COMMENTED** [review]
> Dismissed @KabacinskiPiotr from a discussion.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1230)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @farmakiG)

___
*[oscm-ui-tests/src/main/java/org/oscm/webtest/WebTester.java, line 310 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1230#-MX1oqxBE8cS-HS7L3wU:-MX1tAJyBvPTOfhSG3U0:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/aff639697708cc104b5531808c90a40cce3f523b/oscm-ui-tests/src/main/java/org/oscm/webtest/WebTester.java#L310)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by Piotr-K8i — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1230)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @farmakiG)

**Review by farmakiG — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1230#-:-MX26ggt0fZib3TCDD4r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @farmakiG)

**Pull request merged**
