### PR TITLE
Minor style polish

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
* Added link-active color for Dropdowns.
* added rounded button for Subscription Search.
* added green border-color for input focus.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**
Screenshot_2020-05-27 Marketplace
GreenActiveLinke

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/882)

### CODE REVIEW

**Review by GoebelL — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/882)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by farmakiG — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/882#-:-M8PPU7-BKv7ELVNjTU5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by farmakiG — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/882#-:-M8PPZmuA3KSvPW5lXq0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mchudy-fujitsu — COMMENTED** [review]
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/882)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mchudy-fujitsu — DISMISSED** [review]

**Review by mchudy-fujitsu — APPROVED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/882)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
