### PR TITLE
Get Bulk images

### LINKED ISSUE #1028: Transparent image background
**Version Info**
OSCM v19

**Describe the bug**
If service image is defined with transparency the placeholder image appears in the background. The placeholder should only appear if no service image is defined.

**How to Reproduce**
1. Create marketable service with service image that has transparent background
2. Publish the service and view it in the marketplace portal

**Observed behavior**
Placeholder image appear is as background 

**Expected behavior**
No placeholder, just transparent background.

**Screenshots**
image

**Additional context**
Ask me

### PR DESCRIPTION
**Pull request by cworf91**
**Changes in this Pull Request:**
- Implements bulk image reader

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [x] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1040)

### CODE REVIEW

**Review by GoebelL — DISMISSED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1040)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by farmakiG** [comment]
___
*[oscm-portal/javasrc/org/oscm/ui/model/ServiceWithImage.java, line 50 at r3](https://reviewable.io/reviews/servicecatalog/oscm/1040#-MDt4nuBCGoPMCTm9zMk:-MDt4nuBCGoPMCTm9zMl:bvze0ed) ([raw file](https://github.com/servicecatalog/oscm/blob/459cafa8c81b50bb081bfc4cf12a49c2690f7245/oscm-portal/javasrc/org/oscm/ui/model/ServiceWithImage.java#L50)):*
> ```Java
> 
>   public void setImageContent(String imageContent) {
>     this.imageContent = imageContent;
> ```

Ich würde lieber im Constructor nur den VO img setzen, und den Code: this.imageContent  = "..." in dem setter umziehen, und im Constructor nur setImageContent(vo img) rufen.

**Comment by farmakiG** [comment]
___
*[oscm-internal/javasrc/org/oscm/internal/portallandingpage/LandingpageServiceBean.java, line 3 at r3](https://reviewable.io/reviews/servicecatalog/oscm/1040#-MDt5Vx27fsVG4v0yyMD:-MDt5Vx33fwTms9VKTFp:b84yaui) ([raw file](https://github.com/servicecatalog/oscm/blob/42834383a7aab7cf77b7c309e9c153fab89eca77/oscm-internal/javasrc/org/oscm/internal/portallandingpage/LandingpageServiceBean.java#L3)):*
> ```Java
> /*******************************************************************************
>  *  Copyright FUJITSU LIMITED 2018
>  *******************************************************************************/
> ```

Copyright has been misplaced.

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1040)* status: 0 of 31 files reviewed, 2 unresolved discussions (waiting on @farmakiG and @GoebelL)

___
*[oscm-internal/javasrc/org/oscm/internal/portallandingpage/LandingpageServiceBean.java, line 3 at r3](https://reviewable.io/reviews/servicecatalog/oscm/1040#-MDt5Vx27fsVG4v0yyMD:-MDtEGpM7QeF7ldk97vu:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/42834383a7aab7cf77b7c309e9c153fab89eca77/oscm-internal/javasrc/org/oscm/internal/portallandingpage/LandingpageServiceBean.java#L3)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Copyright has been misplaced.
</blockquote></details>

Done.
___
*[oscm-portal/javasrc/org/oscm/ui/model/ServiceWithImage.java, line 50 at r3](https://reviewable.io/reviews/servicecatalog/oscm/1040#-MDt4nuBCGoPMCTm9zMk:-MDtEIEd0wZLq-51JQZF:b-cooqt9) ([raw file](https://github.com/servicecatalog/oscm/blob/459cafa8c81b50bb081bfc4cf12a49c2690f7245/oscm-portal/javasrc/org/oscm/ui/model/ServiceWithImage.java#L50)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Ich würde lieber im Constructor nur den VO img setzen, und den Code: this.imageContent  = "..." in dem setter umziehen, und im Constructor nur setImageContent(vo img) rufen.
</blockquote></details>

As discussed, that could causes unexpectet problems.

**Review by farmakiG — APPROVED** [review]
> Reviewed 27 of 32 files at r2, 6 of 6 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1040)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
