### PR TITLE
Bug/faulty code formatter

### LINKED ISSUE #264: Google code formatter behaves not as expected
**Version Info**
Latest

**Describe the bug**
Automatic google code formatter is not working as expected.

**How to Reproduce**
1. Check the commits: https://github.com/servicecatalog/oscm/commits/task/synchronize_credentials
2. No code formatting after https://github.com/servicecatalog/oscm/commit/9a563f0bfaca9cfc5660e0d816f7e3b32d64cb7e
3.  Strange behaviour in comit: https://github.com/servicecatalog/oscm/commit/6be5a94d883b08442103b933828c41b2dbd04088

**Observed behavior**
Formatter did not format the code nor add the header (pasted java code instead)

**Expected behavior**
Formatter only formats the code and add missing header.

**Screenshots**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by adamczykba**
**Changes in this PR**
- fixed the issue, where formatter didn't work for the first commit in new branch
- fixed the issue where another file was appended at top of the formatted one - instead of copyright clause

**Proposed test scenarios:**
- branch out from source, create new java files and check if they are formatted properly
- branch out from source, modify some java files and check if they are formatted properly
- branch out from source, create or modify some non-java files and check if they are intact

Closes #264

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/269)

### CODE REVIEW

**Review by Crystalzord — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/269)* status: all files reviewed, 3 unresolved discussions (waiting on @adamczykba and @kowalczyka)

___
*[scripts/check_copyrights.sh, line 3 at r1](https://reviewable.io/reviews/servicecatalog/oscm/269#-Lbhk7CX8rQ2CYCUmoVZ:-Lbhk7CX8rQ2CYCUmoV_:b8e3xac) ([raw file](https://github.com/servicecatalog/oscm/blob/81acd474d9dc0d1b68a914aeacf855946c1ee6de/scripts/check_copyrights.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> 
> determine_files_to_process () {
> ```

Since You use this function 3 times, I propose to create a common.sh file with the function implementation and just import it to prevent redundancy.

example: https://github.com/servicecatalog/oscm-app-shell/blob/master/src/main/resources/sample_scripts/advanced_scripts/operation.sh#L5
___
*[scripts/format_code.sh, line 3 at r1](https://reviewable.io/reviews/servicecatalog/oscm/269#-LbhjdHR460hyzad8l9Z:-LbhjdHR460hyzad8l9_:b-7ropln) ([raw file](https://github.com/servicecatalog/oscm/blob/81acd474d9dc0d1b68a914aeacf855946c1ee6de/scripts/format_code.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> 
> determine_files_to_process () {
> ```

ditto
___
*[scripts/repush_formatted_code.sh, line 3 at r1](https://reviewable.io/reviews/servicecatalog/oscm/269#-Lbhk3hm8zqCJ4WHPe0X:-Lbhk3hm8zqCJ4WHPe0Y:b-7ropln) ([raw file](https://github.com/servicecatalog/oscm/blob/81acd474d9dc0d1b68a914aeacf855946c1ee6de/scripts/repush_formatted_code.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> 
> determine_files_to_process () {
> ```

ditto

**Review by adamczykba — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/269)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @Crystalzord and @kowalczyka)

___
*[scripts/check_copyrights.sh, line 3 at r1](https://reviewable.io/reviews/servicecatalog/oscm/269#-Lbhk7CX8rQ2CYCUmoVZ:-LbhwiBVAX9H6GOIa6l6:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/81acd474d9dc0d1b68a914aeacf855946c1ee6de/scripts/check_copyrights.sh#L3)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

Since You use this function 3 times, I propose to create a common.sh file with the function implementation and just import it to prevent redundancy.

example: https://github.com/servicecatalog/oscm-app-shell/blob/master/src/main/resources/sample_scripts/advanced_scripts/operation.sh#L5
</blockquote></details>

Done.
___
*[scripts/format_code.sh, line 3 at r1](https://reviewable.io/reviews/servicecatalog/oscm/269#-LbhjdHR460hyzad8l9Z:-LbhwjDu1kF8xtZ4xpji:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/81acd474d9dc0d1b68a914aeacf855946c1ee6de/scripts/format_code.sh#L3)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[scripts/repush_formatted_code.sh, line 3 at r1](https://reviewable.io/reviews/servicecatalog/oscm/269#-Lbhk3hm8zqCJ4WHPe0X:-Lbhwjvz1L0pHfQ4Ds42:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/81acd474d9dc0d1b68a914aeacf855946c1ee6de/scripts/repush_formatted_code.sh#L3)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by Crystalzord — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/269)* status: all files reviewed, 3 unresolved discussions (waiting on @adamczykba and @kowalczyka)

___
*[scripts/common.sh, line 5 at r2](https://reviewable.io/reviews/servicecatalog/oscm/269#-LcGSc3_EUdriMBnam-W:-LcGSc3a6IIE1BBwmhZ4:b7uwkre) ([raw file](https://github.com/servicecatalog/oscm/blob/29c15fb0c0a65047e6cb5eb283526b13fd84681d/scripts/common.sh#L5)):*
> ```Shell
> determine_files_to_process () {
>     if [[ ! -z "$TRAVIS_COMMIT_RANGE" ]] ; then
>         GIT_DIFF_OUTPUT=$(git diff --stat --name-only $(echo "$TRAVIS_COMMIT_RANGE") | grep "\.java$")
> ```

You do not need to use $(echo "$VARIABLE"). Just use $VARIABLE instead.
example: GIT_DIFF_OUTPUT=$(git diff-tree --no-commit-id --name-only -r $TRAVIS_COMMIT | grep "\.java$")
___
*[scripts/common.sh, line 7 at r2](https://reviewable.io/reviews/servicecatalog/oscm/269#-LcGQOfY0wYPhqfhVbRF:-LcGQOfY0wYPhqfhVbRG:b-7ropln) ([raw file](https://github.com/servicecatalog/oscm/blob/29c15fb0c0a65047e6cb5eb283526b13fd84681d/scripts/common.sh#L7)):*
> ```Shell
>         GIT_DIFF_OUTPUT=$(git diff --stat --name-only $(echo "$TRAVIS_COMMIT_RANGE") | grep "\.java$")
>     else
>         GIT_DIFF_OUTPUT=$(git diff-tree --no-commit-id --name-only -r $(echo "$TRAVIS_COMMIT") | grep "\.java$")
> ```

ditto
___
*[scripts/format_code.sh, line 12 at r2](https://reviewable.io/reviews/servicecatalog/oscm/269#-LcGTvttADA5meHgvU1Q:-LcGTvtv8V61EwWVsunq:bs2m42k) ([raw file](https://github.com/servicecatalog/oscm/blob/29c15fb0c0a65047e6cb5eb283526b13fd84681d/scripts/format_code.sh#L12)):*
> ```Shell
>     if [ ! -f libraries/google-java-format.jar ] ; then 
>         curl -o libraries/google-java-format.jar http://central.maven.org/maven2/com/google/googlejavaformat/google-java-format/1.7/google-java-format-1.7-all-deps.jar
>         chmod 755 libraries/google-java-format.jar
> ```

is it necessary to make the .jar file executable if it is run by java command?

**Review by adamczykba — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/269)* status: all files reviewed, 3 unresolved discussions (waiting on @Crystalzord and @kowalczyka)

___
*[scripts/common.sh, line 5 at r2](https://reviewable.io/reviews/servicecatalog/oscm/269#-LcGSc3_EUdriMBnam-W:-LcGUvRd8CIMLhbsF-Tp:b-b7dr5x) ([raw file](https://github.com/servicecatalog/oscm/blob/29c15fb0c0a65047e6cb5eb283526b13fd84681d/scripts/common.sh#L5)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

You do not need to use $(echo "$VARIABLE"). Just use $VARIABLE instead.
example: GIT_DIFF_OUTPUT=$(git diff-tree --no-commit-id --name-only -r $TRAVIS_COMMIT | grep "\.java$")
</blockquote></details>

Actually using VAR without wrapping it in echo caused some errors - therefore echo is used
___
*[scripts/common.sh, line 7 at r2](https://reviewable.io/reviews/servicecatalog/oscm/269#-LcGQOfY0wYPhqfhVbRF:-LcGV3jmEVSRvOLhE5KS:b-7ropln) ([raw file](https://github.com/servicecatalog/oscm/blob/29c15fb0c0a65047e6cb5eb283526b13fd84681d/scripts/common.sh#L7)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[scripts/format_code.sh, line 12 at r2](https://reviewable.io/reviews/servicecatalog/oscm/269#-LcGTvttADA5meHgvU1Q:-LcGVBHT4WdXmbmy4Nx7:box6vjd) ([raw file](https://github.com/servicecatalog/oscm/blob/29c15fb0c0a65047e6cb5eb283526b13fd84681d/scripts/format_code.sh#L12)):*
<details><summary><i>Previously, Crystalzord (Lukasz Wiecek) wrote…</i></summary><blockquote>

is it necessary to make the .jar file executable if it is run by java command?
</blockquote></details>

Without it, error about script being unable to access the jar was being thrown

**Review by Crystalzord — APPROVED** [review]

**Review by adamczykba — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/269#-:-LcGe29K354rfTkZ1NNo:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Crystalzord and @kowalczyka)

**Review by Crystalzord — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/269)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
