### PR TITLE
List group custom colors

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- Added darker and lighter shades of colors for list-group-item (active,hover and default).
-For this purpose added a class list-group-item-custom.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell
ci6: farmaki

**Screenshot (if applicable):**
Screenshot_2020-06-23 Marketplace

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/945)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/945)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @GoebelL)

___
*[oscm-portal/WebContent/customBootstrap/scss/_myvariables.scss, line 4 at r2](https://reviewable.io/reviews/servicecatalog/oscm/945#-MA_NSbFBedQBYlQj064:-MA_NSbG13UZ_zmlAdOd:b-y54g1s) ([raw file](https://github.com/servicecatalog/oscm/blob/acef911a51305614f5e559e7cbb73808a2de9cb7/oscm-portal/WebContent/customBootstrap/scss/_myvariables.scss#L4)):*
> ```SCSS
> 
> $main-color: #f0c105;
> ```

For this default, let's leave it $green.
Not necessary to check in this yellow branding. Just the "tools" are needed to make the tab colors customizable.

**Review by GoebelL — DISMISSED** [review]
> Reviewed 1 of 4 files at r2, 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/945)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-portal/WebContent/customBootstrap/scss/_myvariables.scss, line 22 at r2](https://reviewable.io/reviews/servicecatalog/oscm/945#-MA_SuR0-jxaUJViDmn-:-MA_SuR158NNnoM56oGK:b-f5jp9d) ([raw file](https://github.com/servicecatalog/oscm/blob/acef911a51305614f5e559e7cbb73808a2de9cb7/oscm-portal/WebContent/customBootstrap/scss/_myvariables.scss#L22)):*
> ```SCSS
> 
> $lightened-color: lighten(desaturate($secondary, 0.03), 23.33);
> ```

#FCE070

**Review by GoebelL — COMMENTED** [review]
> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/945)* status: all files reviewed, 1 unresolved discussion (waiting on @farmakiG)

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/945)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-portal/WebContent/customBootstrap/scss/_myvariables.scss, line 22 at r2](https://reviewable.io/reviews/servicecatalog/oscm/945#-MA_SuR0-jxaUJViDmn-:-MA_nwZe6Y_0kgQCsyNx:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/acef911a51305614f5e559e7cbb73808a2de9cb7/oscm-portal/WebContent/customBootstrap/scss/_myvariables.scss#L22)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

#FCE070  
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/945)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
