### PR TITLE
Bug#1149 Content outside the table

### LINKED ISSUE #1149: Content outside the table
**Version Info**
19.1

**Describe the bug**
Content outside the table. See screenshot

**How to Reproduce**
1. Create service which contains parameter with valueType="ENUMERATION"
2. Go to marketplace
3. Start subscribe the service

**Observed behavior**
Content outside the table. See screenshot

**Expected behavior**
Content should be placed next to radio button

**Screenshots**

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Fix table style

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**
image

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1150)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1150)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)

___
*[oscm-portal/WebContent/marketplace/account/paramtable.xhtml, line 121 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1150#-MQHcALH5AfSdD98byeI:-MQHcALH5AfSdD98byeJ:b-jn7ksh) ([raw file](https://github.com/servicecatalog/oscm/blob/0f677e3183407e2ae08d5a1fce62034113bb4877/oscm-portal/WebContent/marketplace/account/paramtable.xhtml#L121)):*
> ```HTML
>           <c:set var="style" value="margin-right:4px;" />
>           <ui:fragment rendered="#{row.parameterOption.optionId == row.parameter.value and readOnly}">
>             <input type="radio" id="#{radioId}" name="#{row.parameterOption.paramDefId}"
> ```

No. Please don't remove classes for marketplace customization. The class tableParameter has been added in 19.0 with intension to style the parameter input fields. The layout bug doesn't exist in a version from 25th november. It has been introduced very recently. 
Please first find from recent changes (e.g. maybe in mp.scss) what has caused this layout issue.

**Comment by Piotr-K8i** [comment]
> > _[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1150)_ status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)
> 
> _[oscm-portal/WebContent/marketplace/account/paramtable.xhtml, line 121 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1150#-MQHcALH5AfSdD98byeI:-MQHcALH5AfSdD98byeJ:b-jn7ksh) ([raw file](https://github.com/servicecatalog/oscm/blob/0f677e3183407e2ae08d5a1fce62034113bb4877/oscm-portal/WebContent/marketplace/account/paramtable.xhtml#L121)):_
> 
> > ```
> >           <c:set var="style" value="margin-right:4px;" />
> >           <ui:fragment rendered="#{row.parameterOption.optionId == row.parameter.value and readOnly}">
> >             <input type="radio" id="#{radioId}" name="#{row.parameterOption.paramDefId}"
> > ```
> 
> No. Please don't remove classes for marketplace customization. The class tableParameter has been added in 19.0 with intension to style the parameter input fields. The layout bug doesn't exist in a version from 25th november. It has been introduced very recently.
> Please first find from recent changes (e.g. maybe in mp.scss) what has caused this layout issue.

**tableParameter** had no effect before here, after removing _width: 2rem!important;_ from input[type="radio"] has started affecting on this radio button

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1150)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)

___
*[oscm-portal/WebContent/marketplace/account/paramtable.xhtml, line 121 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1150#-MQUIlKB9DBuP4HPrmD0:-MQUIlKC97GWAKllz-XT:bp0c07t) ([raw file](https://github.com/servicecatalog/oscm/blob/98b8a8f16265e52f3c312a517b278f22ad24e20b/oscm-portal/WebContent/marketplace/account/paramtable.xhtml#L121)):*
> ```HTML
>           <c:set var="style" value="margin-right:4px;" />
>           <ui:fragment rendered="#{row.parameterOption.optionId == row.parameter.value and readOnly}">
>             <input class="tableParameter" type="radio" id="#{radioId}" name="#{row.parameterOption.paramDefId}"
> ```

Again, this content class is intended and needed for custom styling of input parameters. Removing it will break our customer brandings. So, please don't remove this.

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1150)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)

___
*[oscm-portal/WebContent/marketplace/account/paramtable.xhtml, line 121 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1150#-MQUIlKB9DBuP4HPrmD0:-MQUK4LL4w7-pCLZacMu:b-ou1vz3) ([raw file](https://github.com/servicecatalog/oscm/blob/98b8a8f16265e52f3c312a517b278f22ad24e20b/oscm-portal/WebContent/marketplace/account/paramtable.xhtml#L121)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Again, this content class is intended and needed for custom styling of input parameters. Removing it will break our customer brandings. So, please don't remove this. 
</blockquote></details>

We have several OSCM content related classes. Please first ask in slack before you remove them.

**Review by Piotr-K8i — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1150)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @GoebelL)

___
*[oscm-portal/WebContent/marketplace/account/paramtable.xhtml, line 121 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1150#-MQUIlKB9DBuP4HPrmD0:-MQpuKoH8mN5NMaoPved:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/98b8a8f16265e52f3c312a517b278f22ad24e20b/oscm-portal/WebContent/marketplace/account/paramtable.xhtml#L121)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

We have several OSCM content related classes. Please first ask in slack before you remove them.
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1150)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @farmakiG)

**Pull request merged**
