### PR TITLE
[Subscription UI] Configuration tab

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
-  Created new configuration tab in subscription details page.

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [x] .MASTER/job/BES_MASTER_IT/
- [x] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [x] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [x] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
N/A

**Screenshot (if applicable):**

modal 4
FireShot Capture 084 - Marketplace - 10 140 18 99
FireShot Capture 085 - Marketplace - 10 140 18 99
moda 3
modal 1
modal 2

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/playground/account/subscriptionDetails.xhtml, line 370 at r1](https://reviewable.io/reviews/servicecatalog/oscm/885#-M8PobGtAvRGWYW1zeC2:-M8PobGv9Jtl9kKR-7nl:b-9yvwx1) ([raw file](https://github.com/servicecatalog/oscm/blob/0feb51d0245e35a10d84fbc50fedfaa9296e0774/oscm-portal/WebContent/marketplace/playground/account/subscriptionDetails.xhtml#L370)):*
> ```HTML
>                   </div>
>                 </h:form>
>                 <script type="text/javascript">
> ```

Is this set focus code not needed here? Or is the the focus correctly set to subscription name field when the the view is opened?

**Review by GoebelL — COMMENTED** [review]
> Reviewed 4 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)* status: all files reviewed, 1 unresolved discussion (waiting on @farmakiG and @mchudy-fujitsu)

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 4443 at r1](https://reviewable.io/reviews/servicecatalog/oscm/885#-M8PyIt-5Fv2KBW35ckj:-M8PyIt0CCBBzYZcENYH:b-veeikz) ([raw file](https://github.com/servicecatalog/oscm/blob/0feb51d0245e35a10d84fbc50fedfaa9296e0774/oscm-portal/WebContent/marketplace/css/mp.css#L4443)):*
> ```CSS
> ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----  */
> 
> .table-radio tbody tr {
> ```

Please use another class name for the rich:column, so that we do not confuse with the Bootstrap table classes (.table, .table-striped, .table-hover etc). Also, please move this section to the chapter for tables.

**Review by farmakiG — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)* status: all files reviewed, 3 unresolved discussions (waiting on @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/playground/organizationUnitPanel.xhtml, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm/885#-M8Pygn2AWjmQqGAYRTV:-M8Pygn2AWjmQqGAYRTW:b-7mo7f4) ([raw file](https://github.com/servicecatalog/oscm/blob/0feb51d0245e35a10d84fbc50fedfaa9296e0774/oscm-portal/WebContent/marketplace/playground/organizationUnitPanel.xhtml#L1)):*
> ```HTML
> 
> ```

Remove empty line.

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)* status: all files reviewed, 3 unresolved discussions (waiting on @farmakiG and @GoebelL)

___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 4443 at r1](https://reviewable.io/reviews/servicecatalog/oscm/885#-M8PyIt-5Fv2KBW35ckj:-M8TYGDa2mvDdasLVuIq:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/0feb51d0245e35a10d84fbc50fedfaa9296e0774/oscm-portal/WebContent/marketplace/css/mp.css#L4443)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Please use another class name for the rich:column, so that we do not confuse with the Bootstrap table classes (.table, .table-striped, .table-hover etc). Also, please move this section to the chapter for tables.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/playground/organizationUnitPanel.xhtml, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm/885#-M8Pygn2AWjmQqGAYRTV:-M8TYXANAS4A1INFVOO8:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/0feb51d0245e35a10d84fbc50fedfaa9296e0774/oscm-portal/WebContent/marketplace/playground/organizationUnitPanel.xhtml#L1)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Remove empty line.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/playground/account/subscriptionDetails.xhtml, line 370 at r1](https://reviewable.io/reviews/servicecatalog/oscm/885#-M8PobGtAvRGWYW1zeC2:-M8TZexb5G5YxP3OkIhr:b-bvwhm5) ([raw file](https://github.com/servicecatalog/oscm/blob/0feb51d0245e35a10d84fbc50fedfaa9296e0774/oscm-portal/WebContent/marketplace/playground/account/subscriptionDetails.xhtml#L370)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Is this set focus code not needed here? Or is the the focus correctly set to subscription name field when the the view is opened?
</blockquote></details>

Restored.

**Review by farmakiG — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)* status: all files reviewed, 2 unresolved discussions (waiting on @farmakiG and @GoebelL)

**Review by farmakiG — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by farmakiG — DISMISSED** [review]
> Reviewed 4 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by GoebelL — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Piotr-K8i — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)* status: all files reviewed, 1 unresolved discussion (waiting on @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/playground/organizationUnitPanel.xhtml, line 89 at r2](https://reviewable.io/reviews/servicecatalog/oscm/885#-M8nvIyE3xC5YnMu_FaY:-M8nvIyE3xC5YnMu_FaZ:b-1a0xiq) ([raw file](https://github.com/servicecatalog/oscm/blob/420c8b7d23c0e01d5331906ab331059350e8a21e/oscm-portal/WebContent/marketplace/playground/organizationUnitPanel.xhtml#L89)):*
> ```HTML
>               </rich:column>
> 
>               <f:facet name="header">
> ```

Please change to footer like was did in other tables

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @KabacinskiPiotr)

___
*[oscm-portal/WebContent/marketplace/playground/organizationUnitPanel.xhtml, line 89 at r2](https://reviewable.io/reviews/servicecatalog/oscm/885#-M8nvIyE3xC5YnMu_FaY:-M8o4pcgD9x0UnPqJ2Ho:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/420c8b7d23c0e01d5331906ab331059350e8a21e/oscm-portal/WebContent/marketplace/playground/organizationUnitPanel.xhtml#L89)):*
<details><summary><i>Previously, KabacinskiPiotr wrote…</i></summary><blockquote>

Please change to footer like was did in other tables
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)* status: all files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)* status: all files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)* status: all files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)

**Review by farmakiG — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/885)* status: all files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)

**Pull request merged**
