### PR TITLE
Task#900 organizational units table

### LINKED ISSUE #900: [Users & Units] Organizational Units table

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Create new units table page

**Mandatory checks:**
- [ ] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [ ] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- ci:11

**Screenshot (if applicable):**
Units_2
Units_1
Units_4
Units_3

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/937)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/937)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @GoebelL and @KabacinskiPiotr)

___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties, line 68 at r1](https://reviewable.io/reviews/servicecatalog/oscm/937#-MAAXAby9L98OzeWJ_u-:-MAAX4d3E189L6qWvU9Q:b-64fdzu) ([raw file](https://github.com/servicecatalog/oscm/blob/4e92c3a77670741e7af3f52db3eb911fe3de276c/oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties#L68)):*
> ```INI
> button.manageUser=Benutzer verwalten
> button.manageOrganization=Organisation verwalten
> button.deleteOrganization=Organisation löschen
> ```

Use \u00F6 for ö
___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 3551 at r1](https://reviewable.io/reviews/servicecatalog/oscm/937#-MAAXOsS69IBXPCSCwti:-MAAXOsS69IBXPCSCwtj:b-sl5zdk) ([raw file](https://github.com/servicecatalog/oscm/blob/fe949adbecf24fa535ee2eaa5f0d527b09002e1b/oscm-portal/WebContent/marketplace/css/mp.css#L3551)):*
> ```CSS
>   margin: -2px 0px 0px 0px;
>   max-height: 30px;
>   font-size: 0.8rem;
> ```

Why is this removed?
___
*[oscm-portal/WebContent/marketplace/playground/account/profile.xhtml, line 77 at r1](https://reviewable.io/reviews/servicecatalog/oscm/937#-MAAYQpc492bAbQgEJmL:-MAAYQpd8sVCxTu5Bjk-:bvcyglk) ([raw file](https://github.com/servicecatalog/oscm/blob/4e92c3a77670741e7af3f52db3eb911fe3de276c/oscm-portal/WebContent/marketplace/playground/account/profile.xhtml#L77)):*
> ```HTML
>         <adm:buttonCustomizedOnClickBootstrap id="changePwdButton" value="#{msg['button.changePassword']}"
>                                               onclick="showLoginPanel('');return false;"
>                                               buttonStyleClass="btn btn-outline-secondary" buttonType="execute"/>
> ```

If this change is intended in this PR? If yes, could you please attach a screenshot?

**Comment by Piotr-K8i** [comment]
___
*[oscm-portal/WebContent/marketplace/playground/account/profile.xhtml, line 77 at r1](https://reviewable.io/reviews/servicecatalog/oscm/937#-MAAYQpc492bAbQgEJmL:-MAAdDRo8Mab_2y73HjU:bk7v5pe) ([raw file](https://github.com/servicecatalog/oscm/blob/4e92c3a77670741e7af3f52db3eb911fe3de276c/oscm-portal/WebContent/marketplace/playground/account/profile.xhtml#L77)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

If this change is intended in this PR? If yes, could you please attach a screenshot?
</blockquote></details>





I must change this because earlier I made changes at adm:buttonCustomizedOnClickBootstrap

**Comment by Piotr-K8i** [comment]
___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 3551 at r1](https://reviewable.io/reviews/servicecatalog/oscm/937#-MAAXOsS69IBXPCSCwti:-MAAdlI0DURniSP-mDRV:bcugkge) ([raw file](https://github.com/servicecatalog/oscm/blob/fe949adbecf24fa535ee2eaa5f0d527b09002e1b/oscm-portal/WebContent/marketplace/css/mp.css#L3551)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Why is this removed?
</blockquote></details>

It shouldn't I will rollback, I think Koala made changes

**Comment by Piotr-K8i** [comment]
___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 3551 at r1](https://reviewable.io/reviews/servicecatalog/oscm/937#-MAAXOsS69IBXPCSCwti:-MAAgKAE8dzRKJVfjL1a:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/fe949adbecf24fa535ee2eaa5f0d527b09002e1b/oscm-portal/WebContent/marketplace/css/mp.css#L3551)):*
<details><summary><i>Previously, KabacinskiPiotr wrote…</i></summary><blockquote>

It shouldn't I will rollback, I think Koala made changes 
</blockquote></details>

Done.

**Comment by Piotr-K8i** [comment]
___
*[oscm-portal/WebContent/marketplace/playground/account/profile.xhtml, line 77 at r1](https://reviewable.io/reviews/servicecatalog/oscm/937#-MAAYQpc492bAbQgEJmL:-MAAgNrgDfHBoqX8CCW7:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/4e92c3a77670741e7af3f52db3eb911fe3de276c/oscm-portal/WebContent/marketplace/playground/account/profile.xhtml#L77)):*
<details><summary><i>Previously, KabacinskiPiotr wrote…</i></summary><blockquote>





I must change this because earlier I made changes at adm:buttonCustomizedOnClickBootstrap
</blockquote></details>

Done.

**Comment by Piotr-K8i** [comment]
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties, line 68 at r1](https://reviewable.io/reviews/servicecatalog/oscm/937#-MAAXAby9L98OzeWJ_u-:-MAAgL2q9mVwwe4KiHLc:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/4e92c3a77670741e7af3f52db3eb911fe3de276c/oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties#L68)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Use \u00F6 for ö
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 15 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/937)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
