### PR TITLE
Epic#967_Subscription_service_pages

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Create responsive pages for service activation/deactivation and error page

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- ci:9

**Screenshot (if applicable):**

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1007)

### CODE REVIEW

**Review by farmakiG — COMMENTED** [review]
> Reviewed 13 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1007)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @farmakiG)

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/errorPage.xhtml, line 2 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1007#-MBdbIGPAslNAOwJYc56:-MBdbIGPAslNAOwJYc57:b-988xd4) ([raw file](https://github.com/servicecatalog/oscm/blob/3af80edd64fb33daf3449a723e51f06a2ba16246/oscm-portal/WebContent/marketplace/errorPage.xhtml#L2)):*
> ```HTML
> 
> 
> ```

Remove empty lines below 2020.

**Review by farmakiG — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1007)* status: all files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)

**Review by Piotr-K8i — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1007)* status: all files reviewed, 1 unresolved discussion (waiting on @farmakiG and @GoebelL)

___
*[oscm-portal/WebContent/marketplace/errorPage.xhtml, line 2 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1007#-MBdbIGPAslNAOwJYc56:-MBeAFs_7iRJf1NjxGx4:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/3af80edd64fb33daf3449a723e51f06a2ba16246/oscm-portal/WebContent/marketplace/errorPage.xhtml#L2)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Remove empty lines below 2020.
</blockquote></details>

Done.

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1007)* status: all files reviewed, 2 unresolved discussions (waiting on @farmakiG and @KabacinskiPiotr)

___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties, line 233 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1007#-MBe9NBG8ryi5VjQ_RmT:-MBe9NBG8ryi5VjQ_RmU:b-9pmcz7) ([raw file](https://github.com/servicecatalog/oscm/blob/5de3aab496cafed4cdb29497264c03d8c4082d43/oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties#L233)):*
> ```INI
> error.no.currencies=Es wird keine W\u00E4hrung unterst\u00FCtzt. Wenden Sie sich an den Betreiber, damit W\u00E4hrungen eingerichtet werden.
> error.organization.ldapsettings.nofile=Geben Sie eine g\u00FCltige Datei an, die die LDAP-Einstellung enth\u00E4lt.
> error.organization.role.notset=Der Organisation muss mindestens eine Rolle zugewiesen werden.
> ```

Where is this shown? Is 404 really the only error case? See errorcontent.xhtml.
Two points here
- error.page.error is a strange key name. Also I cannot make connection to an 404 error. Is the error message only for 404 than the key name should indicate it
- The "404 Not Found" is enough content for such error case. Additional text of error.page.not.found is a bit redundant. Please drop the later.

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 9 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1007)* status: all files reviewed, 3 unresolved discussions (waiting on @farmakiG and @KabacinskiPiotr)

___
*[oscm-portal/WebContent/marketplace/templates/errorcontent.xhtml, line 27 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1007#-MBeD9y4-IaD0HK5ttvo:-MBeD9y4-IaD0HK5ttvp:bd7bp6k) ([raw file](https://github.com/servicecatalog/oscm/blob/5de3aab496cafed4cdb29497264c03d8c4082d43/oscm-portal/WebContent/marketplace/templates/errorcontent.xhtml#L27)):*
> ```HTML
>     </h1>
>     <h2>
>       <h:outputText id="mpErrorPageNotFound" value="#{msg['error.page.error']}"/>
> ```

@kabacinskipiotr 
See above. I actually don't know about the context here. But it seems wrong to me to hardwire the content to 404 error messages. I think we had a generic page here where the error comes from the application.
See in the left side: True, the message key is set one time by c:set (in build view phase view) but it'll be dynamically updated from the application (e.g. in faces context in ajax rerendering or self re-rending rich:panel - both not impacted by tag handlers or c: tag logic)
 
Considering that this page is located in the templates folder, it seems strange that content should stick to 404 cases. Please check.

**Comment by Piotr-K8i** [comment]
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties, line 233 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1007#-MBe9NBG8ryi5VjQ_RmT:-MBeN380-8CA8ZYlPEWl:b2d1vd) ([raw file](https://github.com/servicecatalog/oscm/blob/5de3aab496cafed4cdb29497264c03d8c4082d43/oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties#L233)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Where is this shown? Is 404 really the only error case? See errorcontent.xhtml.
Two points here
- error.page.error is a strange key name. Also I cannot make connection to an 404 error. Is the error message only for 404 than the key name should indicate it
- The "404 Not Found" is enough content for such error case. Additional text of error.page.not.found is a bit redundant. Please drop the later. 
</blockquote></details>

I removed the display of 404 errors because this page may also appear e.g. when trying to display the registration form or attempting to login

**Comment by Piotr-K8i** [comment]
> > Reviewed 9 of 14 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1007)_ status: all files reviewed, 3 unresolved discussions (waiting on @farmakiG and @KabacinskiPiotr)
> 
> _[oscm-portal/WebContent/marketplace/templates/errorcontent.xhtml, line 27 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1007#-MBeD9y4-IaD0HK5ttvo:-MBeD9y4-IaD0HK5ttvp:bd7bp6k) ([raw file](https://github.com/servicecatalog/oscm/blob/5de3aab496cafed4cdb29497264c03d8c4082d43/oscm-portal/WebContent/marketplace/templates/errorcontent.xhtml#L27)):_
> 
> > ```
> >     </h1>
> >     <h2>
> >       <h:outputText id="mpErrorPageNotFound" value="#{msg['error.page.error']}"/>
> > ```
> 
> @KabacinskiPiotr
> See above. I actually don't know about the context here. But it seems wrong to me to hardwire the content to 404 error messages. I think we had a generic page here where the error comes from the application.
> See in the left side: True, the message key is set one time by c:set (in build view phase view) but it'll be dynamically updated from the application (e.g. in faces context in ajax rerendering or self re-rending rich:panel - both not impacted by tag handlers or c: tag logic)
> 
> Considering that this page is located in the templates folder, it seems strange that content should stick to 404 cases. Please check.

Yes, I removed display 404 error message. We don't have any custom page for this error
image

**Review by GoebelL — COMMENTED** [review]
> Reviewed 2 of 14 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1007)* status: all files reviewed, 2 unresolved discussions (waiting on @farmakiG and @GoebelL)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1007)* status: all files reviewed, 1 unresolved discussion (waiting on @farmakiG)

**Review by farmakiG — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1007#-:-MBiLHMW0yLNzZF90xl8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @farmakiG)

**Pull request merged**
