### PR TITLE
Fix responsive stage

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- Fixed Failing Tests.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**
- add a screenshot illustrating your change

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1014)

### CODE REVIEW

**Review by cworf91 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1014)* status: all files reviewed, 4 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java, line 97 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1014#-MBt1zDqA9LSlqqGT3c0:-MBt1zDqA9LSlqqGT3c1:b-xgm6av) ([raw file](https://github.com/servicecatalog/oscm/blob/301c928a9d4eb769ee35f051ee40c4574d101e72/oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java#L97)):*
> ```Java
>         .thenReturn(stageContent);
> 
>     String resultDiv = MessageFormat.format(SkinBean.MARKETPLACE_STAGE_BRANDED, stageContent);
> ```

it´s the expectedDiv
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java, line 112 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1014#-MBt2F5GEKxWoMO3VRmp:-MBt2F5GEKxWoMO3VRmq:b-xgm6av) ([raw file](https://github.com/servicecatalog/oscm/blob/301c928a9d4eb769ee35f051ee40c4574d101e72/oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java#L112)):*
> ```Java
>     when(brandServiceMock.getMarketplaceStage(anyString(), eq(Locale.CHINA.getLanguage())))
>         .thenReturn(stageContentBranded);
>     String resultDiv =
> ```

it´s the expectedDiv
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java, line 127 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1014#-MBt2MYU951R3vp7pc_B:-MBt2MYU951R3vp7pc_C:b-xgm6av) ([raw file](https://github.com/servicecatalog/oscm/blob/301c928a9d4eb769ee35f051ee40c4574d101e72/oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java#L127)):*
> ```Java
> 
>     // then
>     String resultDiv = MessageFormat.format(SkinBean.MARKETPLACE_STAGE_BRANDED, stageContent);
> ```

it´s the expectedDiv
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java, line 150 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1014#-MBt2PHN-L4g-kwDoGtw:-MBt2PHN-L4g-kwDoGtx:b-xgm6av) ([raw file](https://github.com/servicecatalog/oscm/blob/301c928a9d4eb769ee35f051ee40c4574d101e72/oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java#L150)):*
> ```Java
> 
>     // then
>     String resultDiv =
> ```

it´s the expectedDiv

**Review by cworf91 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1014#-:-MBt8Gyb2_YCxktVP8Ux:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @farmakiG)

**Comment by farmakiG** [comment]
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java, line 97 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1014#-MBt1zDqA9LSlqqGT3c0:-MBtC1Rc9eGj4I_SJxx4:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/301c928a9d4eb769ee35f051ee40c4574d101e72/oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java#L97)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

it´s the expectedDiv
</blockquote></details>

Done.

**Review by farmakiG — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1014#-:-MBtBzYg1anJkqLVjQ4t:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @cworf91)

___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java, line 112 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1014#-MBt2F5GEKxWoMO3VRmp:-MBtC39D9_uhBs4PRN_D:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/301c928a9d4eb769ee35f051ee40c4574d101e72/oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java#L112)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

it´s the expectedDiv
</blockquote></details>

Done.
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java, line 127 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1014#-MBt2MYU951R3vp7pc_B:-MBtC5rnAk-DVon271e-:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/301c928a9d4eb769ee35f051ee40c4574d101e72/oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java#L127)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

it´s the expectedDiv
</blockquote></details>

Done.
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java, line 150 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1014#-MBt2PHN-L4g-kwDoGtw:-MBtC7a_1mGoFgTND77T:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/301c928a9d4eb769ee35f051ee40c4574d101e72/oscm-portal-unittests/javasrc/org/oscm/ui/beans/SkinBeanTest.java#L150)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

it´s the expectedDiv
</blockquote></details>

Done.

**Pull request merged**
