### PR TITLE
add mobile stage

### LINKED ISSUE #893: Mobile Stage
**Summary**
Provide for defining a separate marketplace stage content, that is shown only in mobile view.

**Details**
Marketplace stage dimensions are designed for desktop displays. This is not suitable for small display media. The request is to allow the marketplace owner to define a second stage content that is used for small display views.
Unless a mobile stage is defined a default white label mobile stage shall be shown in a small view (an image created from existing white label stage image with mobile dimensions). 
 
**Technical Implementation**
*Service layer*
Extend `org.oscm.internal.intf.BrandService`
```java
   public void setMarketplaceMobileStage(String mobileStageContent, String marketplaceId,
            String localeString) throws ObjectNotFoundException,
            OperationNotPermittedException;
```

*Data and Persistence Layer*
New enum filed in `org.oscm.domobjects.enums.LocalizedObjectTypes`
```java
    /**
     * Defines the content of the mobile stage of the landing page.
     */
    MARKETPLACE_MOBILE_STAGE(InformationSource.DATABASE),
```

Data migration is not needed.

**Acceptance criteria**
Two stages can be defined (optional)
- [ ] Mobile stage is shown in mobile view in case if it's defined for the opened marketplace
- [ ] Mobile default stage is shown in small view if mobile stage is undefined
- [ ] Marketplace desktop stage is shown in large views as before

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by cworf91**
**Changes in this Pull Request:**
- add mobile stage

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [x] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/920)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 13 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/920)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @cworf91 and @GoebelL)

___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_en.properties, line 755 at r1](https://reviewable.io/reviews/servicecatalog/oscm/920#-M9NamnE6rCGjK63X9te:-M9NamnF3v-CJNRGXapK:ba9m4gr) ([raw file](https://github.com/servicecatalog/oscm/blob/c4a5b8ef0ad45715ab8d10e09f7a44addf8179ae/oscm-portal/javares/org/oscm/ui/resources/Messages_en.properties#L755)):*
> ```INI
> marketplace.stage.define=Select a language, and enter your HTML code\:
> marketplace.stage.example=The recommended width of the stage is 100%, the recommended height is between 200 and 300 pixels. For example\: <IFRAME FRAMEBORDER\="0"  SRC\="yourstage.htm" NAME\="stage" WIDTH\="100%" HEIGHT\="280px" SCROLLING\="no"></IFRAME>
> marketplace.mobileStage.example=The recommended width of the stage is 100%, the recommended height is between 200 and 300 pixels. For example\: <IFRAME FRAMEBORDER\="0"  SRC\="yourstage.htm" NAME\="stage" WIDTH\="100%" HEIGHT\="280px" SCROLLING\="no"></IFRAME>
> ```

Please adapt this description. It's not suitable for mobile stage. The recommended width of the stage is 100%, the recommended height should be around 700 pixels and fit the screen with a common 16:9 aspect ratio.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/920)* status: 14 of 16 files reviewed, all discussions resolved

**Review by GoebelL — DISMISSED** [review]
> Reviewed 2 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/920)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/920)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @cworf91 and @GoebelL)

___
*[oscm-portal/WebContent/shop/editStage.xhtml, line 102 at r2](https://reviewable.io/reviews/servicecatalog/oscm/920#-M9d5Ll83YA-6Ef9hnJi:-M9d5Ll83YA-6Ef9hnJj:bvanmun) ([raw file](https://github.com/servicecatalog/oscm/blob/5598c533773949ad4d7cd95f026f8fe6fd0f12bf/oscm-portal/WebContent/shop/editStage.xhtml#L102)):*
> ```HTML
>       
>       <adm:buttonPanel columns="1">
>         <adm:button id="saveButton2" value="#{msg['button.save']}" bean="#{translationBean}" action="saveMobileStage"
> ```

Instead of two save buttons in the UI, the should be one save button for the entire page. Remove this one, or simply change this button into an invisible h:commandButton for saving the mobile stage, like
 ``` <h:commandButton style="display:none;" ... ```"

**Comment by cworf91** [comment]
Still todo:
- Add description in Help
- Add responsive design for the mobile stage
- Add image

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/920)* status: 14 of 19 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-portal/WebContent/shop/editStage.xhtml, line 102 at r2](https://reviewable.io/reviews/servicecatalog/oscm/920#-M9d5Ll83YA-6Ef9hnJi:-M9rx6SZE2GtwvTjCNt2:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/5598c533773949ad4d7cd95f026f8fe6fd0f12bf/oscm-portal/WebContent/shop/editStage.xhtml#L102)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Instead of two save buttons in the UI, the should be one save button for the entire page. Remove this one, or simply change this button into an invisible h:commandButton for saving the mobile stage, like
 ``` <h:commandButton style="display:none;" ... ```"

</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 4 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/920)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
