### PR TITLE
Provide for downloading tenant configuration templates 

### LINKED ISSUE #379: Export tenant settings template
**Summary**
Display also default tenant settings in the manage tenants UI and provide a function  to download configuration template for the selected tenant.

**Details**
* Add default tentent to the tenant list. 
* Add a button export template that is alway enabled.

**Acceptance criteria**
Later

**Additional context**
Later

### PR DESCRIPTION
**Pull request by GoebelL**
Fixes #379. 

* Provide for downloading tenant configuration templates from manage tenants UI
* Include default tenant configuration for displaying in UI

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/381)

### CODE REVIEW

**Review by cworf91 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/381)* status: 0 of 10 files reviewed, 5 unresolved discussions (waiting on @cworf91 and @GoebelL)

___
*[oscm-internal/javasrc/org/oscm/internal/tenant/ManageTenantServiceBean.java, line 57 at r1](https://reviewable.io/reviews/servicecatalog/oscm/381#-Lkxzg3f4mqTzChLg_dy:-Lkxzg3f4mqTzChLg_dz:b-rjkl2u) ([raw file](https://github.com/servicecatalog/oscm/blob/2dfe27de5648f4326736d9d94d56a43616f3de15/oscm-internal/javasrc/org/oscm/internal/tenant/ManageTenantServiceBean.java#L57)):*
> ```Java
>         List<POTenant> poTenants = new ArrayList<>();
>         poTenants.add(createDefaultTenant());
>         poTenants.addAll(getAllTenants());
> ```

Maybe getAllTenants() should be named getAllTenantsWithoutDefaultTenant(). But that´s maybe a refactoring task. 
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_en.properties, line 57 at r1](https://reviewable.io/reviews/servicecatalog/oscm/381#-Lky01jV9_KOFzVnw5uq:-Lky01jV9_KOFzVnw5ur:bqbewi2) ([raw file](https://github.com/servicecatalog/oscm/blob/2dfe27de5648f4326736d9d94d56a43616f3de15/oscm-portal/javares/org/oscm/ui/resources/Messages_en.properties#L57)):*
> ```INI
> button.execute=Execute
> button.export=Export
> button.export.template=Download a template
> ```

Is it realy "Download a template" or "Download template" like "Vorlage herunterladen"?
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties, line 57 at r1](https://reviewable.io/reviews/servicecatalog/oscm/381#-Lky0vPw1mo7qFxaLien:-Lky0vPw1mo7qFxaLieo:buo9nmt) ([raw file](https://github.com/servicecatalog/oscm/blob/2dfe27de5648f4326736d9d94d56a43616f3de15/oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties#L57)):*
> ```INI
> button.execute=\u5b9f\u884c
> button.export=\u30a8\u30af\u30b9\u30dd\u30fc\u30c8
> button.export.template=Download a template
> ```

Same here
___
*[oscm-portal/javasrc/org/oscm/ui/dialog/classic/manageTenants/ManageTenantsCtrl.java, line 104 at r1](https://reviewable.io/reviews/servicecatalog/oscm/381#-Lky1O8p874e3yqamoUe:-Lky1O8p874e3yqamoUf:b16224l) ([raw file](https://github.com/servicecatalog/oscm/blob/2dfe27de5648f4326736d9d94d56a43616f3de15/oscm-portal/javasrc/org/oscm/ui/dialog/classic/manageTenants/ManageTenantsCtrl.java#L104)):*
> ```Java
>     private POTenant getSelectedTenant() {
>         POTenant defaultTenant = getDefaultTenant();
>         if (!defaultTenant.getTenantId().equals(model.getSelectedTenantId())) {
> ```

Is here a nullcheck necasarry? What happen the runtime exception is thrown?
___
*[oscm-portal-unittests/javasrc/org/oscm/ui/dialog/classic/manageTenants/ManageTenantsCtrlTest.java, line 227 at r1](https://reviewable.io/reviews/servicecatalog/oscm/381#-Lky3U2nBvfC6j6u-q26:-Lky3U2nBvfC6j6u-q27:b-pkuuy2) ([raw file](https://github.com/servicecatalog/oscm/blob/2dfe27de5648f4326736d9d94d56a43616f3de15/oscm-portal-unittests/javasrc/org/oscm/ui/dialog/classic/manageTenants/ManageTenantsCtrlTest.java#L227)):*
> ```Java
>         HttpURLConnection httpMock = mock(HttpURLConnection.class);
>         doReturn(httpMock).when(ctrl).getConnection();
> ```

should the connection be closed at the end of the test?

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/381)* status: 0 of 10 files reviewed, 5 unresolved discussions (waiting on @cworf91 and @GoebelL)

___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_en.properties, line 57 at r1](https://reviewable.io/reviews/servicecatalog/oscm/381#-Lky01jV9_KOFzVnw5uq:-LkyIg8w8v0XzePoTfS4:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/2dfe27de5648f4326736d9d94d56a43616f3de15/oscm-portal/javares/org/oscm/ui/resources/Messages_en.properties#L57)):*
<details><summary><i>Previously, cworf91 wrote…</i></summary><blockquote>

Is it realy "Download a template" or "Download template" like "Vorlage herunterladen"?
</blockquote></details>

Done.
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties, line 57 at r1](https://reviewable.io/reviews/servicecatalog/oscm/381#-Lky0vPw1mo7qFxaLien:-LkyNpFf-NfEeIKdRgM-:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/2dfe27de5648f4326736d9d94d56a43616f3de15/oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties#L57)):*
<details><summary><i>Previously, cworf91 wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[oscm-portal/javasrc/org/oscm/ui/dialog/classic/manageTenants/ManageTenantsCtrl.java, line 104 at r1](https://reviewable.io/reviews/servicecatalog/oscm/381#-Lky1O8p874e3yqamoUe:-LkyIl_748WM3gzTu8zS:b-gj70rx) ([raw file](https://github.com/servicecatalog/oscm/blob/2dfe27de5648f4326736d9d94d56a43616f3de15/oscm-portal/javasrc/org/oscm/ui/dialog/classic/manageTenants/ManageTenantsCtrl.java#L104)):*
<details><summary><i>Previously, cworf91 wrote…</i></summary><blockquote>

Is here a nullcheck necasarry? What happen the runtime exception is thrown?
</blockquote></details>

No. Either this subsequent code is executed or an exception is thrown. Both together is impossible. Runtime exceptions are unchecked and not user exceptions. They must not be caught by business functions. The OSCM UI framework (in the filter package) provides the central "runtime" to handle such cases with with the "operation failed" screen and respective error trace entry in system.log.

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/381)* status: 0 of 10 files reviewed, 5 unresolved discussions (waiting on @cworf91 and @GoebelL)

___
*[oscm-portal-unittests/javasrc/org/oscm/ui/dialog/classic/manageTenants/ManageTenantsCtrlTest.java, line 227 at r1](https://reviewable.io/reviews/servicecatalog/oscm/381#-Lky3U2nBvfC6j6u-q26:-LkyOaCoBDqQCJbsggEz:bnbqjhg) ([raw file](https://github.com/servicecatalog/oscm/blob/2dfe27de5648f4326736d9d94d56a43616f3de15/oscm-portal-unittests/javasrc/org/oscm/ui/dialog/classic/manageTenants/ManageTenantsCtrlTest.java#L227)):*
<details><summary><i>Previously, cworf91 wrote…</i></summary><blockquote>

should the connection be closed at the end of the test?
</blockquote></details>

Just a test mock.

**Review by cworf91 — APPROVED** [review]

**Review by cworf91 — COMMENTED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/381#-:-LkyQYZQ7Td8STYyGNkG:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @cworf91 and @GoebelL)

**Review by cworf91 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/381#-:-LkyQd5G4YDEUoe68kB3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by cworf91 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/381)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
