### PR TITLE
Remove hardcoded path variable

### LINKED ISSUE #689: OSCM OIDC mode issue with reverse proxy
**Version Info**
v18.1

**Describe the bug**
OSCM 18.1 in OIDC mode is not usable with reverse proxy. This is due to hardcoded application paths and ports, like [here](https://github.com/servicecatalog/oscm/blob/master/oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java#L114)
These shall be removed and tested with reverse proxy.

**How to Reproduce**
1. Setup OSCM in OIDC mode with a default tenant as described in the Operator's Guide 
2. Setup a webserver and configure oscm-portal location on 443 with a reverse proxy rule (ask me how to) 
3. Try to access the oscm-portal

**Observed behaviour**
The oscm-portal is not accessible with custom URL (because hardcoded ports and application contexts as shown above)

**Expected behaviour**
The oscm-portal is accessible with custom URL.

**Additional context**
Note: OSCM v18.1 in internal mode is working well with reverse proxy using custom URLs on default HTTPS port 443.

### PR DESCRIPTION
**Pull request by cworf91**
**Changes in this Pull Request:**
- Make path for redirect configurable. 
- Remove saml check
- Update and add Unit tests

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [x] unit tests were properly implemented

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/710)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/710)* status: all files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java, line 111 at r2](https://reviewable.io/reviews/servicecatalog/oscm/710#-M23bXHd1eSYNAQJuBB8:-M23bXHe3qsYKLSb8R11:b2nh7wk) ([raw file](https://github.com/servicecatalog/oscm/blob/99f04c064fd380904ee5819eda9dad153c27eb10/oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java#L111)):*
> ```Java
>   private String buildRedirectionUrl(URI requestedUri, String path) {
> 
>     path.length();
> ```

?

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/710)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java, line 111 at r2](https://reviewable.io/reviews/servicecatalog/oscm/710#-M23bXHd1eSYNAQJuBB8:-M23gXYx2blysuzuv7Nj:b-hfpv0l) ([raw file](https://github.com/servicecatalog/oscm/blob/99f04c064fd380904ee5819eda9dad153c27eb10/oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java#L111)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

? 
</blockquote></details>

removed

**Review by GoebelL — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/710)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/710)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
