### PR TITLE
Distributed switch

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/248)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/248)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @cworf91 and @GoebelL)

___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/NetworkManager.java, line 164 at r1](https://reviewable.io/reviews/servicecatalog/oscm/248#-LaL4saMEEWtTSIJ2jPv:-LaL4saMEEWtTSIJ2jPw:bficdtc) ([raw file](https://github.com/servicecatalog/oscm/blob/2411efab9b9729e2c86dd1469e8cf04d5b6123c6/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/NetworkManager.java#L164)):*
> ```Java
>                 .getDvSwitchManager();
> 
>         List<ManagedObjectReference> s = (List<ManagedObjectReference>) vmw
> ```

This seems unused. Please check.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/248)* status: all files reviewed, 1 unresolved discussion (waiting on @cworf91)

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/248)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-app-vmware/javasrc/org/oscm/app/vmware/business/NetworkManager.java, line 164 at r1](https://reviewable.io/reviews/servicecatalog/oscm/248#-LaL4saMEEWtTSIJ2jPv:-LaL5sMX3-P8FItkBndv:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/2411efab9b9729e2c86dd1469e8cf04d5b6123c6/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/NetworkManager.java#L164)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

This seems unused. Please check.
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/248)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
