### PR TITLE
Test/ui test refractor

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
Introduce single oscm-ui-tests maven project containing oscm-webtest-base and oscm-portal-integrationtests. Skip Selenium test from CODECOV

**Mandatory checks:**
- [ ] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
_Please provide the link for the successfull build_

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/634)

### CODE REVIEW

**Review by adamczykba — DISMISSED** [review]
:lgtm:

> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/634#-:-LzkQxa5ATEOsF7daJVa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kowalczyka)

**Review by kowalczyka — CHANGES_REQUESTED** [review]
UI tests are now ready to work with Chrome driver:

- please add the changes from https://github.com/servicecatalog/oscm/commit/000afa75a912412b990fffdd2603f292a896859e to the new project
- remove old projects
- provide the link to the successfull Jenkins job which incudes described changes

**Comment by Piotr-K8i** [comment]
[Jenkins job](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Integration_Tests_Upgrade/72/)

@kowalczyka - > Done

**Review by kowalczyka — COMMENTED** [review]
oscm-webtest-base should be moved to src/main/java. Why is it in src/test/java? Additionaly let's keep packaging naming e.g. org.oscm....

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/634#-:-Lzm3pyf1WNHSgnuoNSj:b-hdbjkl)* status: 23 of 26 files reviewed, all discussions resolved (waiting on @adamczykba and @KabacinskiPiotr)

**Review by adamczykba — COMMENTED** [review]
@kowalczyka I guess that way, the test suite code will not count towards the code coverage 

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/634#-:-LzmGQWRD2k3zUNkvMKA:bmmcpdv)* status: 23 of 26 files reviewed, all discussions resolved (waiting on @adamczykba and @KabacinskiPiotr)

**Comment by kowalczyka** [comment]
Closing as it had to be merged from cmd line https://github.com/servicecatalog/oscm/commit/37247afb5caac7fbc352213c16ef9cee8c27cc70

**Pull request closed without merging**
