### PR TITLE
Adapted token validation call

### PR DESCRIPTION
**Pull request by adamczykba**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/462)

### CODE REVIEW

**Review by kowalczyka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/462)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @adamczykba and @kowalczyka)

___
*[oscm-portal/javasrc/org/oscm/ui/filter/OidcFilter.java, line 142 at r1](https://reviewable.io/reviews/servicecatalog/oscm/462#-LpbVIXn1CSfYFc42mcb:-LpbVIXn1CSfYFc42mcc:brnoyjd) ([raw file](https://github.com/servicecatalog/oscm/blob/5792ebdda2dc85dcad459fc2fc6bbf9ffb66edcc/oscm-portal/javasrc/org/oscm/ui/filter/OidcFilter.java#L142)):*
> ```Java
> 
>     if (idToken != null) validateIdToken(idToken, post, client);
>     if (accessToken != null) validateAccessToken(idToken, post, client);
> ```

id token is passed here instead of access token

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/462)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @adamczykba and @kowalczyka)

___
*[oscm-portal/javasrc/org/oscm/ui/filter/OidcFilter.java, line 142 at r1](https://reviewable.io/reviews/servicecatalog/oscm/462#-LpbVIXn1CSfYFc42mcb:-Lpbd7Ue1D5R5yXiNtOc:b-fitmlf) ([raw file](https://github.com/servicecatalog/oscm/blob/5792ebdda2dc85dcad459fc2fc6bbf9ffb66edcc/oscm-portal/javasrc/org/oscm/ui/filter/OidcFilter.java#L142)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

id token is passed here instead of access token
</blockquote></details>

Good found. In this context a kind request from my side, that these PR needs to be manually tested before it gets merged in SSO branch.

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/462)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @adamczykba and @kowalczyka)

___
*[oscm-portal/javasrc/org/oscm/ui/filter/OidcFilter.java, line 142 at r1](https://reviewable.io/reviews/servicecatalog/oscm/462#-LpbVIXn1CSfYFc42mcb:-LpbeNzN05nAeQFLUJt6:b-v47wrq) ([raw file](https://github.com/servicecatalog/oscm/blob/5792ebdda2dc85dcad459fc2fc6bbf9ffb66edcc/oscm-portal/javasrc/org/oscm/ui/filter/OidcFilter.java#L142)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Good found. In this context a kind request from my side, that these PR needs to be manually tested before it gets merged in SSO branch. 
</blockquote></details>

Also respective unit tests are needed, in OIDCFilterTest.

**Review by adamczykba — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/462)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @adamczykba and @kowalczyka)

___
*[oscm-portal/javasrc/org/oscm/ui/filter/OidcFilter.java, line 142 at r1](https://reviewable.io/reviews/servicecatalog/oscm/462#-LpbVIXn1CSfYFc42mcb:-Lpc6qWyCfVR8xhpjDoM:b-v15hl9) ([raw file](https://github.com/servicecatalog/oscm/blob/5792ebdda2dc85dcad459fc2fc6bbf9ffb66edcc/oscm-portal/javasrc/org/oscm/ui/filter/OidcFilter.java#L142)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Also respective unit tests are needed, in OIDCFilterTest. 
</blockquote></details>

Done and tested

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/462)* status: all files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

**Review by kowalczyka — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/462#-:-LpcbmSiAM0SUXAhBvBc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
