### PR TITLE
Task#1023_Fixup pager bar styles

### LINKED ISSUE #1023: Brush up the service pager bar
**Summary**
Some styling flaws in the service bar

**Details**
- Fix horizontal alignment and border
- Move left service numbers more left 

**Acceptance criteria**
- [ ] Looking well styled in desktop view
- [ ] Looking well styled in small mobile view

**Additional context**
Here is how it looks now:
image

And here how it's ideally supposed to look like:
image

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Remove unnecessary style class
- Fixup pager bar styles

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- ci:9

**Screenshot (if applicable):**

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1025)

### CODE REVIEW

**Review by farmakiG — DISMISSED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1025)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @GoebelL)

**Review by farmakiG — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1025)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @GoebelL)

**Review by farmakiG — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1025)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @GoebelL)

**Review by GoebelL — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1025)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
