### PR TITLE
Task#1127 reformat mp css

### LINKED ISSUE #1127: Clean the format of mp.scss
**Summary**
Update mp.scss toc and format.

**Details**
1.	The toc is out dated. The scss file starts with chapter 5.1 and the toc lists 1-11. For all chapters listed in the toc there should be be contained in the file, at least the chapter number and header title. Thus chapters can be empty but must appear in the file, otherwise the file looks broken.
2.	The final chapter "9 UI Graphics" is a mess. Chapter 10+11 are missing (see point 1) and Chapter 9.2 has a length of 672 lines (!). It seems to be of all various content, where most of the styles are not related to UI Graphics. The request is to first order all these styles, grouping them by topic and move the topic groups at the right place in the document. F.e. richfaces related styles should be grouped or sub grouped to make clear that they are related to this framework

3. The begin of the document should contain a short description with link pointing to Marketplace Customization Guide 
    https://github.com/servicecatalog/oscm/blob/master/oscm-portal/WebContent/marketplace/customBootstrap/README.md

**Acceptance criteria**
- [ ] TOC is up-to-date
- [ ] Content is arranged
- [ ] Chapter 9.1 UI Graphics contains about styling related to graphics not 

**Additional context**
Add any other context or screenshots about the task.

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Reformat marketplace sass files

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1134)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1134)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @KabacinskiPiotr)

___
*[oscm-portal/WebContent/marketplace/scss/mp.scss, line 4 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1134#-MNcMJBe-6EfjM432iiZ:-MNcMJBe-6EfjM432ii_:b-uphoxg) ([raw file](https://github.com/servicecatalog/oscm/blob/46aa4cbdc2b020c40bba3edb00abe4956ac6dcef/oscm-portal/WebContent/marketplace/scss/mp.scss#L4)):*
> ```SCSS
>  *  Copyright FUJITSU LIMITED 2020
>  */
> ```

Please add a short description with link as request in point 3. of the task

This is a Sass based stylesheet for styling OSCM marketplaces. 
This file serves as a compile template for the marketplace related styles. Any modifications to the marketplace CSS or related CSS files, shall only be carried out by compiling this SCSS file with respective tools. 
Please refer to the Marketplace Customization Guide at https://github.com/servicecatalog/oscm/blob/master/oscm-portal/WebContent/marketplace/customBootstrap/README.md for a detailed description of how to use this.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 15 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1134)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @KabacinskiPiotr)

**Review by Piotr-K8i — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1134)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @KabacinskiPiotr)

___
*[oscm-portal/WebContent/marketplace/scss/mp.scss, line 4 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1134#-MNcMJBe-6EfjM432iiZ:-MNcX00S5CD6CmKNdPS5:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/46aa4cbdc2b020c40bba3edb00abe4956ac6dcef/oscm-portal/WebContent/marketplace/scss/mp.scss#L4)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Please add a short description with link as request in point 3. of the task

This is a Sass based stylesheet for styling OSCM marketplaces. 
This file serves as a compile template for the marketplace related styles. Any modifications to the marketplace CSS or related CSS files, shall only be carried out by compiling this SCSS file with respective tools. 
Please refer to the Marketplace Customization Guide at https://github.com/servicecatalog/oscm/blob/master/oscm-portal/WebContent/marketplace/customBootstrap/README.md for a detailed description of how to use this.



</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1134)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
