### PR TITLE
Vmware debug

### PR DESCRIPTION
**Pull request by xusuest**
After saving settings, the Vcenter data will be reloaded. so that the data of settings is updated. 
The issue is resolved.

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/133)

### CODE REVIEW

**Review by GoebelL — COMMENTED** [review]
Hi, travis has been fixed on master. Please fetch from upstream.

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/133#-:-LIojwYY6bCwQ5vSBXt8:bmgrr85)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @GoebelL)

**Comment by ghost** [comment]
As an note: it also fixes issue that I fix in #131.

**Review by GoebelL — APPROVED** [review]
Looks good.

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/133#-:-LIpV2wR644gH5slRlJ6:b9a3lbe)* status: 0 of 2 files reviewed, all discussions resolved

**Review by GoebelL — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/133#-:-LIpVXP3E7TWdKutyxwd:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by GoebelL — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/133)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
