### PR TITLE
OIDC User Sync / Cleanup and Unit Tests

### PR DESCRIPTION
**Pull request by GoebelL**
**Changes in this Pull Request:**
- Change #1: Coding and logging.

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [x] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM Build And Push job](http://estessbesci1:8080/view/Docker_OSCM/job/OSCM_Docker_Build_and_push/276/)
- Manually deployed and tested on ci10.

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/522)

### CODE REVIEW

**Review by kowalczyka — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/522)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/OidcSynchronizationBean.java, line 95 at r1](https://reviewable.io/reviews/servicecatalog/oscm/522#-LsW2LLY28jOpcxHu2aw:-LsW2LLY28jOpcxHu2ax:b5w2pg3) ([raw file](https://github.com/servicecatalog/oscm/blob/0cd4ac6bb032a93282a55329413e757ed3a6d0d3/oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/OidcSynchronizationBean.java#L95)):*
> ```Java
>     protected List<Organization> syncOrganizations(GroupInfo group, String tenantId) {
>         try {
> ```

Is this wrapping with array and converting to list necessary? syncOrganization always return single organization

**Comment by GoebelL** [comment]
> 
> 
> > Reviewed 6 of 7 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/522)_ status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)
> 
> _[oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/OidcSynchronizationBean.java, line 95 at r1](https://reviewable.io/reviews/servicecatalog/oscm/522#-LsW2LLY28jOpcxHu2aw:-LsW2LLY28jOpcxHu2ax:b5w2pg3) ([raw file](https://github.com/servicecatalog/oscm/blob/0cd4ac6bb032a93282a55329413e757ed3a6d0d3/oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/OidcSynchronizationBean.java#L95)):_
> 
> > ```java
> >     protected List<Organization> syncOrganizations(GroupInfo group, String tenantId) {
> >         try {
> > ```
> 
> Is this wrapping with array and converting to list necessary? syncOrganization always return single organization

Well, the syncOrganizations returns 1 organization in positive case but 0 otherwise. This is for fault tollerance, as it must no throw but only log potentential errors, whereas the surounding loop has to continue with the next group. Returning a list type here simplifies the caller and avoids the null check (returning null [is a bad practice](https://stackoverflow.com/a/1274865).)

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/522)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

___
*[oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/OidcSynchronizationBean.java, line 95 at r1](https://reviewable.io/reviews/servicecatalog/oscm/522#-LsW2LLY28jOpcxHu2aw:-LsWJpAy9WvrbTe4ld1X:b2nhk7e) ([raw file](https://github.com/servicecatalog/oscm/blob/aaa60be92706db8bedf8dd755eb4918cfad9ca3c/oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/OidcSynchronizationBean.java#L95)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Well, the syncOrganizations returns 1 organization in positive case but 0 otherwise. This is for fault tollerance, as it must no throw but only log potentential errors, whereas the surounding loop has to continue with the next group. Returning a list type here simplifies the caller and avoids the null check (returning null [is a bad practice](https://stackoverflow.com/a/1274865).) 
</blockquote></details>

NOP

**Review by kowalczyka — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/522#-:-LsWV8LU-zDa10C3Zz4T:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

**Review by kowalczyka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/522)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
