### PR TITLE
Some page apperance change

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Change div width for Radio Bottoms [ shop/customizeLandingpage ]
- Change for Bottoms align text to center

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [ ] changes were tested manually
- [ ] unit tests were properly implemented
- [x] communication about interdependent changes has been sent to the team (if applicable)
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM Pull And Start job](https://10.140.18.12:8081/oscm-portal/shop/customizeLandingpage.jsf)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/674)

### CODE REVIEW

**Comment by Piotr-K8i** [comment]
### Before change:
image

### After change
image

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/shop/customFeaturedServices.xhtml, line 57 at r1](https://reviewable.io/reviews/servicecatalog/oscm/674#-M0qLnsK1InvWXFg_Ss-:-M0qLnsK1InvWXFg_Ss0:b9x6yc0) ([raw file](https://github.com/servicecatalog/oscm/blob/a696a60a963fe727f9e84a01e5cc1e3018440668/oscm-portal/WebContent/shop/customFeaturedServices.xhtml#L57)):*
> ```HTML
>     </rich:pickList>
> ```

We should in general avoid inline styles as it makes harder the css stylesheet maintainance and the clear separation of view and model. Instead, you can define a class in portal. css and then define the div as such: <div class="fillinDiv fitContentDiv" or so.

**Comment by Piotr-K8i** [comment]
> _[oscm-portal/WebContent/shop/customFeaturedServices.xhtml, line 57 at r1](https://reviewable.io/reviews/servicecatalog/oscm/674#-M0qLnsK1InvWXFg_Ss-:-M0qLnsK1InvWXFg_Ss0:b9x6yc0) ([raw file](https://github.com/servicecatalog/oscm/blob/a696a60a963fe727f9e84a01e5cc1e3018440668/oscm-portal/WebContent/shop/customFeaturedServices.xhtml#L57)):_
> 
> > ```
> >     </rich:pickList>
> > ```
> 
> We should in general avoid inline styles as it makes harder the css stylesheet maintainance and the clear separation of view and model. Instead, you can define a class in portal. css and then define the div as such: <div class="fillinDiv fitContentDiv" or so.


Done

**Review by farmakiG — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/674#-:-M0qg3DyAIy3UGlOTmVy:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @farmakiG)

**Pull request merged**
