### PR TITLE
Task#1011 standarization of marketplace appearence

### LINKED ISSUE #1011: Standardization of marketplace appearance
**Summary**
All form elements should have bootstrap styles (buttons, inputs, test areas, select menu)
Form approval buttons should have one consistent appearance on all pages - they should be on the right
Improving the style of some pages - pages should be as readable as possible, and the links on it should stand out from the text

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Change all inputs, textareas and select menu to bootstrap styles
- Fixed styles in service card
- Change pagination for service browse to smaller
- Change PopUps which are has scrolls or not bootstrap buttons
- Add some paddings, margins, bolds
- Align user menu in navbar

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- ci:9

**Screenshot (if applicable):**

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1012)

### CODE REVIEW

**Review by GoebelL — COMMENTED** [review]
> Reviewed 2 of 47 files at r1, 2 of 31 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1012)* status: 4 of 53 files reviewed, all discussions resolved (waiting on @farmakiG and @GoebelL)

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 2 of 31 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1012)* status: 6 of 53 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @KabacinskiPiotr)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/tagCloudLink.xhtml, line 16 at r2](https://reviewable.io/reviews/servicecatalog/oscm/1012#-MCBGJzk7Vo_oGNM3UZ8:-MCBGJzk7Vo_oGNM3UZ9:b-rc28j3) ([raw file](https://github.com/servicecatalog/oscm/blob/18af0eada98d5a31be5be347906777e66f990a3d/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/tagCloudLink.xhtml#L16)):*
> ```HTML
>         <f:setPropertyActionListener target="#{servicePagingBean.filterCategoryForDisplay}" value=""/>
>         <h:outputText
>             styleClass="#{tag.name eq servicePagingBean.filterTagForDisplay ? 'bg-secondary text-white p-1 rounded-pill' : ''}"
> ```


Instead of adding further specific bootstrap classes, I prefer custom classes, something like tagCloudLink etc. in mp.scss that uses bootstrap variables which the user can customize.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 11 of 47 files at r1, 21 of 31 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1012)* status: 36 of 53 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @KabacinskiPiotr)

**Comment by Piotr-K8i** [comment]
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/tagCloudLink.xhtml, line 16 at r2](https://reviewable.io/reviews/servicecatalog/oscm/1012#-MCBGJzk7Vo_oGNM3UZ8:-MCCTH0tC8ynSm57pxAG:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/18af0eada98d5a31be5be347906777e66f990a3d/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/tagCloudLink.xhtml#L16)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Instead of adding further specific bootstrap classes, I prefer custom classes, something like tagCloudLink etc. in mp.scss that uses bootstrap variables which the user can customize.
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 8 of 47 files at r1, 3 of 31 files at r2, 24 of 24 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1012)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @farmakiG)

**Review by farmakiG — APPROVED** [review]
> Reviewed 30 of 47 files at r1, 15 of 31 files at r2, 23 of 24 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1012)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
