### PR TITLE
Fix account navigation menu

### PR DESCRIPTION
**Pull request by GoebelL**
**Changes in this Pull Request:**
- Make account navigation bar working.
- Edit pen icon in account subscriptions table

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [X] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- ci10

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/906)

### CODE REVIEW

**Review by farmakiG — CHANGES_REQUESTED** [review]
> Reviewed 2 of 21 files at r4, 11 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/906)* status: 13 of 23 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @GoebelL)

___
*[tools/oscm-client/.gitignore, line 3 at r5](https://reviewable.io/reviews/servicecatalog/oscm/906#-M8scOe03eQtA2xYtsFu:-M8scOe15YXWAPxXf0lz:bsmn40c) ([raw file](https://github.com/servicecatalog/oscm/blob/4ff61404b4c0557a8c18a868b1372df871e43273/tools/oscm-client/.gitignore#L3)):*
> ```ignore
> # IntelliJ
> *.iml
> *.iws
> ```

do you need to commit .gitignore?

**Review by farmakiG — COMMENTED** [review]
> Reviewed 2 of 21 files at r4, 7 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/906)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @GoebelL)

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/906)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[tools/oscm-client/.gitignore, line 3 at r5](https://reviewable.io/reviews/servicecatalog/oscm/906#-M8scOe03eQtA2xYtsFu:-M8t6SHXDf4tuVhmUsDd:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/4ff61404b4c0557a8c18a868b1372df871e43273/tools/oscm-client/.gitignore#L3)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

do you need to commit .gitignore?
</blockquote></details>

Done.

**Review by farmakiG — APPROVED** [review]
> Reviewed 1 of 21 files at r4, 1 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/906)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
