### PR TITLE
Task/479

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
- Created new tag for responsive horizontal categories bar

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [x] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [ ] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
N/A

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/777)

### CODE REVIEW

**Review by farmakiG — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/777)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/taglib.xml, line 213 at r2](https://reviewable.io/reviews/servicecatalog/oscm/777#-M4NQ4h-0U6V4OXGRc2S:-M4NQ4h01-c8p9Lt9Mxg:b-92btgr) ([raw file](https://github.com/servicecatalog/oscm/blob/b7dc18fc76e168231eb9aebf5608aa401c127e01/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/taglib.xml#L213)):*
> ```XML
>     <source>tagCloudBootstrap.xhtml</source>
>   </tag>
>   <tag>
> ```

Maybe you can shorten a bit the name, for example: categorySelectionBootstrap. Or you need another categorySelection for the Services page as well?

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/777)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/taglib.xml, line 213 at r2](https://reviewable.io/reviews/servicecatalog/oscm/777#-M4NQ4h-0U6V4OXGRc2S:-M4NUW4x4Kcm79FoLtIN:bzdjpqn) ([raw file](https://github.com/servicecatalog/oscm/blob/b7dc18fc76e168231eb9aebf5608aa401c127e01/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/taglib.xml#L213)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Maybe you can shorten a bit the name, for example: categorySelectionBootstrap. Or you need another categorySelection for the Services page as well?
</blockquote></details>

Yes, currenly the service page is using diffretent cateory selection.

**Review by farmakiG — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/777)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @mchudy-fujitsu)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/categorySelectionLandingBootstrap.xhtml, line 44 at r2](https://reviewable.io/reviews/servicecatalog/oscm/777#-M4N_kgc8YuxDttCwyJL:-M4N_kgc8YuxDttCwyJM:bvuzcs0) ([raw file](https://github.com/servicecatalog/oscm/blob/b7dc18fc76e168231eb9aebf5608aa401c127e01/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/categorySelectionLandingBootstrap.xhtml#L44)):*
> ```HTML
>         </div>
>       </div>
>     </div>
> ```

The Browse Service and the Text of Categories, when displayed vertically, should be aligned to the left.

**Review by farmakiG — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/777)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @mchudy-fujitsu)

**Review by farmakiG — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/777)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
