### PR TITLE
Task/improve app related ui test

### PR DESCRIPTION
**Pull request by Piotr-K8i**
Summary
APP is purely tested within current UI tests. It includes logging in to the main app configuration and registering new controller. Additionally it works directly on the db, which should not be the case as we can configure everything using UI.

Details
Let's include following improvements:
- additional scenarios for logging the user to all default controllers provided within oscm-app (openstack, azure, vmware, aws) with some basic actions on its configuration page
- additional scenario for configuring newly created organization as the owner of one of the existing controllers (including logging in with the new user credentials)
- remove all the code related to the direct DB operations
- organize APP related tests and base code in separate packages

Acceptance criteria
- [ ] number of APP related test is improved according to the description above
- [ ]  all test are running successfully

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/649)

### CODE REVIEW

**Comment by Piotr-K8i** [comment]
Link to [Jenkins](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Integration_Tests_Upgrade/191/) with passed tests

**Review by kowalczyka — CHANGES_REQUESTED** [review]
There are some confilcts with master branch. Please resolve this.

Additionally link to Jenkins build is not existing.

**Comment by Piotr-K8i** [comment]
> There are some confilcts with master branch. Please resolve this.
> 
> Additionally link to Jenkins build is not existing.

All conflicts with master resolved

Here is another link with Jenkins build [Jenkins](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Integration_Tests_Upgrade/191/)

**Review by kowalczyka — CHANGES_REQUESTED** [review]
> Reviewed 5 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/649)* status: 4 of 14 files reviewed, 10 unresolved discussions (waiting on @KabacinskiPiotr and @kowalczyka)

___
*[oscm-ui-tests/src/main/java/org/oscm/webtest/app/AppServiceInstanceTester.java, line 28 at r1](https://reviewable.io/reviews/servicecatalog/oscm/649#-M-xsWYWDDZ9_KqRP2_Y:-M-xsWYWDDZ9_KqRP2_Z:b-wey6ye) ([raw file](https://github.com/servicecatalog/oscm/blob/09251fb6316770957a974859d2eca0b3c8b8e403/oscm-ui-tests/src/main/java/org/oscm/webtest/app/AppServiceInstanceTester.java#L28)):*
> ```Java
>   protected static final Logger logger = LogManager.getLogger(WebTester.class.getName());
> 
>   public AppServiceInstanceTester() throws Exception {
> ```

Name of the calss is misleading - please change it to AppControllerTester
___
*[oscm-ui-tests/src/main/java/org/oscm/webtest/app/AppServiceInstanceTester.java, line 30 at r1](https://reviewable.io/reviews/servicecatalog/oscm/649#-M-xrlk8DLrYif4tUFcJ:-M-xrVlkEW3WLmyyy8O9:b-z87ode) ([raw file](https://github.com/servicecatalog/oscm/blob/09251fb6316770957a974859d2eca0b3c8b8e403/oscm-ui-tests/src/main/java/org/oscm/webtest/app/AppServiceInstanceTester.java#L30)):*
> ```Java
>   public AppServiceInstanceTester() throws Exception {
>     super();
> ```

This logic for loading the url with https or http is irrelevant as we always secure version. Please adapt this so that https is alway used. Please do the same in AppTester.
___
*[oscm-ui-tests/src/main/java/org/oscm/webtest/app/AppServiceInstanceTester.java, line 49 at r1](https://reviewable.io/reviews/servicecatalog/oscm/649#-M-xsuE15IHprHpZpZHK:-M-xsuE15IHprHpZpZHL:b-5hp7m4) ([raw file](https://github.com/servicecatalog/oscm/blob/09251fb6316770957a974859d2eca0b3c8b8e403/oscm-ui-tests/src/main/java/org/oscm/webtest/app/AppServiceInstanceTester.java#L49)):*
> ```
> loginAppServiceInstance
> ```
Let's change the method name to loginAppController
___
*[oscm-ui-tests/src/test/java/org/oscm/app/AppConfigurationWT.java, line 33 at r1](https://reviewable.io/reviews/servicecatalog/oscm/649#-M-xtau_0j4B55Fbw30E:-M-xtau_0j4B55Fbw30F:bs30e73) ([raw file](https://github.com/servicecatalog/oscm/blob/09251fb6316770957a974859d2eca0b3c8b8e403/oscm-ui-tests/src/test/java/org/oscm/app/AppConfigurationWT.java#L33)):*
> ```Java
>   public static void setup() throws Exception {
>     tester = new AppTester();
>     String userid = tester.getPropertie(AppTester.APP_ADMIN_USER_ID);
> ```

Please use camelCase for variable names
___
*[oscm-ui-tests/src/test/java/org/oscm/app/AppControllerAWS.java, line 13 at r1](https://reviewable.io/reviews/servicecatalog/oscm/649#-M-xu1Pp47IL-ors1AT4:-M-xu1Pp47IL-ors1AT5:b-m7hcj0) ([raw file](https://github.com/servicecatalog/oscm/blob/09251fb6316770957a974859d2eca0b3c8b8e403/oscm-ui-tests/src/test/java/org/oscm/app/AppControllerAWS.java#L13)):*
> ```Java
> 
> @FixMethodOrder(MethodSorters.NAME_ASCENDING)
> public class AppControllerAWS {
> ```

Please keep the same notation for all tests classes name (WT suffix)
___
*[oscm-ui-tests/src/test/java/org/oscm/app/AppControllerAzure.java, line 12 at r1](https://reviewable.io/reviews/servicecatalog/oscm/649#-M-xuWJdDNeojBCMysKD:-M-xuWJdDNeojBCMysKE:b-7ropln) ([raw file](https://github.com/servicecatalog/oscm/blob/09251fb6316770957a974859d2eca0b3c8b8e403/oscm-ui-tests/src/test/java/org/oscm/app/AppControllerAzure.java#L12)):*
> ```Java
> 
> @FixMethodOrder(MethodSorters.NAME_ASCENDING)
> public class AppControllerAzure {
> ```

ditto
___
*[oscm-ui-tests/src/test/java/org/oscm/app/AppControllerOpenstack.java, line 19 at r1](https://reviewable.io/reviews/servicecatalog/oscm/649#-M-xuXi0BgBRq06i2nAA:-M-xuXi0BgBRq06i2nAB:b-7ropln) ([raw file](https://github.com/servicecatalog/oscm/blob/09251fb6316770957a974859d2eca0b3c8b8e403/oscm-ui-tests/src/test/java/org/oscm/app/AppControllerOpenstack.java#L19)):*
> ```Java
> 
> @FixMethodOrder(MethodSorters.NAME_ASCENDING)
> public class AppControllerOpenstack {
> ```

ditto
___
*[oscm-ui-tests/src/test/java/org/oscm/app/AppControllerVCenter.java, line 19 at r1](https://reviewable.io/reviews/servicecatalog/oscm/649#-M-xuZN99TT5ZGQy9NLH:-M-xuZNA5l5rit1-dlwT:b-7ropln) ([raw file](https://github.com/servicecatalog/oscm/blob/09251fb6316770957a974859d2eca0b3c8b8e403/oscm-ui-tests/src/test/java/org/oscm/app/AppControllerVCenter.java#L19)):*
> ```Java
> 
> @FixMethodOrder(MethodSorters.NAME_ASCENDING)
> public class AppControllerVCenter {
> ```

ditto
___
*[oscm-ui-tests/src/test/java/org/oscm/portal/JUnitHelper.java, line 17 at r1](https://reviewable.io/reviews/servicecatalog/oscm/649#-M-xuml4-j0qReypuUl6:-M-xuml4-j0qReypuUl7:b-xs04yp) ([raw file](https://github.com/servicecatalog/oscm/blob/09251fb6316770957a974859d2eca0b3c8b8e403/oscm-ui-tests/src/test/java/org/oscm/portal/JUnitHelper.java#L17)):*
> ```Java
> import org.junit.runner.Description;
> 
> public class JUnitHelper extends TestWatcher {
> ```

Please keep the formatting style.
___
*[oscm-ui-tests/src/main/java/org/oscm/webtest/app/AppPathSegments.java, line 14 at r1](https://reviewable.io/reviews/servicecatalog/oscm/649#-M-xpqoZ7zuFWqTeUI5f:-M-xpqo_CV9rTfS2RXeA:b-c9zg6g) ([raw file](https://github.com/servicecatalog/oscm/blob/09251fb6316770957a974859d2eca0b3c8b8e403/oscm-ui-tests/src/main/java/org/oscm/webtest/app/AppPathSegments.java#L14)):*
> ```Java
> public class AppPathSegments {
>   public static final String APP_CONFIGURATION = "/oscm-app/default.jsf";
>   public static final String APP_SERVICE_INSTANCE = "/oscm-app";
> ```

The field name APP_SERVICE_INSTANCE is misleading. Let's use here separate static field for every controller e.g APP_CONTROLLER_AWS = "/oscm-app-aws"

**Comment by Piotr-K8i** [comment]
Link for [Jenkins](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Integration_Tests_Upgrade/224/) build

**Review by kowalczyka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1, 13 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/649)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @KabacinskiPiotr and @kowalczyka)

___
*[oscm-ui-tests/src/main/java/org/oscm/webtest/app/AppTester.java, line 34 at r2](https://reviewable.io/reviews/servicecatalog/oscm/649#-M0MkUGC2UwfXPvq4EH1:-M0MkUGD2vwZR0YiUuX5:b-3rydvn) ([raw file](https://github.com/servicecatalog/oscm/blob/f44f20ffb2318b9375201c9f73889300ddb0222a/oscm-ui-tests/src/main/java/org/oscm/webtest/app/AppTester.java#L34)):*
> ```Java
>     super();
> 
>     baseUrl = loadUrl(APP_SECURE, APP_HTTPS_URL, APP_HTTP_URL);
> ```

Please refactor loadUrl method - it should always load one property (url with https). Cleanup http related properties.

**Comment by Piotr-K8i** [comment]
> > Reviewed 1 of 14 files at r1, 13 of 14 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/649)_ status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @KabacinskiPiotr and @kowalczyka)
> 
> _[oscm-ui-tests/src/main/java/org/oscm/webtest/app/AppTester.java, line 34 at r2](https://reviewable.io/reviews/servicecatalog/oscm/649#-M0MkUGC2UwfXPvq4EH1:-M0MkUGD2vwZR0YiUuX5:b-3rydvn) ([raw file](https://github.com/servicecatalog/oscm/blob/f44f20ffb2318b9375201c9f73889300ddb0222a/oscm-ui-tests/src/main/java/org/oscm/webtest/app/AppTester.java#L34)):_
> 
> > ```java
> >     super();
> > 
> >     baseUrl = loadUrl(APP_SECURE, APP_HTTPS_URL, APP_HTTP_URL);
> > ```
> 
> Please refactor loadUrl method - it should always load one property (url with https). Cleanup http related properties.

Done -> new [Jenkins](http://10.140.16.80:8080/job/OSCM_Integration_Tests_Upgrade/231/) build

**Review by kowalczyka — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/649#-:-M0RYgHM7EQ_DuSfR2yH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
