### PR TITLE
Styling Update for Categories and Tag Filters

### LINKED ISSUE #935: Styling issues with navigation items (categories, navigation menu and tag cloud links)
**Summary**
Small issues found in new marketplace UI 

**Details**
- Categories bar needs styling improvement
- Navigation menu also shows links which should be invisible. E.g. unit menu is offered also for user who don't have permissions to manage units.
- Selected tag cloud link is not distinguish-able for other links. The selected one should emphisized, highlighted or else.

 **Acceptance criteria**
- [ ] Tag could provides visual feedback of which tag link is selected, if any.
- [ ] Navigation menu doesn't show groups menu if user is unauthorized for managing groups.
- [ ] Categories bar on the landing page has full width and categories width is responsive

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by GoebelL**
**Changes in this Pull Request:**
- Don't render invisible links in navigation menu (side fix)
- Polished category bar and tag cloud link styling

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [X] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [X] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- ci10:v18
**Screenshot (if applicable):**
Desktop view:
image

image

Small view:
image

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/931)

### CODE REVIEW

**Review by Piotr-K8i — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/931)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @GoebelL and @KabacinskiPiotr)

___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 3552 at r3](https://reviewable.io/reviews/servicecatalog/oscm/931#-MA5RwDe0nkJkAHFb1Bn:-MA5RwDe0nkJkAHFb1Bo:bq3kd3) ([raw file](https://github.com/servicecatalog/oscm/blob/f3441226c5a063026ccb9519021329cedeff7572/oscm-portal/WebContent/marketplace/css/mp.css#L3552)):*
> ```CSS
>   max-height: 30px;
>   font-size: 0.8rem;
>   vertical-align: middle !important;
> ```

`text-align: center;`

___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 3579 at r3](https://reviewable.io/reviews/servicecatalog/oscm/931#-MA5U4_WE3h9RAqtMi8p:-MA5U4_WE3h9RAqtMi8q:bizzpab) ([raw file](https://github.com/servicecatalog/oscm/blob/f3441226c5a063026ccb9519021329cedeff7572/oscm-portal/WebContent/marketplace/css/mp.css#L3579)):*
> ```CSS
>   display: block;
>   margin: 2px 0 0 0; }
> ```

```
.img-fluid {
  width: -webkit-fill-available;}
```

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/categorySelectionLandingBootstrap.xhtml, line 11 at r3](https://reviewable.io/reviews/servicecatalog/oscm/931#-MA5Y2QR6ECSNHvFjs9o:-MA5Y2QR6ECSNHvFjs9p:b-ltwt7c) ([raw file](https://github.com/servicecatalog/oscm/blob/f3441226c5a063026ccb9519021329cedeff7572/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/categorySelectionLandingBootstrap.xhtml#L11)):*
> ```HTML
>     <div class="col-12 mt-0 p-0 ">
>       <div class="list-group list-group-horizontal-lg align-items-center">
>

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/931)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @GoebelL and @KabacinskiPiotr)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/categorySelectionLandingBootstrap.xhtml, line 11 at r3](https://reviewable.io/reviews/servicecatalog/oscm/931#-MA5Y2QR6ECSNHvFjs9o:-MA5Zdf45aiaaIVuLODT:b-ozllki) ([raw file](https://github.com/servicecatalog/oscm/blob/f3441226c5a063026ccb9519021329cedeff7572/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/categorySelectionLandingBootstrap.xhtml#L11)):*
<details><summary><i>Previously, KabacinskiPiotr wrote…</i></summary><blockquote>

Can you enter why it was commented on?
</blockquote></details>

It was not desired to keep. We don't need such button with same link on the landing page, as we already have a sticky header bar with the link to browse all services.

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/931)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @KabacinskiPiotr)

___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 3552 at r3](https://reviewable.io/reviews/servicecatalog/oscm/931#-MA5RwDe0nkJkAHFb1Bn:-MA5jVhS55jwckzNcBwF:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/f3441226c5a063026ccb9519021329cedeff7572/oscm-portal/WebContent/marketplace/css/mp.css#L3552)):*
<details><summary><i>Previously, KabacinskiPiotr wrote…</i></summary><blockquote>

text-align: center;


</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 3579 at r3](https://reviewable.io/reviews/servicecatalog/oscm/931#-MA5U4_WE3h9RAqtMi8p:-MA5jZ7TBn6C1E2xkuab:busa43a) ([raw file](https://github.com/servicecatalog/oscm/blob/f3441226c5a063026ccb9519021329cedeff7572/oscm-portal/WebContent/marketplace/css/mp.css#L3579)):*
<details><summary><i>Previously, KabacinskiPiotr wrote…</i></summary><blockquote>

.img-fluid {
  width: -webkit-fill-available;}


</blockquote></details>

  width: -webkit-fill-available;
isn't related and doesn't have effect as its overriden by bootstrap _images.scss in line 8.
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/categorySelectionLandingBootstrap.xhtml, line 11 at r3](https://reviewable.io/reviews/servicecatalog/oscm/931#-MA5Y2QR6ECSNHvFjs9o:-MA5l1ML5645jztsoyLF:b-ynwl21) ([raw file](https://github.com/servicecatalog/oscm/blob/f3441226c5a063026ccb9519021329cedeff7572/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/categorySelectionLandingBootstrap.xhtml#L11)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

It was not desired to keep. We don't need such button with same link on the landing page, as we already have a sticky header bar with the link to browse all services. 
</blockquote></details>

I removed it.

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/931)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @KabacinskiPiotr)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/categorySelectionLandingBootstrap.xhtml, line 11 at r3](https://reviewable.io/reviews/servicecatalog/oscm/931#-MA5Y2QR6ECSNHvFjs9o:-MA5l6666Gv0ypCdP_p0:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/f3441226c5a063026ccb9519021329cedeff7572/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/categorySelectionLandingBootstrap.xhtml#L11)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

I removed it.
</blockquote></details>

Done.

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/931)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @KabacinskiPiotr)

___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 3579 at r3](https://reviewable.io/reviews/servicecatalog/oscm/931#-MA5U4_WE3h9RAqtMi8p:-MA5l9Q9BNwuhbd-cN11:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/f3441226c5a063026ccb9519021329cedeff7572/oscm-portal/WebContent/marketplace/css/mp.css#L3579)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

  width: -webkit-fill-available;
isn't related and doesn't have effect as its overriden by bootstrap _images.scss in line 8.

</blockquote></details>

Done.

**Review by Piotr-K8i — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 4 files at r2, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/931)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @KabacinskiPiotr)

**Pull request merged**
