### PR TITLE
Customize service cards

### LINKED ISSUE #993: Customized Service Cards
**Summary**
Customize with Sass the Service Cards.

**Details**
Provide the ability to customize the layout of the Service Cards appearing in the public MP page.
The following things must be customizable: color, border of cards (style, border-radius), padding, margins and layout of icons.

Furthermore, the number of cards that are displayed depending on the screen width must be customizable.
So, the following line must be replaced by a customizable class in Sass: 
<div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 mb-4">

**Acceptance criteria**
- [ ] A new file: _serviceCardsCustom.scss included in branding package.
- [ ] Few variables added in _myvariables.scss 
- [ ] This file is imported in _darkCustom.scss
- [ ] darkCustom.css is generated and included in headBootstrap.css.
- [ ] Manual tests  for different layouts.

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- custom gridLayoutForCard
-Cards variables.
-Default Fonts

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [X] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**

Landing page

Screenshot_2020-07-08 Marketplace(3)

- Rounded list groups

Screenshot_2020-07-08 Marketplace(6)

Screenshot_2020-07-08 Marketplace(7)

- Button shadows
Screenshot_2020-07-08 Marketplace(4)
Screenshot_2020-07-08 Marketplace(2)

Screenshot_2020-07-08 Marketplace(5)

- Tooltips
Screenshot popover

- Dropdowns with rounded corners
Dropdown Sorting

Dropdown Navbar

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1009)

### CODE REVIEW

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1009)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-portal/WebContent/marketplace/scss/_variables.scss, line 6 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1009#-MBmWy647-yGyluRNFCk:-MBmWy647-yGyluRNFCl:b-9jjxq7) ([raw file](https://github.com/servicecatalog/oscm/blob/781ee58dbe7bdcdc4ac202a34a44e68474df4fb4/oscm-portal/WebContent/marketplace/scss/_variables.scss#L6)):*
> ```SCSS
> $interior-color: #fff;
> 
> $font-family-sans-serif: "OpenSansRegular", Arial, Verdana, "Lucida Grande", '´╝¡´╝│ ´╝░Òé┤ÒéÀÒââÒé»', 'ÒâÆÒâ®Òé«ÒâÄÞºÆÒé┤ Pro W3', sans-serif;;
> ```

I guess encoding got broken. Ensure your editor is saving with UTF-8.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1009)* status: 1 of 20 files reviewed, 2 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal/WebContent/marketplace/customBootstrap/scss/_myvariablesExtended.scss, line 3 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1009#-MBmXsj4AhJR_7MLVXnw:-MBmXsj4AhJR_7MLVXnx:bb17k7j) ([raw file](https://github.com/servicecatalog/oscm/blob/781ee58dbe7bdcdc4ac202a34a44e68474df4fb4/oscm-portal/WebContent/marketplace/customBootstrap/scss/_myvariablesExtended.scss#L3)):*
> ```SCSS
> /* -------begin customization-------- *//* change the fonts, and primary theme color to green  */
> @import "myvariables";
> ```

Instead packaging additional customization files, lets keep the assets in GitHub and add a nice online description, e.g. as GitHub readme.md.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 11 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1009)* status: 12 of 20 files reviewed, 4 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 194 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1009#-MBmYwIa-Pf_OUZIDfOc:-MBmYwIa-Pf_OUZIDfOd:bb7eybp) ([raw file](https://github.com/servicecatalog/oscm/blob/781ee58dbe7bdcdc4ac202a34a44e68474df4fb4/oscm-portal/WebContent/marketplace/css/mp.css#L194)):*
> ```CSS
> h1, h2, h3, h4, h5, h6 {
>   margin: 0;
>   /* font: normal 100% "OpenSansRegular", Arial, Verdana, "Lucida Grande", '´╝¡´╝│ ´╝░Òé┤ÒéÀÒââÒé»', 'ÒâÆÒâ®Òé«ÒâÄÞºÆÒé┤ Pro W3', sans-serif; */
> ```

dito
___
*[oscm-portal/WebContent/marketplace/customBootstrap/scss/darkCustom.scss, line 7 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1009#-MBmZDjgAKXBkzV7GXQA:-MBmZDjgAKXBkzV7GXQB:b-a8bude) ([raw file](https://github.com/servicecatalog/oscm/blob/781ee58dbe7bdcdc4ac202a34a44e68474df4fb4/oscm-portal/WebContent/marketplace/customBootstrap/scss/darkCustom.scss#L7)):*
> ```SCSS
> 
> /* -------begin customization-------- *//* change the fonts, and primary theme color to green  */
> @import "myvariablesExtended";
> ```

 In my understanding we want to compile darkCustom.scss and package it in portal, don't we?
This change means this "extended style" will be always used by default? No, please change.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1009)* status: 13 of 20 files reviewed, 4 unresolved discussions (waiting on @farmakiG)

**Review by GoebelL — COMMENTED** [review]
> Reviewed 5 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1009)* status: 18 of 20 files reviewed, 4 unresolved discussions (waiting on @farmakiG)

**Comment by GoebelL** [comment]
Hi @farmakiG 

one additional point. Referring to the acceptance criteria in the GitHub issue #993, I am missing dedicated service card customization. In particular _serviceCardsCustom.scss.  How about this? Did you drop it?

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1009)* status: 12 of 21 files reviewed, 3 unresolved discussions (waiting on @farmakiG and @GoebelL)

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1009)* status: 12 of 21 files reviewed, 3 unresolved discussions (waiting on @farmakiG and @GoebelL)

___
*[oscm-portal/WebContent/marketplace/css/mp.css, line 194 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1009#-MBmYwIa-Pf_OUZIDfOc:-MBmrW0LDV2OCNp7OS8u:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/781ee58dbe7bdcdc4ac202a34a44e68474df4fb4/oscm-portal/WebContent/marketplace/css/mp.css#L194)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

dito
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/customBootstrap/scss/darkCustom.scss, line 7 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1009#-MBmZDjgAKXBkzV7GXQA:-MBmrkiT5zejQkCxqa61:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/781ee58dbe7bdcdc4ac202a34a44e68474df4fb4/oscm-portal/WebContent/marketplace/customBootstrap/scss/darkCustom.scss#L7)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

 In my understanding we want to compile darkCustom.scss and package it in portal, don't we?
This change means this "extended style" will be always used by default? No, please change.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/scss/_variables.scss, line 6 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1009#-MBmWy647-yGyluRNFCk:-MBmsWzcEgEA5aT1xt-e:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/781ee58dbe7bdcdc4ac202a34a44e68474df4fb4/oscm-portal/WebContent/marketplace/scss/_variables.scss#L6)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

I guess encoding got broken. Ensure your editor is saving with UTF-8.
</blockquote></details>

Done.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 3 of 10 files at r3, 6 of 6 files at r4, 5 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1009)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
