### PR TITLE
Sass branch

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- Added scss folder located under marketplace with initial mp.scss file and _variables.scss file.
-Added README instructions for Compilation of Sass files.
-Removed scss folder located under resources with initial custom.scss example.

**Mandatory checks:**
- [X] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [X] changes were tested manually
- [ ] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [ ] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM Build And Push job]: http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Docker_Build_and_push/617/

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/751)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/751)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @farmakiG, @GoebelL, and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/scss/mp.scss, line 10 at r5](https://reviewable.io/reviews/servicecatalog/oscm/751#-M3k5DTV4aS28kfaCJeP:-M3k5DTV4aS28kfaCJeQ:b-2jt5ox) ([raw file](https://github.com/servicecatalog/oscm/blob/46cb4287e4f076bf74cd356506c26089e0397440/oscm-portal/WebContent/marketplace/scss/mp.scss#L10)):*
> ```SCSS
> /* --------------------------------------------------------------------
> 
> Copyright 2010-2012 FUJITSU LIMITED
> ```

Update year
___
*[oscm-portal/WebContent/marketplace/scss/mp.scss, line 78 at r5](https://reviewable.io/reviews/servicecatalog/oscm/751#-M3k3Vj96RgH21M9UXRX:-M3k3Vj96RgH21M9UXRY:bnw522z) ([raw file](https://github.com/servicecatalog/oscm/blob/46cb4287e4f076bf74cd356506c26089e0397440/oscm-portal/WebContent/marketplace/scss/mp.scss#L78)):*
> ```SCSS
> 		
> 	9 Footer
> ```

Of course it's a goal to reduce the mp.css content. Nevertheless, good structuring is essential for keeping overview. 
For all new bootstrap related styles, I suggest to append TOC entries here and respective sections at the end of this file.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/751)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @farmakiG, @GoebelL, and @mchudy-fujitsu)

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/751)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @GoebelL and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/scss/mp.scss, line 10 at r5](https://reviewable.io/reviews/servicecatalog/oscm/751#-M3k5DTV4aS28kfaCJeP:-M3kDiwBD9AJb_amLo4T:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/46cb4287e4f076bf74cd356506c26089e0397440/oscm-portal/WebContent/marketplace/scss/mp.scss#L10)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Update year
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/scss/mp.scss, line 78 at r5](https://reviewable.io/reviews/servicecatalog/oscm/751#-M3k3Vj96RgH21M9UXRX:-M3p-blD-jUAcVbR-KJr:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/46cb4287e4f076bf74cd356506c26089e0397440/oscm-portal/WebContent/marketplace/scss/mp.scss#L78)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Of course it's a goal to reduce the mp.css content. Nevertheless, good structuring is essential for keeping overview. 
For all new bootstrap related styles, I suggest to append TOC entries here and respective sections at the end of this file. 
</blockquote></details>

Done.

**Review by mchudy-fujitsu — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/751#-:-M3u7Ogx2aGy74DRtPbY:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @GoebelL)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/751)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
