### PR TITLE
Task #673 Highlight of label next to Dropdown.

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
Create template for Bootsfaces selectOneMenu

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [ ] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM Build And Push job](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Docker_Build_and_push/522/)
- [OSCM Pull And Start job](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Update_oscm_core/468/)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/684)

[Link with started node on this branch](http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Docker_pull_and_start/866/)

[Link with internal test for this branch](http://10.140.16.80:8080/job/OSCM_Integration_Tests_INTERNAL/)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/684)* status: 0 of 35 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @KabacinskiPiotr)

___
*[oscm-portal/javasrc/org/oscm/ui/beans/GotoMarketplaceBean.java, line 22 at r2](https://reviewable.io/reviews/servicecatalog/oscm/684#-M1VOfFW-42p-iZx_2Ia:-M1VOfFXAsdP4FWTpx5_:bgswh90) ([raw file](https://github.com/servicecatalog/oscm/blob/0f38fbb2619a024f992d9ecb0d13fda578c8160d/oscm-portal/javasrc/org/oscm/ui/beans/GotoMarketplaceBean.java#L22)):*
> ```Java
> import javax.faces.component.UIOutput;
> import javax.faces.event.AjaxBehaviorEvent;
> import javax.faces.event.ValueChangeEvent;
> ```

Please remove if not needed.

**Comment by Piotr-K8i** [comment]
Jenkins jobs for UI tests:
[**master**](http://10.140.16.80:8080/job/OSCM_Integration_Tests_Upgrade/242/)
[**My branch**](http://10.140.16.80:8080/job/OSCM_Integration_Tests_Upgrade/241/)

**Review by Piotr-K8i — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/684)* status: 0 of 37 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @GoebelL)

___
*[oscm-portal/javasrc/org/oscm/ui/beans/GotoMarketplaceBean.java, line 22 at r2](https://reviewable.io/reviews/servicecatalog/oscm/684#-M1VOfFW-42p-iZx_2Ia:-M1_heFX0AcDP-CXLPS2:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/0f38fbb2619a024f992d9ecb0d13fda578c8160d/oscm-portal/javasrc/org/oscm/ui/beans/GotoMarketplaceBean.java#L22)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Please remove if not needed.
</blockquote></details>

Done.

**Review by farmakiG — DISMISSED** [review]
> Reviewed 10 of 24 files at r1, 17 of 25 files at r2, 17 of 17 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/684)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Pull request merged**
