### PR TITLE
Add ant steps for remove, create, compile and compress mp.scss file

### LINKED ISSUE #1076: Remove generated css from version control
**Summary**
scss generated files must be removed from version control to avoid checkout conflicts in local git workspaces

**Details**
Find generated files, like the files mp.css, mp.min.css and mp.css.map in oscm-portal/WebContent/marketplace/css and put them to .gitignore
 
**Acceptance criteria**
- [ ] No generated files in version controll
- [ ] Build is complete (check if scss generation step needs to be added to produce complete build artifacts)

**Additional context**
Ask me

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- Add ant steps for remove, create, compile and compress mp.scss file

### To redeploy oscm-core on Windows, install dart-sass

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [x] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [x] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [x] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell

**Screenshot (if applicable):**
- add a screenshot illustrating your change

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1086)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1086)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)

___
*[oscm-build/defaultprojectbuild.xml, line 192 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1086#-MIZqOeI7Ce0ZoAMilTl:-MIZqOeI7Ce0ZoAMilTm:b-twnbly) ([raw file](https://github.com/servicecatalog/oscm/blob/1da92aefae484ba6e19b08c5fa5e6a20c1f84db9/oscm-build/defaultprojectbuild.xml#L192)):*
> ```XML
> 
>   <target name="package" if="package.file.exists" depends="_init, compile, wsdl, javadoc, _licenses, package_hook">
>     <echo message="Done package build!" />
> ```

debug left over ?

**Review by Piotr-K8i — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1086)* status: 5 of 16 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @KabacinskiPiotr)

___
*[oscm-build/defaultprojectbuild.xml, line 192 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1086#-MIZqOeI7Ce0ZoAMilTl:-MJ0sq-N6Aw3GvF-lKz4:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/1da92aefae484ba6e19b08c5fa5e6a20c1f84db9/oscm-build/defaultprojectbuild.xml#L192)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

debug left over ?
</blockquote></details>

Done.

**Review by cworf91 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1086)* status: 5 of 16 files reviewed, 2 unresolved discussions (waiting on @cworf91, @GoebelL, and @KabacinskiPiotr)

___
*[oscm-build/build.xml, line 67 at r2](https://reviewable.io/reviews/servicecatalog/oscm/1086#-MJXG1kO2Zg737ERdomw:-MJXG-9aEVlyGhtiYAXc:b-eoeq6v) ([raw file](https://github.com/servicecatalog/oscm/blob/4e73bdda2839ef0883bd32355d82a28519712f4e/oscm-build/build.xml#L67)):*
> ```
> value="private-build-on-${hostname}" />
> ```
Please don´t use version numbers here. 2.4.7... If we change the version, it should happen on a central place. We usualy do this in the ivy-build.xml

**Review by cworf91 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1086)* status: 5 of 16 files reviewed, 3 unresolved discussions (waiting on @cworf91, @GoebelL, and @KabacinskiPiotr)

___
*[oscm-build/build.xml, line 439 at r2](https://reviewable.io/reviews/servicecatalog/oscm/1086#-MJXR8RK6zdY7jTv-YJF:-MJXR8RK6zdY7jTv-YJG:btf0yec) ([raw file](https://github.com/servicecatalog/oscm/blob/4e73bdda2839ef0883bd32355d82a28519712f4e/oscm-build/build.xml#L439)):*
> ```XML
>     <mkdir dir="${mp-dest}/customBootstrap/css" />
>     <echo message="Running sass executable against sass files and compiling to CSS directory [${mp-dest}] " />
>     <echo message="This step requires dart-sass installed on windows" />
> ```

So, dart-sass is required to get the build still running?

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1086)* status: 5 of 16 files reviewed, 4 unresolved discussions (waiting on @GoebelL and @KabacinskiPiotr)

___
*[oscm-build/build.xml, line 439 at r2](https://reviewable.io/reviews/servicecatalog/oscm/1086#-MJ_qhmh2ROytFQp333l:-MJ_qhmh2ROytFQp333m:b-km13h4) ([raw file](https://github.com/servicecatalog/oscm/blob/4e73bdda2839ef0883bd32355d82a28519712f4e/oscm-build/build.xml#L439)):*
> ```XML
>     <mkdir dir="${mp-dest}/customBootstrap/css" />
>     <echo message="Running sass executable against sass files and compiling to CSS directory [${mp-dest}] " />
>     <echo message="This step requires dart-sass installed on windows" />
> ```

...and "... installed on windows" ??

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1086)* status: 5 of 16 files reviewed, 4 unresolved discussions (waiting on @cworf91, @GoebelL, and @KabacinskiPiotr)

___
*[oscm-build/build.xml, line 67 at r2](https://reviewable.io/reviews/servicecatalog/oscm/1086#-MJXG1kO2Zg737ERdomw:-MJ_sMMh7F2obZDyOXl4:b-gwt8zl) ([raw file](https://github.com/servicecatalog/oscm/blob/4e73bdda2839ef0883bd32355d82a28519712f4e/oscm-build/build.xml#L67)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

> ```
> value="private-build-on-${hostname}" />
> ```
Please don´t use version numbers here. 2.4.7... If we change the version, it should happen on a central place. We usualy do this in the ivy-build.xml
</blockquote></details>

Use copy ANT task in ivy-build.xml to cut off the version number. For an example see [here](https://github.com/servicecatalog/oscm/blob/Task%231076_Remove_generated_css_from_version_control/oscm-build/ivy-build.xml#L403)

**Comment by Piotr-K8i** [comment]
> > _[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1086)_ status: 5 of 16 files reviewed, 4 unresolved discussions (waiting on @GoebelL and @KabacinskiPiotr)
> 
> _[oscm-build/build.xml, line 439 at r2](https://reviewable.io/reviews/servicecatalog/oscm/1086#-MJ_qhmh2ROytFQp333l:-MJ_qhmh2ROytFQp333m:b-km13h4) ([raw file](https://github.com/servicecatalog/oscm/blob/4e73bdda2839ef0883bd32355d82a28519712f4e/oscm-build/build.xml#L439)):_
> 
> > ```
> >     <mkdir dir="${mp-dest}/customBootstrap/css" />
> >     <echo message="Running sass executable against sass files and compiling to CSS directory [${mp-dest}] " />
> >     <echo message="This step requires dart-sass installed on windows" />
> > ```
> 
> ...and "... installed on windows" ??

on OS, I will change

We need to have dart-sass version on local device to update core from our laptops

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1086)* status: 5 of 16 files reviewed, 3 unresolved discussions (waiting on @cworf91, @GoebelL, and @KabacinskiPiotr)

___
*[oscm-build/build.xml, line 439 at r2](https://reviewable.io/reviews/servicecatalog/oscm/1086#-MJ_qhmh2ROytFQp333l:-MJbRoUWCAULgCZrzlHW:b-yv73lc) ([raw file](https://github.com/servicecatalog/oscm/blob/4e73bdda2839ef0883bd32355d82a28519712f4e/oscm-build/build.xml#L439)):*
<details><summary><i>Previously, KabacinskiPiotr wrote…</i></summary><blockquote>

on OS, I will change

We need to have dart-sass version on local device to update core from our laptops 
</blockquote></details>

Ok. 2 points on this:
1. We a need an update for the "how to build from source" instructions in the oscm repo readme.md.  A brief sentence in prerequisites section pointing to public online doc for setting up dart-saas. 
2. The _dependency target is not the appropriate location to place the sass complile target.
It's called in in many places which are completely unrelated to SASS and CSS. Let's better use the build hook which has been designed for such pre-compile task purpose. 

How to use it:
For the ANT invocation when calling BUILD.BES in oscm-devruntime/javares/build-oscmaas.xml, simply pass two arguments:
custom.build.dir and custom.build.hook, i.e. via VM arguments,
First is to set the local directory containing the ANT hook script and the second is the ANT target for the hook to be executed. The ANT file is expected to be named build.xml, I believe (which fits also in the given case).

**Review by GoebelL — APPROVED** [review]
> Reviewed 9 of 12 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1086)* status: all files reviewed, 2 unresolved discussions (waiting on @cworf91 and @KabacinskiPiotr)

**Review by GoebelL — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1086)* status: all files reviewed, 3 unresolved discussions (waiting on @cworf91 and @KabacinskiPiotr)

___
*[.gitignore, line 32 at r3](https://reviewable.io/reviews/servicecatalog/oscm/1086#-MJlE8og7yCEjQkA4LEb:-MJlE8og7yCEjQkA4LEc:bnmbg96) ([raw file](https://github.com/servicecatalog/oscm/blob/7fabb5069c10cdb43ae43c3df15044e1e3762ade/.gitignore#L32)):*
> ```
> oscm-portal/WebContent/marketplace/css
> ```

**Review by GoebelL — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1086)* status: all files reviewed, 3 unresolved discussions (waiting on @cworf91 and @KabacinskiPiotr)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1086)* status: all files reviewed, 2 unresolved discussions (waiting on @cworf91 and @KabacinskiPiotr)

**Pull request merged**
