### PR TITLE
Changes related to WS tests

### PR DESCRIPTION
**Pull request by kowalczyka**
**Changes in this Pull Request:**
- Configuration for running WS tests both in INTERNAL and OIDC mode

**OSCM Build References:**
http://10.140.16.80:8080/view/.MASTER/job/OSCM_WS_Tests_OIDC/
http://10.140.16.80:8080/view/.MASTER/job/OSCM_WS_Tests_INTERNAL/

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/597)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 27 of 98 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/597)* status: 27 of 98 files reviewed, 2 unresolved discussions (waiting on @GoebelL and @kowalczyka)

___
*[oscm-devruntime/javares/local/estessbesci11/test.properties, line 23 at r1](https://reviewable.io/reviews/servicecatalog/oscm/597#-LvoM4a31pt9mSYxiCXZ:-LvoM4a31pt9mSYxiCX_:bch6iok) ([raw file](https://github.com/servicecatalog/oscm/blob/666e61406c1ec85ffcb56421b725945d198715b1/oscm-devruntime/javares/local/estessbesci11/test.properties#L23)):*
> ```INI
> #user for SSO test
> sso.user.id=administrator
> sso.user.password=admin123
> ```

Where are these used? Looks like internal mode credential settings.
___
*[oscm-i18n/javares/Mail_en.properties, line 101 at r1](https://reviewable.io/reviews/servicecatalog/oscm/597#-LvoN-3w2uLmJW9v2rR2:-LvoN-3xEoRq62gO1Ahn:bn4ameg) ([raw file](https://github.com/servicecatalog/oscm/blob/666e61406c1ec85ffcb56421b725945d198715b1/oscm-i18n/javares/Mail_en.properties#L101)):*
> ```INI
> USER_CREATED.text=Your account has been created. Here is your login data\: \n\n\tURL\: {2}\n\n\tSecure URL\: {4}\n\n\tYour user ID is\: {0}\n\n\tYour initial password is\: {1}\n\n\tUser key for Web service access\: {3}
> USER_CREATED_SAML_SP.subject=Account created
> USER_CREATED_SAML_SP.text=Your account has been created. Here is your login data\: \n\n\tURL\: {1}\n\n\tSecure URL\: {2}\n\n\tYour user ID is\: {0}\n\n\tUser key for Web service access\: {3}
> ```

We need to keep sync with Mail_de.properties and Mail_ja.properties. Just find and copy this text from tailing sentence in respective USER_CREATED.text property, for instance in Mail_de.properties it is: Benutzer-ID f\u00FCr Web Service-Zugriff\: {3}

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 40 of 98 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/597)* status: 67 of 98 files reviewed, 3 unresolved discussions (waiting on @kowalczyka)

___
*[oscm-webservices-tests/javasrc/org/oscm/ws/IdentityServiceTest.java, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm/597#-LvoQAYNA488XUowvhSN:-LvoQAYO9Ci8RNH3g9ch:byjqrp1) ([raw file](https://github.com/servicecatalog/oscm/blob/666e61406c1ec85ffcb56421b725945d198715b1/oscm-webservices-tests/javasrc/org/oscm/ws/IdentityServiceTest.java#L1)):*
> ```Java
> package org.oscm.ws;
> ```

Please add FUJITSU copyright notice.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 26 of 98 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/597)* status: 93 of 98 files reviewed, 3 unresolved discussions (waiting on @kowalczyka)

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/597)* status: 93 of 99 files reviewed, 3 unresolved discussions (waiting on @GoebelL)

___
*[oscm-devruntime/javares/local/estessbesci11/test.properties, line 23 at r1](https://reviewable.io/reviews/servicecatalog/oscm/597#-LvoM4a31pt9mSYxiCXZ:-LvoUIUMAATqEo9xe6Ic:b-1dm7o9) ([raw file](https://github.com/servicecatalog/oscm/blob/666e61406c1ec85ffcb56421b725945d198715b1/oscm-devruntime/javares/local/estessbesci11/test.properties#L23)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Where are these used? Looks like internal mode credential settings.
</blockquote></details>

Looks like it was used in oscm-portal-webtests which is no longer in use. I would suggest to take care of it in separate task related to clenaup/removal as this settings exists in most of the configurations stored in oscm-devruntime.
___
*[oscm-i18n/javares/Mail_en.properties, line 101 at r1](https://reviewable.io/reviews/servicecatalog/oscm/597#-LvoN-3w2uLmJW9v2rR2:-LvoVS7p5JOGLL430VFC:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/666e61406c1ec85ffcb56421b725945d198715b1/oscm-i18n/javares/Mail_en.properties#L101)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

We need to keep sync with Mail_de.properties and Mail_ja.properties. Just find and copy this text from tailing sentence in respective USER_CREATED.text property, for instance in Mail_de.properties it is: Benutzer-ID f\u00FCr Web Service-Zugriff\: {3}
</blockquote></details>

Done.
___
*[oscm-webservices-tests/javasrc/org/oscm/ws/IdentityServiceTest.java, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm/597#-LvoQAYNA488XUowvhSN:-LvoVT8k0eLeJJVgR6KL:b-q0qrqw) ([raw file](https://github.com/servicecatalog/oscm/blob/666e61406c1ec85ffcb56421b725945d198715b1/oscm-webservices-tests/javasrc/org/oscm/ws/IdentityServiceTest.java#L1)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Please add FUJITSU copyright notice.
</blockquote></details>

Removed as it was only created for some initail testing

**Review by GoebelL — APPROVED** [review]

**Review by GoebelL — APPROVED** [review]
> Reviewed 4 of 98 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/597)* status: all files reviewed, 3 unresolved discussions (waiting on @GoebelL)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/597)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
