### PR TITLE
Task 1089 font awesome

### LINKED ISSUE #1089: Host font-awesome icons and include in branding-package
**Summary**
The font-awesome icons are fetched per URL in the marketplace UI. 
They can be hosted on our portal and included in a "font-awesome" folder in our downloaded branding-package.

**Details**
- Host the font-awesome icons instead of fetching them per URL.
- Include the font-awesome folder and its icons in the branding-package.

**Acceptance criteria**
- Branding package updated with font-awesome folder.
- Updated branding-package README.
- Resulting UI Screenshots.

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- Added font-awesome to ivy-build.
- Included in branding-package.
- Local URL in .xhtml pages instead of CDN.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell
-est6

**Screenshot (if applicable):**
- add a screenshot illustrating your change

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1098)

### CODE REVIEW

**Review by cworf91 — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1098#-:-MJWuSKFCiridoxwFgzm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @GoebelL)

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1098)* status: all files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-portal/WebContent/marketplace/templates/errorcontent.xhtml, line 17 at r3](https://reviewable.io/reviews/servicecatalog/oscm/1098#-MJX1yMD5iwagJm4fXAD:-MJX1yMED0T-HwSf4IGI:bynhzo3) ([raw file](https://github.com/servicecatalog/oscm/blob/7052633a109bf3dde3488d95126999cfb5d82d03/oscm-portal/WebContent/marketplace/templates/errorcontent.xhtml#L17)):*
> ```HTML
>   <link type="text/css" rel="stylesheet"
>         href="${facesContext.externalContext.requestContextPath}/marketplace/font-awesome/css/font-awesome.min.css"/>
> </h:head>
> ```

This is not customizable? Why not ?

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/templates/errorcontent.xhtml, line 17 at r3](https://reviewable.io/reviews/servicecatalog/oscm/1098#-MJX1yMD5iwagJm4fXAD:-MJXWEoc2st4jgpPuuLx:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/7052633a109bf3dde3488d95126999cfb5d82d03/oscm-portal/WebContent/marketplace/templates/errorcontent.xhtml#L17)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

This is not customizable? Why not ?
</blockquote></details>

Done.

**Review by GoebelL — CHANGES_REQUESTED** [review]
___
*[oscm-portal/WebContent/marketplace/customBootstrap/README.md, line 33 at r4](https://reviewable.io/reviews/servicecatalog/oscm/1098#-MJlYFSQ55xj2bLKTlCt:-MJlYFSQ55xj2bLKTlCu:b-53k4ym) ([raw file](https://github.com/servicecatalog/oscm/blob/346ea5de798ff51df17276f56e3680a363905936/oscm-portal/WebContent/marketplace/customBootstrap/README.md#L33)):*
> ```Markdown
> 	
> 	-   `font-awesome`: Contains a local copy of font-awesome v4.7.0 with WebFonts and CSS. It is useful only if you wish to customize the font-awesome icons yourself. For more details look this [here](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself).
> ```

One general request:  please take care for stability of your documents. Revision numbers change with every update and very quickly make this text to appear out-dated or inconsistent. Better don't mention them, unless they are essential for understanding this description.

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1098)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @cworf91, @farmakiG, and @GoebelL)

___
*[oscm-portal/WebContent/marketplace/customBootstrap/README.md, line 33 at r4](https://reviewable.io/reviews/servicecatalog/oscm/1098#-MJlYFSQ55xj2bLKTlCt:-MK-EuA7AslLPm4MlYY1:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/346ea5de798ff51df17276f56e3680a363905936/oscm-portal/WebContent/marketplace/customBootstrap/README.md#L33)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Please take care for stability of your document content. Revision numbers change with every update and very quickly make this text to appear out-dated or inconsistent. Better don't mention them, unless they are essential for understanding this description.
</blockquote></details>

Done.

**Comment by farmakiG** [comment]
___
*[oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java, line 377 at r4](https://reviewable.io/reviews/servicecatalog/oscm/1098#-MJlWw353aS0_dw0vgyC:-MK-ExeE9o4tAnEcNWsG:bvbit6) ([raw file](https://github.com/servicecatalog/oscm/blob/346ea5de798ff51df17276f56e3680a363905936/oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java#L377)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

I am missing a JUnit test in your change set, that covers the bootstrapBrandBaseUrl check when getMarketplaceId() is null.
</blockquote></details>

There is already a unit test implemented.

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1098)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @cworf91, @farmakiG, and @GoebelL)

___
*[oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java, line 377 at r4](https://reviewable.io/reviews/servicecatalog/oscm/1098#-MJlWw353aS0_dw0vgyC:-MK-F4xpCpzyZXlTumlv:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/346ea5de798ff51df17276f56e3680a363905936/oscm-portal/javasrc/org/oscm/ui/beans/SessionBean.java#L377)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

There is already a unit test implemented.
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r4, 1 of 1 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1098)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
