### PR TITLE
Task/784

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
- Created a service details page using bootstrap.

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [x] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
/view/Docker_OSCM/job/OSCM_Integration_Tests_OIDC/224/
/view/Docker_OSCM/job/OSCM_Integration_Tests_INTERNAL/117/

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/797)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/797)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @mchudy-fujitsu)

___
*[oscm-portal/javasrc/org/oscm/ui/dialog/mp/serviceDetails/ServiceDetailsCtrl.java, line 153 at r1](https://reviewable.io/reviews/servicecatalog/oscm/797#-M5LM30O-humDoqZ4TuZ:-M5LM30P35eL68yjTwUh:b-52fkzf) ([raw file](https://github.com/servicecatalog/oscm/blob/e3b3e06d2eb5c5a57a824173777771b13869dc53/oscm-portal/javasrc/org/oscm/ui/dialog/mp/serviceDetails/ServiceDetailsCtrl.java#L153)):*
> ```Java
>         ExternalContext extContext = context.getExternalContext();
>         String viewId = ui.getMarketplaceId().startsWith("pg_") ? Marketplace.MARKETPLACE_ROOT + "/playgroundServiceDetails.jsf" : Marketplace.MARKETPLACE_ROOT + "/serviceDetails.jsf";
> ```

- Extract condition e.g. getTargetURL
- Add unit tests

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/797)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-portal/javasrc/org/oscm/ui/dialog/mp/serviceDetails/ServiceDetailsCtrl.java, line 153 at r1](https://reviewable.io/reviews/servicecatalog/oscm/797#-M5LM30O-humDoqZ4TuZ:-M5LWWls-ed3bH4pihtJ:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/e3b3e06d2eb5c5a57a824173777771b13869dc53/oscm-portal/javasrc/org/oscm/ui/dialog/mp/serviceDetails/ServiceDetailsCtrl.java#L153)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

- Extract condition e.g. getTargetURL
- Add unit tests
</blockquote></details>

Done.

**Review by GoebelL — DISMISSED** [review]
> Reviewed 10 of 14 files at r1, 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/797)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/WEB-INF/faces-config.xml, line 1149 at r2](https://reviewable.io/reviews/servicecatalog/oscm/797#-M5Wcv9TDJQzgE1KHBFs:-M5Wcv9U2gMjjJecpp6Y:b-hnsd2f) ([raw file](https://github.com/servicecatalog/oscm/blob/1fa159402c2dab30bf89843ffb1eb044527fb872/oscm-portal/WebContent/WEB-INF/faces-config.xml#L1149)):*
> ```XML
>       <from-outcome>addSubscription</from-outcome>
>       <to-view-id>/marketplace/subscriptions/creation/add.xhtml</to-view-id>
>       <redirect />
> ```

Shouldn 't the navigation go to playgroundAdd.xhtml ?

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/797)* status: all files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-portal/WebContent/WEB-INF/faces-config.xml, line 1149 at r2](https://reviewable.io/reviews/servicecatalog/oscm/797#-M5Wcv9TDJQzgE1KHBFs:-M5Wf1Gw52i8iVTRAEtM:b-pv28qc) ([raw file](https://github.com/servicecatalog/oscm/blob/1fa159402c2dab30bf89843ffb1eb044527fb872/oscm-portal/WebContent/WEB-INF/faces-config.xml#L1149)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Shouldn 't the navigation go to playgroundAdd.xhtml ?
</blockquote></details>

It will but with other PR, playgroundAdd is not part of this PR, it doesn't exist yet.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/playgroundServiceDetails.xhtml, line 14 at r2](https://reviewable.io/reviews/servicecatalog/oscm/797#-M5Wg71FDK3WvIL--p9J:-M5Wg71FDK3WvIL--p9K:b-t1najw) ([raw file](https://github.com/servicecatalog/oscm/blob/1fa159402c2dab30bf89843ffb1eb044527fb872/oscm-portal/WebContent/marketplace/playgroundServiceDetails.xhtml#L14)):*
> ```HTML
>   </ui:define>
> 
>   <ui:define name="feature">
> ```

Remove the comments.

**Review by farmakiG — APPROVED** [review]
> Reviewed 9 of 14 files at r1, 12 of 12 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/797)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
