### PR TITLE
Task#1256 remove console warnings

### LINKED ISSUE #1256: Remove console warnings for Subscriptions tabs
**Version Info**
latest master. 
_Please note that this bug is present since Bootstrap v4.6, so it was not introduced with the 5 version._

**Describe the bug**
When clicking on one the Subscription tabs, Console warnings appear with a ReferenceError.
See below Screenshot.
This bug is probably caused by the call of <a4j:jsFunction> in the subscriptionDetails page.

**How to Reproduce**
1. Go to 'Account=> Subscriptions'
2. Click on the 'edit pen' button.
3. Open the Browser Inspector tools.
4. Click on one of the Tabs, such as ''Configuration' or 'Up/Downgrade'.
5. See the resulting Console warning such as in the screenshot.

**Observed behavior**
Console warnings.

**Expected behavior**
No console warnings.

**Screenshots**
JSException

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- Removed console warnings about: 1) restorePaymentTab in subscriptionDetails page, 2) console warning "TypeError of null" for hexToHSL function.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [X] Changes were tested manually
- [ ] Java code changes are unit tested
- [X] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- est6

**Screenshot (if applicable):**
Screenshot Subscription Tabs Console warning:
TabsWarning

Screenshot no warning:
tabsNoWarning

Screenshot warning hexToHSL
hexToHSL

Screenshot no warning:
noWarning

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1265)

### CODE REVIEW

**Review by GoebelL — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1265)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @farmakiG)

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1265)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-portal/WebContent/marketplace/account/subscriptionDetails.xhtml, line 74 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1265#-McIXoIsC9Vng41hQSDc:-McIXoIsC9Vng41hQSDd:b-pgsr03) ([raw file](https://github.com/servicecatalog/oscm/blob/3f227e2b268a2061f3370c08261b9e2065434220/oscm-portal/WebContent/marketplace/account/subscriptionDetails.xhtml#L74)):*
> ```HTML
>                   jsLeaveTabFunction();
>                   $(this).tab('show');
>                   return true;
> ```

Are you sure restorePaymentTab is not needed? 
a) Did you test the payment tab in existing payed subscriptions ?
b) I assume the method is still needed elsewhere as you didn't remove it completely.  
       - If yes, did you check this part as well? 
       - If no, please remove it completely.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/account/subscriptionDetails.xhtml, line 74 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1265#-McIXoIsC9Vng41hQSDc:-McJg9EG7-5cY2CD---P:bc5vj78) ([raw file](https://github.com/servicecatalog/oscm/blob/3f227e2b268a2061f3370c08261b9e2065434220/oscm-portal/WebContent/marketplace/account/subscriptionDetails.xhtml#L74)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Are you sure restorePaymentTab is not needed? 
a) Did you test the payment tab in existing payed subscriptions ?
b) I assume the method is still needed elsewhere as you didn't remove it completely.  
       - If yes, did you check this part as well? 
       - If no, please remove it completely.
</blockquote></details>

You are right, this function is necessary, but only in the case that the #paymentTab is there.

**Review by farmakiG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1265)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-portal/WebContent/marketplace/account/subscriptionDetails.xhtml, line 74 at r1](https://reviewable.io/reviews/servicecatalog/oscm/1265#-McIXoIsC9Vng41hQSDc:-McJgJFrBcuRr_ULWz5m:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/3f227e2b268a2061f3370c08261b9e2065434220/oscm-portal/WebContent/marketplace/account/subscriptionDetails.xhtml#L74)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

You are right, this function is necessary, but only in the case that the #paymentTab is there.
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/1265)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @farmakiG)

**Pull request merged**
