### PR TITLE
get correct tenant config template

### PR DESCRIPTION
**Pull request by cworf91**
**Changes in this Pull Request:**
- <enter list of changes here>

**Mandatory checks:**
- [ ] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [ ] changes were tested manually
- [ ] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [ ] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM Build And Push job](<enter URL to a job here>)
- [OSCM Pull And Start job](<enter URL to a job here>)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/643)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/643)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cworf91 and @GoebelL)

___
*[oscm-portal/javasrc/org/oscm/ui/dialog/classic/manageTenants/ManageTenantsCtrl.java, line 227 at r1](https://reviewable.io/reviews/servicecatalog/oscm/643#-M-OrC_5ACDMrcQBUdeU:-M-OrC_5ACDMrcQBUdeV:bhxemsv) ([raw file](https://github.com/servicecatalog/oscm/blob/76d99343b1cfaa0a1e1b01012086140967e07484/oscm-portal/javasrc/org/oscm/ui/dialog/classic/manageTenants/ManageTenantsCtrl.java#L227)):*
> ```Java
>     try (InputStream in =
>         fc.getExternalContext().getResourceAsStream("/oidc/tenant-default.properties")) {
>       return IOUtils.toByteArray(in);
> ```


Caution is required with converting strings to byte arrays and vice versa. Commonly we use UTF-8 encoding in files. 

=> Use
 IOUtils.toByteArray(<InputStream in>, <String encoding>)

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/643)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-portal/javasrc/org/oscm/ui/dialog/classic/manageTenants/ManageTenantsCtrl.java, line 227 at r1](https://reviewable.io/reviews/servicecatalog/oscm/643#-M-OrC_5ACDMrcQBUdeU:-M-PI4qg2aWE05aD4Cet:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/76d99343b1cfaa0a1e1b01012086140967e07484/oscm-portal/javasrc/org/oscm/ui/dialog/classic/manageTenants/ManageTenantsCtrl.java#L227)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>


Caution is required with converting strings to byte arrays and vice versa. Commonly we use UTF-8 encoding in files. 

=> Use
 IOUtils.toByteArray(<InputStream in>, <String encoding>)
</blockquote></details>

Done.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/643)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/643)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
