### PR TITLE
Task/799

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
- Created an add subscription page.

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [ ] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [ ] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
N/A

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/815)

### CODE REVIEW

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/buttonBootstrap.xhtml, line 2 at r2](https://reviewable.io/reviews/servicecatalog/oscm/815#-M5gE1OL0_T3yhPpl6jw:-M5gE1OMC7CmFz1jtpxf:b9qz15l) ([raw file](https://github.com/servicecatalog/oscm/blob/e5830d92e9554a625e0e7505dfee4186aa894020/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/buttonBootstrap.xhtml#L2)):*
> ```HTML
> 
> <!DOCTYPE html>
> ```

Update Copyright.

**Review by farmakiG — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/815)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @farmakiG and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/outputStepBootstrap.xhtml, line 4 at r2](https://reviewable.io/reviews/servicecatalog/oscm/815#-M5gFRrb8bHolxyXsLVk:-M5gFRrb8bHolxyXsLVl:b9qz15l) ([raw file](https://github.com/servicecatalog/oscm/blob/e5830d92e9554a625e0e7505dfee4186aa894020/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/outputStepBootstrap.xhtml#L4)):*
> ```HTML
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
>                       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
> <ui:composition 
> ```

Update Copyright.

**Review by farmakiG — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/815)* status: all files reviewed, 2 unresolved discussions (waiting on @mchudy-fujitsu)

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/815)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/buttonBootstrap.xhtml, line 2 at r2](https://reviewable.io/reviews/servicecatalog/oscm/815#-M5gE1OL0_T3yhPpl6jw:-M5uATiG5R-wvGljHL33:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/e5830d92e9554a625e0e7505dfee4186aa894020/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/buttonBootstrap.xhtml#L2)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Update Copyright.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/outputStepBootstrap.xhtml, line 4 at r2](https://reviewable.io/reviews/servicecatalog/oscm/815#-M5gFRrb8bHolxyXsLVk:-M5uAUlo98GSQVi2swy1:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/e5830d92e9554a625e0e7505dfee4186aa894020/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/outputStepBootstrap.xhtml#L4)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Update Copyright.
</blockquote></details>

Done.

**Review by farmakiG — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/815)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
