### PR TITLE
Task/732

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
- Cloud tag on the marketplace
image

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [x] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
/view/Docker_OSCM/job/OSCM_Integration_Tests_INTERNAL/76/

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/753)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/753)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @mchudy-fujitsu)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml, line 24 at r1](https://reviewable.io/reviews/servicecatalog/oscm/753#-M3pFJP-AhW9A6nYvtsU:-M3pFJP-AhW9A6nYvtsV:b-9m8aoa) ([raw file](https://github.com/servicecatalog/oscm/blob/0c81221602f0959e9ea5a524fd1102178557184d/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml#L24)):*
> ```HTML
>         <ul class="nav navbar-nav">
>           
>           <c:if test="#{pageId eq 'marketplace.home'}">
> ```

 @farmakig, @mchudy-fujitsu 
I think this shouldn't be placed in the header but inserted as "aside" composite with the main template.please check.

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/753)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml, line 24 at r1](https://reviewable.io/reviews/servicecatalog/oscm/753#-M3pFJP-AhW9A6nYvtsU:-M3pu4GxCZG7sd8IhHcE:b-e7hvmg) ([raw file](https://github.com/servicecatalog/oscm/blob/0c81221602f0959e9ea5a524fd1102178557184d/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/headerBootstrap.xhtml#L24)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

 @farmakig, @mchudy-fujitsu 
I think this shouldn't be placed in the header but inserted as "aside" composite with the main template.please check.
</blockquote></details>

It is a link inside the nav bar, not navbar below.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/tagCloudBootstrap.xhtml, line 1 at r2](https://reviewable.io/reviews/servicecatalog/oscm/753#-M3uxUYF6aVaeOYreBZ_:-M3uxUYG26Lj4YDnylCw:b9qz15l) ([raw file](https://github.com/servicecatalog/oscm/blob/8e2cc2f0e1984bda687cd5f8ffca334a6570f4dc/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/tagCloudBootstrap.xhtml#L1)):*
> ```HTML
> 
> ```

Update Copyright.

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/753)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @farmakiG and @GoebelL)

___
*[oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/tagCloudBootstrap.xhtml, line 1 at r2](https://reviewable.io/reviews/servicecatalog/oscm/753#-M3uxUYF6aVaeOYreBZ_:-M3uy368Db4qfhUrwOic:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/8e2cc2f0e1984bda687cd5f8ffca334a6570f4dc/oscm-portal/WebContent/WEB-INF/facelets/tags/marketplace/tagCloudBootstrap.xhtml#L1)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Update Copyright.
</blockquote></details>

Done.

**Review by farmakiG — APPROVED** [review]
> Reviewed 2 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/753)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/753)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by GoebelL — APPROVED** [review]
> Reviewed 2 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/753)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
