### PR TITLE
Update VMWare controller configuration

### PR DESCRIPTION
**Pull request by floreks**
### Jenkins job

http://10.140.16.80:8080/job/BUILD_AND_START_DEV/

Should be in sync with https://github.com/servicecatalog/oscm-dockerbuild/pull/117

### CODE REVIEW

**Comment by GoebelL** [comment]
@floreks @maciaszczykm 
The implementation looks fine. However, I am still chewing on the schema change upd_postgresql_01_01_01.sql. The final add constraint statements are unchecked which makes it not re-executable. This seems risky.

**Comment by floreks** [comment]
@GoebelL this is the original schema that we have started with: https://github.com/servicecatalog/oscm/commit/e689055b2e38098647eea3884c05490082ed0c0a#diff-b23c7a82c352745afc53c4d96861c979

It does not have any existence checks. We have actually improved it as we could and added checks wherever it was possible. Unfortunately below code fails when executed by Java driver. It works fine if executed using `psql ... -f script.sql`.
```sql
DO $$
BEGIN
  IF NOT EXISTS(...) THEN ...;
  END IF;
END$$;
```

This is why we couldn't update this last part. There are some solutions to this, however they would require either installing a postgres plugin or reconfiguring database which would have to be a manual step executed by database administrator.

**Comment by maciaszczykm** [comment]
@GoebelL Like @floreks said, we have chosen solution that required no additional plugins or bigger modifications because it was implemented in the same way before our changes. If you would like to improve it at this point let us know, then we can investigate how to make it re-executable.

**Review by GoebelL — APPROVED** [review]
Ok.

**Pull request merged**
