### PR TITLE
Task833/load custom bootstrap

### PR DESCRIPTION
**Pull request by farmakiG**
**Changes in this Pull Request:**
- Added Implementation to save and get customBootstrapUrl in UI and Bean. 
- It will be completed when the MarketplaceService method is added in internal interfaces.

**Mandatory checks:**
- [X] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [ ] Changes were tested manually
- [X] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [ ] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [ ] .MASTER/job/OSCM_WS_Tests_OIDC/
- [x] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [x] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- &lt;CI node number&gt;: &lt;tag&gt;, _example_: ci10:goebell
ci6
**Screenshot (if applicable):**
- add a screenshot illustrating your change

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/926)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 5 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/926)* status: 5 of 15 files reviewed, 6 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties, line 350 at r1](https://reviewable.io/reviews/servicecatalog/oscm/926#-M9S_6LB64MVxU3oYZIG:-M9S_6LB64MVxU3oYZIH:bsgrzpn) ([raw file](https://github.com/servicecatalog/oscm/blob/817d8ef6bc449e2bc16f8f0eecf95cda4a8e3476/oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties#L350)):*
> ```INI
> info.currencies.added=Die W\u00E4hrung {0} wurde erfolgreich angelegt.
> info.customBootstrapUrl.set=Die URL des customisiertes Stylesheets f�r Bootstrap wurde erfolgreich gespeichert. Beachten Sie, dass das neue Layout erst mit der n\u00E4chsten Anmeldung am System wirksam wird.
> info.direct.subscription.created.disable.info=Das Abo {0} wurde erfolgreich angelegt.
> ```

For language and encoding:
"Die URL f\u00FCr die Kundenanpassungen der Bootstap Stylesheets wurde erfolgreich gespeichert..."
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties, line 629 at r1](https://reviewable.io/reviews/servicecatalog/oscm/926#-M9Sax2E19TuomMiaB-0:-M9Sax2E19TuomMiaB-1:b-ivcjfj) ([raw file](https://github.com/servicecatalog/oscm/blob/817d8ef6bc449e2bc16f8f0eecf95cda4a8e3476/oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties#L629)):*
> ```INI
> marketplace.create.settings=Einstellungen
> marketplace.create.title=Marktplatz anlegen
> marketplace.customBootstrapUrl=Custom Bootstrap Style sheet URL
> ```

That's an English description. Translation is context dependant
I suggest "URL f\u00FCr Bootstrap Stylesheet Kundenanpassungen" or simply
"Bootstrap Stylesheet URL" if that's enough clear in the given context 
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_en.properties, line 349 at r1](https://reviewable.io/reviews/servicecatalog/oscm/926#-M9Sesxj2dXIU4A4L3Vq:-M9Sesxj2dXIU4A4L3Vr:b56b3ne) ([raw file](https://github.com/servicecatalog/oscm/blob/817d8ef6bc449e2bc16f8f0eecf95cda4a8e3476/oscm-portal/javares/org/oscm/ui/resources/Messages_en.properties#L349)):*
> ```INI
> info.cssConnection.success=The URL is accessible.
> info.currencies.added=The currency {0} has been successfully added.
> info.customBootstrapUrl.set=The URL for the customized Bootstrap has been successfully set. Note that in order for the custom Bootstrap layout to become effective, the user must log out and log in to the system again.
> ```

Consider reverse phrasing: "Note that the user must log in again to the system, in order for the custom Bootstrap ...."
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_en.properties, line 629 at r1](https://reviewable.io/reviews/servicecatalog/oscm/926#-M9Sd3Ph1WOlBunYxxLh:-M9Sd3Ph1WOlBunYxxLi:bu0yw5x) ([raw file](https://github.com/servicecatalog/oscm/blob/817d8ef6bc449e2bc16f8f0eecf95cda4a8e3476/oscm-portal/javares/org/oscm/ui/resources/Messages_en.properties#L629)):*
> ```INI
> marketplace.create.settings=Settings
> marketplace.create.title=Create marketplace
> marketplace.customBootstrapUrl=Custom Bootstrap Style sheet URL
> ```

in floating text in lower case : "Bootstrap style sheet", in header upper case: "Bootstrap Style Sheet" 
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties, line 349 at r1](https://reviewable.io/reviews/servicecatalog/oscm/926#-M9SgIPZCKXt0V5WYk_K:-M9SgIPZCKXt0V5WYk_L:byr4ffv) ([raw file](https://github.com/servicecatalog/oscm/blob/817d8ef6bc449e2bc16f8f0eecf95cda4a8e3476/oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties#L349)):*
> ```INI
> info.cssConnection.success=URL\u306f\u30a2\u30af\u30bb\u30b9\u53ef\u80fd\u3067\u3059\u3002
> info.currencies.added=\u901a\u8ca8 {0} \u3092\u4fdd\u5b58\u3057\u307e\u3057\u305f\u3002
> info.customBootstrapUrl.set=The URL for the customized Bootstrap has been successfully set. Note that in order for the custom Bootstrap layout to become effective, the user must log out and log in to the system again.
> ```

see above
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties, line 629 at r1](https://reviewable.io/reviews/servicecatalog/oscm/926#-M9ScuLbCs4NioG9VzCA:-M9ScuLbCs4NioG9VzCB:b5nl4m9) ([raw file](https://github.com/servicecatalog/oscm/blob/817d8ef6bc449e2bc16f8f0eecf95cda4a8e3476/oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties#L629)):*
> ```INI
> marketplace.create.settings=\u6a5f\u80fd
> marketplace.create.title=\u30b5\u30fc\u30d3\u30b9\u30dd\u30fc\u30bf\u30eb\u306e\u767b\u9332
> marketplace.customBootstrapUrl=Custom Bootstrap Style sheet URL
> ```

see en file

**Comment by farmakiG** [comment]
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties, line 350 at r1](https://reviewable.io/reviews/servicecatalog/oscm/926#-M9S_6LB64MVxU3oYZIG:-M9T179b-Bc4o6xBY_HN:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/817d8ef6bc449e2bc16f8f0eecf95cda4a8e3476/oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties#L350)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

For language and encoding:
"Die URL f\u00FCr die Kundenanpassungen der Bootstap Stylesheets wurde erfolgreich gespeichert..."
</blockquote></details>

Done.

**Comment by farmakiG** [comment]
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties, line 629 at r1](https://reviewable.io/reviews/servicecatalog/oscm/926#-M9Sax2E19TuomMiaB-0:-M9T0TIq-zflL59ei8yr:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/817d8ef6bc449e2bc16f8f0eecf95cda4a8e3476/oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties#L629)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

That's an English description. Translation is context dependant
I suggest "URL f\u00FCr Bootstrap Stylesheet Kundenanpassungen" or simply
"Bootstrap Stylesheet URL" if that's enough clear in the given context 
</blockquote></details>

Done.

**Comment by farmakiG** [comment]
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_en.properties, line 349 at r1](https://reviewable.io/reviews/servicecatalog/oscm/926#-M9Sesxj2dXIU4A4L3Vq:-M9T1W2CEXhWRRiuR4KJ:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/817d8ef6bc449e2bc16f8f0eecf95cda4a8e3476/oscm-portal/javares/org/oscm/ui/resources/Messages_en.properties#L349)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Consider reverse phrasing: "Note that the user must log in again to the system, in order for the custom Bootstrap ...."
</blockquote></details>

Done.

**Comment by farmakiG** [comment]
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties, line 349 at r1](https://reviewable.io/reviews/servicecatalog/oscm/926#-M9SgIPZCKXt0V5WYk_K:-M9T3EwB8OuYGi1f5gTN:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/817d8ef6bc449e2bc16f8f0eecf95cda4a8e3476/oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties#L349)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

**Comment by farmakiG** [comment]
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties, line 629 at r1](https://reviewable.io/reviews/servicecatalog/oscm/926#-M9ScuLbCs4NioG9VzCA:-M9T3DDSAwWAgRk0w8Td:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/817d8ef6bc449e2bc16f8f0eecf95cda4a8e3476/oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties#L629)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

see en file
</blockquote></details>

Done.

**Comment by farmakiG** [comment]
___
*[oscm-portal/javares/org/oscm/ui/resources/Messages_en.properties, line 629 at r1](https://reviewable.io/reviews/servicecatalog/oscm/926#-M9Sd3Ph1WOlBunYxxLh:-M9T22CLBbitnt6CT54r:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/817d8ef6bc449e2bc16f8f0eecf95cda4a8e3476/oscm-portal/javares/org/oscm/ui/resources/Messages_en.properties#L629)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

in floating text in lower case : "Bootstrap style sheet", in header upper case: "Bootstrap Style Sheet" 
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 7 of 15 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/926)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
