### PR TITLE
Account payment playground page

### PR DESCRIPTION
**Pull request by mchudy-fujitsu**
**Changes in this Pull Request:**
- New responsive account payment page with resposive modals

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Clean Java code and unit tested changes 
- [ ] UI customizablity is preserved: No hard-coded styling and URL references in JSF views 

**To be checked by the pull request owner:**
- [x] .MASTER/job/BES_MASTER_IT/
- [ ] .MASTER/job/OSCM_WS_Tests_INTERNAL/
- [x] .MASTER/job/OSCM_WS_Tests_OIDC/
- [ ] .MASTER/job/OSCM_Integration_Tests_INTERNAL/
- [x] .MASTER/job/OSCM_Integration_Tests_OIDC/

**Cross repository and core changes:**
- [ ] Interdependent changes have been communicated to the team (if applicable)
- [ ] This pull request includes high risk modifications or core changes (e.g API, datamodel, authentication...). Mandatory reviewers: @goebell or @kowalczyka.

**OSCM Build References:**
- view/Docker_OSCM/job/OSCM_Integration_Tests_INTERNAL/156/

**Screenshot (if applicable):**
FireShot Capture 038 - Marketplace - 10 140 18 99
FireShot Capture 039 - Marketplace - 10 140 18 99
FireShot Capture 042 - Marketplace - 10 140 18 99
FireShot Capture 032 - Marketplace - 10 140 18 99
FireShot Capture 033 - Marketplace - 10 140 18 99
FireShot Capture 034 - Marketplace - 10 140 18 99
FireShot Capture 035 - Marketplace - 10 140 18 99
FireShot Capture 036 - Marketplace - 10 140 18 99
FireShot Capture 037 - Marketplace - 10 140 18 99

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/843)

### CODE REVIEW

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/account/playgroundBillingContact.xhtml, line 67 at r1](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72fQxY6RgfHltwCn2v:-M72fQxZ7Czl-dGBqoCo:bxw0b45) ([raw file](https://github.com/servicecatalog/oscm/blob/61a2dba16981a0f21d55ceb647e2c5cf50f995a9/oscm-portal/WebContent/marketplace/account/playgroundBillingContact.xhtml#L67)):*
> ```HTML
>             <div class="col-md-6 col-sm-12">
>               <h:inputText id="companyName" label="#{msg['billingContact.organizationName']}"
>                            value="#{billingContactBean.billingContact.companyName}" maxlength="#{appBean.nameLen}"
> ```

Do not delete the "field" class as I am not sure about possible Validator execution in the background. You can add w-100.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/account/playgroundBillingContacts.xhtml, line 24 at r1](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72fjG56cgpOoMHA5Cd:-M72fjG56cgpOoMHA5Ce:b167dim) ([raw file](https://github.com/servicecatalog/oscm/blob/61a2dba16981a0f21d55ceb647e2c5cf50f995a9/oscm-portal/WebContent/marketplace/account/playgroundBillingContacts.xhtml#L24)):*
> ```HTML
>             </div>
>             <div class="col-12 mb-2">
>                 <a4j:commandLink styleClass="btn-sm btn-secondary text-white text-decoration-none"
> ```

Use text-light instead (remember customization if we switch to a light theme, then this text with text-white will not appear).

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionEdit.xhtml, line 9 at r1](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72fyAi5Z0hA9va_pBx:-M72fyAi5Z0hA9va_pBy:b-hq8ryy) ([raw file](https://github.com/servicecatalog/oscm/blob/61a2dba16981a0f21d55ceb647e2c5cf50f995a9/oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionEdit.xhtml#L9)):*
> ```HTML
>                 xmlns:h="http://xmlns.jcp.org/jsf/html" template="../templates/modalDialogBootstrap.xhtml">
> 
>   <ui:define name="dialogScripts">
> ```

Why not use declaration for html 5:  <!DOCTYPE html>

**Review by farmakiG — CHANGES_REQUESTED** [review]
> Reviewed 3 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/843)* status: 3 of 18 files reviewed, 4 unresolved discussions (waiting on @farmakiG and @mchudy-fujitsu)

___
*[oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionInclude.xhtml, line 32 at r1](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72gB8o6h20aZFGZXK2:-M72gB8o6h20aZFGZXK3:b664ec4) ([raw file](https://github.com/servicecatalog/oscm/blob/61a2dba16981a0f21d55ceb647e2c5cf50f995a9/oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionInclude.xhtml#L32)):*
> ```HTML
>               </div>
>               <div class="col-md-5 col-sm-12">
>                 <h:inputText id="displayName" label="#{msg['billingContact.displayName']}" onchange="setDirty(true)" styleClass="w-100"
> ```

Same comment as before for styleClass="field"

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/account/playgroundPayments.xhtml, line 15 at r1](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72gc0j2DKZsSc-72a9:-M72gc0j2DKZsSc-72aA:b1e49lc) ([raw file](https://github.com/servicecatalog/oscm/blob/61a2dba16981a0f21d55ceb647e2c5cf50f995a9/oscm-portal/WebContent/marketplace/account/playgroundPayments.xhtml#L15)):*
> ```HTML
> 
>   <ui:define name="breadcrumbs">
>     <mp:bootstrapBreadcrumbs>
> ```

Add link to account playground page.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/account/playgroundBillingContacts.xhtml, line 53 at r1](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72huXF8eFJCRAerP1E:-M72huXF8eFJCRAerP1F:b-mg44dl) ([raw file](https://github.com/servicecatalog/oscm/blob/61a2dba16981a0f21d55ceb647e2c5cf50f995a9/oscm-portal/WebContent/marketplace/account/playgroundBillingContacts.xhtml#L53)):*
> ```HTML
>                     <h:outputText value="#{msg['billingContact.contactInformation']}" />
>                   </f:facet>
>                   <a4j:outputPanel layout="block" style="min-height: 50px;">
> ```

avoid inline styling.

**Review by farmakiG — COMMENTED** [review]
> Reviewed 2 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/843)* status: 5 of 18 files reviewed, 6 unresolved discussions (waiting on @mchudy-fujitsu)

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/account/playgroundPaymentOption.xhtml, line 30 at r2](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72jFVt4m58u6Jgq44U:-M72jFVu9rYFXSeEqs2J:b-japio8) ([raw file](https://github.com/servicecatalog/oscm/blob/535a4d66547a19b69f3e103429402bcb71544574/oscm-portal/WebContent/marketplace/account/playgroundPaymentOption.xhtml#L30)):*
> ```HTML
>     <c:set var="includePrefix" value="include"/>
>     
>     <ui:include src="/marketplace/account/playgroundPaymentOptionInclude.xhtml"/>
> ```

Why did you delete this line?     <ui:include src="/marketplace/account/#{paymentInfoBean.paymentTypeRegisterPage}.xhtml"  What was the reason for this page being fetched from PaymentInfoBean?

**Review by farmakiG — COMMENTED** [review]
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/843)* status: 6 of 18 files reviewed, 7 unresolved discussions (waiting on @mchudy-fujitsu)

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionEdit.xhtml, line 34 at r2](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72jpXDAJuWoMcxRK_0:-M72jpXDAJuWoMcxRK_1:b-a20pjr) ([raw file](https://github.com/servicecatalog/oscm/blob/535a4d66547a19b69f3e103429402bcb71544574/oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionEdit.xhtml#L34)):*
> ```HTML
>   <ui:define name="fullDialogContent">
>     <c:set var="includePrefix" value="include"/>
>     <ui:include src="/marketplace/account/playgroundPaymentOptionIncludeEdit.xhtml"/>
> ```

Same comment as above with PaymentInfoBean.

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/843)* status: 5 of 21 files reviewed, 8 unresolved discussions (waiting on @farmakiG)

___
*[oscm-portal/WebContent/marketplace/account/playgroundBillingContact.xhtml, line 67 at r1](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72fQxY6RgfHltwCn2v:-M72kpJZ93vbosRKr_6m:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/61a2dba16981a0f21d55ceb647e2c5cf50f995a9/oscm-portal/WebContent/marketplace/account/playgroundBillingContact.xhtml#L67)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Do not delete the "field" class as I am not sure about possible Validator execution in the background. You can add w-100.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/account/playgroundBillingContacts.xhtml, line 24 at r1](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72fjG56cgpOoMHA5Cd:-M76eIam4kZISST_6JoQ:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/61a2dba16981a0f21d55ceb647e2c5cf50f995a9/oscm-portal/WebContent/marketplace/account/playgroundBillingContacts.xhtml#L24)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Use text-light instead (remember customization if we switch to a light theme, then this text with text-white will not appear).
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/account/playgroundBillingContacts.xhtml, line 53 at r1](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72huXF8eFJCRAerP1E:-M76eQPA1UUSMHSvIXfM:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/61a2dba16981a0f21d55ceb647e2c5cf50f995a9/oscm-portal/WebContent/marketplace/account/playgroundBillingContacts.xhtml#L53)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

avoid inline styling.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/account/playgroundPaymentOption.xhtml, line 30 at r2](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72jFVt4m58u6Jgq44U:-M76e_4E5Wvg_eM4CcFJ:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/535a4d66547a19b69f3e103429402bcb71544574/oscm-portal/WebContent/marketplace/account/playgroundPaymentOption.xhtml#L30)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Why did you delete this line?     <ui:include src="/marketplace/account/#{paymentInfoBean.paymentTypeRegisterPage}.xhtml"  What was the reason for this page being fetched from PaymentInfoBean?
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionEdit.xhtml, line 9 at r1](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72fyAi5Z0hA9va_pBx:-M72kuZIAz8vrgNkf7V8:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/61a2dba16981a0f21d55ceb647e2c5cf50f995a9/oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionEdit.xhtml#L9)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Why not use declaration for html 5:  <!DOCTYPE html>
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionEdit.xhtml, line 34 at r2](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72jpXDAJuWoMcxRK_0:-M76edGn1IeKD8wbo59P:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/535a4d66547a19b69f3e103429402bcb71544574/oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionEdit.xhtml#L34)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Same comment as above with PaymentInfoBean.
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionInclude.xhtml, line 32 at r1](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72gB8o6h20aZFGZXK2:-M72kvnqCoIvsLpiv69f:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/61a2dba16981a0f21d55ceb647e2c5cf50f995a9/oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionInclude.xhtml#L32)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Same comment as before for styleClass="field"
</blockquote></details>

Done.
___
*[oscm-portal/WebContent/marketplace/account/playgroundPayments.xhtml, line 15 at r1](https://reviewable.io/reviews/servicecatalog/oscm/843#-M72gc0j2DKZsSc-72a9:-M76eemACa_yj1pvg7ZK:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/61a2dba16981a0f21d55ceb647e2c5cf50f995a9/oscm-portal/WebContent/marketplace/account/playgroundPayments.xhtml#L15)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Add link to account playground page.
</blockquote></details>

Done.

**Comment by farmakiG** [comment]
___
*[oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionEdit.xhtml, line 35 at r2](https://reviewable.io/reviews/servicecatalog/oscm/843#-M76g8rpDG1DAE3I_K3H:-M76g8rpDG1DAE3I_K3I:b-9i1488) ([raw file](https://github.com/servicecatalog/oscm/blob/535a4d66547a19b69f3e103429402bcb71544574/oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionEdit.xhtml#L35)):*
> ```HTML
>     <c:set var="includePrefix" value="include"/>
>     <ui:include src="/marketplace/account/playgroundPaymentOptionIncludeEdit.xhtml"/>
>   </ui:define>
> ```

I think in this case it was correct before (playgroundPaymentOptionIncludeEdit.xhtml)

**Review by farmakiG — COMMENTED** [review]
> Reviewed 3 of 18 files at r1, 4 of 11 files at r2, 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/843)* status: all files reviewed, 1 unresolved discussion (waiting on @mchudy-fujitsu)

**Review by mchudy-fujitsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/843)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @farmakiG)

___
*[oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionEdit.xhtml, line 35 at r2](https://reviewable.io/reviews/servicecatalog/oscm/843#-M76g8rpDG1DAE3I_K3H:-M76iEVr1JXuiXMJwAY6:b-896fix) ([raw file](https://github.com/servicecatalog/oscm/blob/535a4d66547a19b69f3e103429402bcb71544574/oscm-portal/WebContent/marketplace/account/playgroundPaymentOptionEdit.xhtml#L35)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

I think in this case it was correct before (playgroundPaymentOptionIncludeEdit.xhtml)
</blockquote></details>

Done.

**Review by farmakiG — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm/843)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
